// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreFactory creates a new instance of MockStoreFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreFactory {
	mock := &MockStoreFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreFactory is an autogenerated mock type for the StoreFactory type
type MockStoreFactory struct {
	mock.Mock
}

type MockStoreFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreFactory) EXPECT() *MockStoreFactory_Expecter {
	return &MockStoreFactory_Expecter{mock: &_m.Mock}
}

// NewStore provides a mock function for the type MockStoreFactory
func (_mock *MockStoreFactory) NewStore(cluster string) ComplianceStore {
	ret := _mock.Called(cluster)

	if len(ret) == 0 {
		panic("no return value specified for NewStore")
	}

	var r0 ComplianceStore
	if returnFunc, ok := ret.Get(0).(func(string) ComplianceStore); ok {
		r0 = returnFunc(cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ComplianceStore)
		}
	}
	return r0
}

// MockStoreFactory_NewStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStore'
type MockStoreFactory_NewStore_Call struct {
	*mock.Call
}

// NewStore is a helper method to define mock.On call
//   - cluster string
func (_e *MockStoreFactory_Expecter) NewStore(cluster interface{}) *MockStoreFactory_NewStore_Call {
	return &MockStoreFactory_NewStore_Call{Call: _e.mock.On("NewStore", cluster)}
}

func (_c *MockStoreFactory_NewStore_Call) Run(run func(cluster string)) *MockStoreFactory_NewStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStoreFactory_NewStore_Call) Return(complianceStore ComplianceStore) *MockStoreFactory_NewStore_Call {
	_c.Call.Return(complianceStore)
	return _c
}

func (_c *MockStoreFactory_NewStore_Call) RunAndReturn(run func(cluster string) ComplianceStore) *MockStoreFactory_NewStore_Call {
	_c.Call.Return(run)
	return _c
}
