// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportEventFetcher creates a new instance of MockReportEventFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportEventFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportEventFetcher {
	mock := &MockReportEventFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportEventFetcher is an autogenerated mock type for the ReportEventFetcher type
type MockReportEventFetcher struct {
	mock.Mock
}

type MockReportEventFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportEventFetcher) EXPECT() *MockReportEventFetcher_Expecter {
	return &MockReportEventFetcher_Expecter{mock: &_m.Mock}
}

// GetAuditEvents provides a mock function for the type MockReportEventFetcher
func (_mock *MockReportEventFetcher) GetAuditEvents(context1 context.Context, time1 *time.Time, time11 *time.Time) <-chan *AuditEventResult {
	ret := _mock.Called(context1, time1, time11)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditEvents")
	}

	var r0 <-chan *AuditEventResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) <-chan *AuditEventResult); ok {
		r0 = returnFunc(context1, time1, time11)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *AuditEventResult)
		}
	}
	return r0
}

// MockReportEventFetcher_GetAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditEvents'
type MockReportEventFetcher_GetAuditEvents_Call struct {
	*mock.Call
}

// GetAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 *time.Time
//   - time11 *time.Time
func (_e *MockReportEventFetcher_Expecter) GetAuditEvents(context1 interface{}, time1 interface{}, time11 interface{}) *MockReportEventFetcher_GetAuditEvents_Call {
	return &MockReportEventFetcher_GetAuditEvents_Call{Call: _e.mock.On("GetAuditEvents", context1, time1, time11)}
}

func (_c *MockReportEventFetcher_GetAuditEvents_Call) Run(run func(context1 context.Context, time1 *time.Time, time11 *time.Time)) *MockReportEventFetcher_GetAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportEventFetcher_GetAuditEvents_Call) Return(auditEventResultCh <-chan *AuditEventResult) *MockReportEventFetcher_GetAuditEvents_Call {
	_c.Call.Return(auditEventResultCh)
	return _c
}

func (_c *MockReportEventFetcher_GetAuditEvents_Call) RunAndReturn(run func(context1 context.Context, time1 *time.Time, time11 *time.Time) <-chan *AuditEventResult) *MockReportEventFetcher_GetAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}
