// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
	"github.com/projectcalico/calico/lma/pkg/api"
	"github.com/projectcalico/calico/lma/pkg/list"
)

// NewMockComplianceStore creates a new instance of MockComplianceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplianceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplianceStore {
	mock := &MockComplianceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComplianceStore is an autogenerated mock type for the ComplianceStore type
type MockComplianceStore struct {
	mock.Mock
}

type MockComplianceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplianceStore) EXPECT() *MockComplianceStore_Expecter {
	return &MockComplianceStore_Expecter{mock: &_m.Mock}
}

// GetAuditEvents provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) GetAuditEvents(context1 context.Context, time1 *time.Time, time11 *time.Time) <-chan *AuditEventResult {
	ret := _mock.Called(context1, time1, time11)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditEvents")
	}

	var r0 <-chan *AuditEventResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) <-chan *AuditEventResult); ok {
		r0 = returnFunc(context1, time1, time11)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *AuditEventResult)
		}
	}
	return r0
}

// MockComplianceStore_GetAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditEvents'
type MockComplianceStore_GetAuditEvents_Call struct {
	*mock.Call
}

// GetAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 *time.Time
//   - time11 *time.Time
func (_e *MockComplianceStore_Expecter) GetAuditEvents(context1 interface{}, time1 interface{}, time11 interface{}) *MockComplianceStore_GetAuditEvents_Call {
	return &MockComplianceStore_GetAuditEvents_Call{Call: _e.mock.On("GetAuditEvents", context1, time1, time11)}
}

func (_c *MockComplianceStore_GetAuditEvents_Call) Run(run func(context1 context.Context, time1 *time.Time, time11 *time.Time)) *MockComplianceStore_GetAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockComplianceStore_GetAuditEvents_Call) Return(auditEventResultCh <-chan *AuditEventResult) *MockComplianceStore_GetAuditEvents_Call {
	_c.Call.Return(auditEventResultCh)
	return _c
}

func (_c *MockComplianceStore_GetAuditEvents_Call) RunAndReturn(run func(context1 context.Context, time1 *time.Time, time11 *time.Time) <-chan *AuditEventResult) *MockComplianceStore_GetAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveArchivedReport provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveArchivedReport(ctx context.Context, id string) (*v1.ReportData, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveArchivedReport")
	}

	var r0 *v1.ReportData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.ReportData, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.ReportData); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ReportData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComplianceStore_RetrieveArchivedReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveArchivedReport'
type MockComplianceStore_RetrieveArchivedReport_Call struct {
	*mock.Call
}

// RetrieveArchivedReport is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockComplianceStore_Expecter) RetrieveArchivedReport(ctx interface{}, id interface{}) *MockComplianceStore_RetrieveArchivedReport_Call {
	return &MockComplianceStore_RetrieveArchivedReport_Call{Call: _e.mock.On("RetrieveArchivedReport", ctx, id)}
}

func (_c *MockComplianceStore_RetrieveArchivedReport_Call) Run(run func(ctx context.Context, id string)) *MockComplianceStore_RetrieveArchivedReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReport_Call) Return(reportData *v1.ReportData, err error) *MockComplianceStore_RetrieveArchivedReport_Call {
	_c.Call.Return(reportData, err)
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReport_Call) RunAndReturn(run func(ctx context.Context, id string) (*v1.ReportData, error)) *MockComplianceStore_RetrieveArchivedReport_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveArchivedReportSummaries provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveArchivedReportSummaries(cxt context.Context, q ReportQueryParams) (*ArchivedReportSummaries, error) {
	ret := _mock.Called(cxt, q)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveArchivedReportSummaries")
	}

	var r0 *ArchivedReportSummaries
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReportQueryParams) (*ArchivedReportSummaries, error)); ok {
		return returnFunc(cxt, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReportQueryParams) *ArchivedReportSummaries); ok {
		r0 = returnFunc(cxt, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ArchivedReportSummaries)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReportQueryParams) error); ok {
		r1 = returnFunc(cxt, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComplianceStore_RetrieveArchivedReportSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveArchivedReportSummaries'
type MockComplianceStore_RetrieveArchivedReportSummaries_Call struct {
	*mock.Call
}

// RetrieveArchivedReportSummaries is a helper method to define mock.On call
//   - cxt context.Context
//   - q ReportQueryParams
func (_e *MockComplianceStore_Expecter) RetrieveArchivedReportSummaries(cxt interface{}, q interface{}) *MockComplianceStore_RetrieveArchivedReportSummaries_Call {
	return &MockComplianceStore_RetrieveArchivedReportSummaries_Call{Call: _e.mock.On("RetrieveArchivedReportSummaries", cxt, q)}
}

func (_c *MockComplianceStore_RetrieveArchivedReportSummaries_Call) Run(run func(cxt context.Context, q ReportQueryParams)) *MockComplianceStore_RetrieveArchivedReportSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReportQueryParams
		if args[1] != nil {
			arg1 = args[1].(ReportQueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReportSummaries_Call) Return(archivedReportSummaries *ArchivedReportSummaries, err error) *MockComplianceStore_RetrieveArchivedReportSummaries_Call {
	_c.Call.Return(archivedReportSummaries, err)
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReportSummaries_Call) RunAndReturn(run func(cxt context.Context, q ReportQueryParams) (*ArchivedReportSummaries, error)) *MockComplianceStore_RetrieveArchivedReportSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveArchivedReportTypeAndNames provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveArchivedReportTypeAndNames(cxt context.Context, q ReportQueryParams) ([]ReportTypeAndName, error) {
	ret := _mock.Called(cxt, q)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveArchivedReportTypeAndNames")
	}

	var r0 []ReportTypeAndName
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReportQueryParams) ([]ReportTypeAndName, error)); ok {
		return returnFunc(cxt, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReportQueryParams) []ReportTypeAndName); ok {
		r0 = returnFunc(cxt, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ReportTypeAndName)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReportQueryParams) error); ok {
		r1 = returnFunc(cxt, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveArchivedReportTypeAndNames'
type MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call struct {
	*mock.Call
}

// RetrieveArchivedReportTypeAndNames is a helper method to define mock.On call
//   - cxt context.Context
//   - q ReportQueryParams
func (_e *MockComplianceStore_Expecter) RetrieveArchivedReportTypeAndNames(cxt interface{}, q interface{}) *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call {
	return &MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call{Call: _e.mock.On("RetrieveArchivedReportTypeAndNames", cxt, q)}
}

func (_c *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call) Run(run func(cxt context.Context, q ReportQueryParams)) *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReportQueryParams
		if args[1] != nil {
			arg1 = args[1].(ReportQueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call) Return(reportTypeAndNames []ReportTypeAndName, err error) *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call {
	_c.Call.Return(reportTypeAndNames, err)
	return _c
}

func (_c *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call) RunAndReturn(run func(cxt context.Context, q ReportQueryParams) ([]ReportTypeAndName, error)) *MockComplianceStore_RetrieveArchivedReportTypeAndNames_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveLastArchivedReportSummary provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveLastArchivedReportSummary(ctx context.Context, name string) (*v1.ReportData, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveLastArchivedReportSummary")
	}

	var r0 *v1.ReportData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.ReportData, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.ReportData); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ReportData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComplianceStore_RetrieveLastArchivedReportSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveLastArchivedReportSummary'
type MockComplianceStore_RetrieveLastArchivedReportSummary_Call struct {
	*mock.Call
}

// RetrieveLastArchivedReportSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockComplianceStore_Expecter) RetrieveLastArchivedReportSummary(ctx interface{}, name interface{}) *MockComplianceStore_RetrieveLastArchivedReportSummary_Call {
	return &MockComplianceStore_RetrieveLastArchivedReportSummary_Call{Call: _e.mock.On("RetrieveLastArchivedReportSummary", ctx, name)}
}

func (_c *MockComplianceStore_RetrieveLastArchivedReportSummary_Call) Run(run func(ctx context.Context, name string)) *MockComplianceStore_RetrieveLastArchivedReportSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveLastArchivedReportSummary_Call) Return(reportData *v1.ReportData, err error) *MockComplianceStore_RetrieveLastArchivedReportSummary_Call {
	_c.Call.Return(reportData, err)
	return _c
}

func (_c *MockComplianceStore_RetrieveLastArchivedReportSummary_Call) RunAndReturn(run func(ctx context.Context, name string) (*v1.ReportData, error)) *MockComplianceStore_RetrieveLastArchivedReportSummary_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveLatestBenchmarks provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveLatestBenchmarks(ctx context.Context, ct v1.BenchmarkType, filters []v1.BenchmarksFilter, start time.Time, end time.Time) <-chan BenchmarksResult {
	ret := _mock.Called(ctx, ct, filters, start, end)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveLatestBenchmarks")
	}

	var r0 <-chan BenchmarksResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.BenchmarkType, []v1.BenchmarksFilter, time.Time, time.Time) <-chan BenchmarksResult); ok {
		r0 = returnFunc(ctx, ct, filters, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan BenchmarksResult)
		}
	}
	return r0
}

// MockComplianceStore_RetrieveLatestBenchmarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveLatestBenchmarks'
type MockComplianceStore_RetrieveLatestBenchmarks_Call struct {
	*mock.Call
}

// RetrieveLatestBenchmarks is a helper method to define mock.On call
//   - ctx context.Context
//   - ct v1.BenchmarkType
//   - filters []v1.BenchmarksFilter
//   - start time.Time
//   - end time.Time
func (_e *MockComplianceStore_Expecter) RetrieveLatestBenchmarks(ctx interface{}, ct interface{}, filters interface{}, start interface{}, end interface{}) *MockComplianceStore_RetrieveLatestBenchmarks_Call {
	return &MockComplianceStore_RetrieveLatestBenchmarks_Call{Call: _e.mock.On("RetrieveLatestBenchmarks", ctx, ct, filters, start, end)}
}

func (_c *MockComplianceStore_RetrieveLatestBenchmarks_Call) Run(run func(ctx context.Context, ct v1.BenchmarkType, filters []v1.BenchmarksFilter, start time.Time, end time.Time)) *MockComplianceStore_RetrieveLatestBenchmarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.BenchmarkType
		if args[1] != nil {
			arg1 = args[1].(v1.BenchmarkType)
		}
		var arg2 []v1.BenchmarksFilter
		if args[2] != nil {
			arg2 = args[2].([]v1.BenchmarksFilter)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveLatestBenchmarks_Call) Return(benchmarksResultCh <-chan BenchmarksResult) *MockComplianceStore_RetrieveLatestBenchmarks_Call {
	_c.Call.Return(benchmarksResultCh)
	return _c
}

func (_c *MockComplianceStore_RetrieveLatestBenchmarks_Call) RunAndReturn(run func(ctx context.Context, ct v1.BenchmarkType, filters []v1.BenchmarksFilter, start time.Time, end time.Time) <-chan BenchmarksResult) *MockComplianceStore_RetrieveLatestBenchmarks_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveList provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) RetrieveList(kind v10.TypeMeta, from *time.Time, to *time.Time, sortAscendingTime bool) (*list.TimestampedResourceList, error) {
	ret := _mock.Called(kind, from, to, sortAscendingTime)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveList")
	}

	var r0 *list.TimestampedResourceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(v10.TypeMeta, *time.Time, *time.Time, bool) (*list.TimestampedResourceList, error)); ok {
		return returnFunc(kind, from, to, sortAscendingTime)
	}
	if returnFunc, ok := ret.Get(0).(func(v10.TypeMeta, *time.Time, *time.Time, bool) *list.TimestampedResourceList); ok {
		r0 = returnFunc(kind, from, to, sortAscendingTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*list.TimestampedResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(v10.TypeMeta, *time.Time, *time.Time, bool) error); ok {
		r1 = returnFunc(kind, from, to, sortAscendingTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComplianceStore_RetrieveList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveList'
type MockComplianceStore_RetrieveList_Call struct {
	*mock.Call
}

// RetrieveList is a helper method to define mock.On call
//   - kind v10.TypeMeta
//   - from *time.Time
//   - to *time.Time
//   - sortAscendingTime bool
func (_e *MockComplianceStore_Expecter) RetrieveList(kind interface{}, from interface{}, to interface{}, sortAscendingTime interface{}) *MockComplianceStore_RetrieveList_Call {
	return &MockComplianceStore_RetrieveList_Call{Call: _e.mock.On("RetrieveList", kind, from, to, sortAscendingTime)}
}

func (_c *MockComplianceStore_RetrieveList_Call) Run(run func(kind v10.TypeMeta, from *time.Time, to *time.Time, sortAscendingTime bool)) *MockComplianceStore_RetrieveList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v10.TypeMeta
		if args[0] != nil {
			arg0 = args[0].(v10.TypeMeta)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockComplianceStore_RetrieveList_Call) Return(timestampedResourceList *list.TimestampedResourceList, err error) *MockComplianceStore_RetrieveList_Call {
	_c.Call.Return(timestampedResourceList, err)
	return _c
}

func (_c *MockComplianceStore_RetrieveList_Call) RunAndReturn(run func(kind v10.TypeMeta, from *time.Time, to *time.Time, sortAscendingTime bool) (*list.TimestampedResourceList, error)) *MockComplianceStore_RetrieveList_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAuditEvents provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) SearchAuditEvents(ctx context.Context, filter *v3.AuditEventsSelection, start *time.Time, end *time.Time) <-chan *AuditEventResult {
	ret := _mock.Called(ctx, filter, start, end)

	if len(ret) == 0 {
		panic("no return value specified for SearchAuditEvents")
	}

	var r0 <-chan *AuditEventResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.AuditEventsSelection, *time.Time, *time.Time) <-chan *AuditEventResult); ok {
		r0 = returnFunc(ctx, filter, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *AuditEventResult)
		}
	}
	return r0
}

// MockComplianceStore_SearchAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAuditEvents'
type MockComplianceStore_SearchAuditEvents_Call struct {
	*mock.Call
}

// SearchAuditEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *v3.AuditEventsSelection
//   - start *time.Time
//   - end *time.Time
func (_e *MockComplianceStore_Expecter) SearchAuditEvents(ctx interface{}, filter interface{}, start interface{}, end interface{}) *MockComplianceStore_SearchAuditEvents_Call {
	return &MockComplianceStore_SearchAuditEvents_Call{Call: _e.mock.On("SearchAuditEvents", ctx, filter, start, end)}
}

func (_c *MockComplianceStore_SearchAuditEvents_Call) Run(run func(ctx context.Context, filter *v3.AuditEventsSelection, start *time.Time, end *time.Time)) *MockComplianceStore_SearchAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v3.AuditEventsSelection
		if args[1] != nil {
			arg1 = args[1].(*v3.AuditEventsSelection)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockComplianceStore_SearchAuditEvents_Call) Return(auditEventResultCh <-chan *AuditEventResult) *MockComplianceStore_SearchAuditEvents_Call {
	_c.Call.Return(auditEventResultCh)
	return _c
}

func (_c *MockComplianceStore_SearchAuditEvents_Call) RunAndReturn(run func(ctx context.Context, filter *v3.AuditEventsSelection, start *time.Time, end *time.Time) <-chan *AuditEventResult) *MockComplianceStore_SearchAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFlows provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) SearchFlows(ctx context.Context, namespaces []string, start *time.Time, end *time.Time) <-chan *api.FlowLogResult {
	ret := _mock.Called(ctx, namespaces, start, end)

	if len(ret) == 0 {
		panic("no return value specified for SearchFlows")
	}

	var r0 <-chan *api.FlowLogResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *time.Time, *time.Time) <-chan *api.FlowLogResult); ok {
		r0 = returnFunc(ctx, namespaces, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *api.FlowLogResult)
		}
	}
	return r0
}

// MockComplianceStore_SearchFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFlows'
type MockComplianceStore_SearchFlows_Call struct {
	*mock.Call
}

// SearchFlows is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaces []string
//   - start *time.Time
//   - end *time.Time
func (_e *MockComplianceStore_Expecter) SearchFlows(ctx interface{}, namespaces interface{}, start interface{}, end interface{}) *MockComplianceStore_SearchFlows_Call {
	return &MockComplianceStore_SearchFlows_Call{Call: _e.mock.On("SearchFlows", ctx, namespaces, start, end)}
}

func (_c *MockComplianceStore_SearchFlows_Call) Run(run func(ctx context.Context, namespaces []string, start *time.Time, end *time.Time)) *MockComplianceStore_SearchFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockComplianceStore_SearchFlows_Call) Return(flowLogResultCh <-chan *api.FlowLogResult) *MockComplianceStore_SearchFlows_Call {
	_c.Call.Return(flowLogResultCh)
	return _c
}

func (_c *MockComplianceStore_SearchFlows_Call) RunAndReturn(run func(ctx context.Context, namespaces []string, start *time.Time, end *time.Time) <-chan *api.FlowLogResult) *MockComplianceStore_SearchFlows_Call {
	_c.Call.Return(run)
	return _c
}

// StoreArchivedReport provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) StoreArchivedReport(r *v1.ReportData) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for StoreArchivedReport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*v1.ReportData) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComplianceStore_StoreArchivedReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreArchivedReport'
type MockComplianceStore_StoreArchivedReport_Call struct {
	*mock.Call
}

// StoreArchivedReport is a helper method to define mock.On call
//   - r *v1.ReportData
func (_e *MockComplianceStore_Expecter) StoreArchivedReport(r interface{}) *MockComplianceStore_StoreArchivedReport_Call {
	return &MockComplianceStore_StoreArchivedReport_Call{Call: _e.mock.On("StoreArchivedReport", r)}
}

func (_c *MockComplianceStore_StoreArchivedReport_Call) Run(run func(r *v1.ReportData)) *MockComplianceStore_StoreArchivedReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.ReportData
		if args[0] != nil {
			arg0 = args[0].(*v1.ReportData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockComplianceStore_StoreArchivedReport_Call) Return(err error) *MockComplianceStore_StoreArchivedReport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComplianceStore_StoreArchivedReport_Call) RunAndReturn(run func(r *v1.ReportData) error) *MockComplianceStore_StoreArchivedReport_Call {
	_c.Call.Return(run)
	return _c
}

// StoreBenchmarks provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) StoreBenchmarks(ctx context.Context, b *v1.Benchmarks) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for StoreBenchmarks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Benchmarks) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComplianceStore_StoreBenchmarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreBenchmarks'
type MockComplianceStore_StoreBenchmarks_Call struct {
	*mock.Call
}

// StoreBenchmarks is a helper method to define mock.On call
//   - ctx context.Context
//   - b *v1.Benchmarks
func (_e *MockComplianceStore_Expecter) StoreBenchmarks(ctx interface{}, b interface{}) *MockComplianceStore_StoreBenchmarks_Call {
	return &MockComplianceStore_StoreBenchmarks_Call{Call: _e.mock.On("StoreBenchmarks", ctx, b)}
}

func (_c *MockComplianceStore_StoreBenchmarks_Call) Run(run func(ctx context.Context, b *v1.Benchmarks)) *MockComplianceStore_StoreBenchmarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Benchmarks
		if args[1] != nil {
			arg1 = args[1].(*v1.Benchmarks)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_StoreBenchmarks_Call) Return(err error) *MockComplianceStore_StoreBenchmarks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComplianceStore_StoreBenchmarks_Call) RunAndReturn(run func(ctx context.Context, b *v1.Benchmarks) error) *MockComplianceStore_StoreBenchmarks_Call {
	_c.Call.Return(run)
	return _c
}

// StoreList provides a mock function for the type MockComplianceStore
func (_mock *MockComplianceStore) StoreList(typeMeta v10.TypeMeta, timestampedResourceList *list.TimestampedResourceList) error {
	ret := _mock.Called(typeMeta, timestampedResourceList)

	if len(ret) == 0 {
		panic("no return value specified for StoreList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(v10.TypeMeta, *list.TimestampedResourceList) error); ok {
		r0 = returnFunc(typeMeta, timestampedResourceList)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComplianceStore_StoreList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreList'
type MockComplianceStore_StoreList_Call struct {
	*mock.Call
}

// StoreList is a helper method to define mock.On call
//   - typeMeta v10.TypeMeta
//   - timestampedResourceList *list.TimestampedResourceList
func (_e *MockComplianceStore_Expecter) StoreList(typeMeta interface{}, timestampedResourceList interface{}) *MockComplianceStore_StoreList_Call {
	return &MockComplianceStore_StoreList_Call{Call: _e.mock.On("StoreList", typeMeta, timestampedResourceList)}
}

func (_c *MockComplianceStore_StoreList_Call) Run(run func(typeMeta v10.TypeMeta, timestampedResourceList *list.TimestampedResourceList)) *MockComplianceStore_StoreList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v10.TypeMeta
		if args[0] != nil {
			arg0 = args[0].(v10.TypeMeta)
		}
		var arg1 *list.TimestampedResourceList
		if args[1] != nil {
			arg1 = args[1].(*list.TimestampedResourceList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplianceStore_StoreList_Call) Return(err error) *MockComplianceStore_StoreList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComplianceStore_StoreList_Call) RunAndReturn(run func(typeMeta v10.TypeMeta, timestampedResourceList *list.TimestampedResourceList) error) *MockComplianceStore_StoreList_Call {
	_c.Call.Return(run)
	return _c
}
