# Copyright (c) 2021-2025 Tigera, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG THIRD_PARTY_REGISTRY
ARG THIRD_PARTY_RELEASE_BRANCH
ARG WINDOWS_VERSION

FROM ${THIRD_PARTY_REGISTRY}/fluentd-base:v1.19.2-${THIRD_PARTY_RELEASE_BRANCH}-windows-${WINDOWS_VERSION}

USER ContainerAdministrator

# The ROOT_DIR is set for Windows only.
ENV ROOT_DIR=C:

# On Windows, the destination format for COPY must use forward slashes.
COPY elastic_mapping_flows.template /fluentd/etc/elastic_mapping_flows.template
COPY elastic_mapping_dns.template /fluentd/etc/elastic_mapping_dns.template
COPY elastic_mapping_audits.template /fluentd/etc/elastic_mapping_audits.template
COPY elastic_mapping_bgp.template /fluentd/etc/elastic_mapping_bgp.template
COPY elastic_mapping_waf.template /fluentd/etc/elastic_mapping_waf.template
COPY elastic_mapping_l7.template /fluentd/etc/elastic_mapping_l7.template
COPY elastic_mapping_runtime.template /fluentd/etc/elastic_mapping_runtime.template

ENV FLOW_LOG_FILE=${ROOT_DIR}/TigeraCalico/flowlogs/flows.log
ENV POS_DIR=${ROOT_DIR}/TigeraCalico/flowlogs

# Use Windows-specific sources and transforms config - we only support flowlogs for now.
COPY fluent_sources.conf.windows /fluentd/etc/fluent_sources.conf
COPY fluent_transforms.conf.windows /fluentd/etc/fluent_transforms.conf

# Disable unsupported logs.
ENV DISABLE_ES_DNS_LOG=true
ENV DISABLE_ES_L7_LOG=true
ENV DISABLE_ES_BGP_LOG=true
ENV DISABLE_ES_RUNTIME_LOG=true

COPY output_match/ /fluentd/etc/output_match/
COPY outputs/ /fluentd/etc/outputs/
COPY inputs/ /fluentd/etc/inputs/
COPY filters/ /fluentd/etc/filters/

# Compliance reports logs needs a regex pattern because there will be
# multiple logs (one per report type), e.g. compliance.network-access.reports.log
ENV COMPLIANCE_LOG_FILE=${ROOT_DIR}/var/log/calico/compliance/compliance.*.reports.log
ENV DNS_LOG_FILE=${ROOT_DIR}/var/log/calico/dnslogs/dns.log
ENV BIRD_LOG_FILE=${ROOT_DIR}/var/log/calico/bird/current
ENV BIRD6_LOG_FILE=${ROOT_DIR}/var/log/calico/bird6/current
ENV IDS_EVENT_LOG_FILE=${ROOT_DIR}/var/log/calico/ids/events.log
ENV WAF_LOG_FILE=${ROOT_DIR}/var/log/calico/waf/waf.log
ENV L7_LOG_FILE=${ROOT_DIR}/var/log/calico/l7logs/l7.log
ENV EE_AUDIT_LOG_FILE=${ROOT_DIR}/var/log/calico/audit/tsee-audit.log
ENV RUNTIME_LOG_FILE=${ROOT_DIR}/var/log/calico/runtime-security/report.log
ENV POLICY_ACTIVITY_LOG_FILE=/var/log/calico/policy/policy_activity.log

# TLS Settings
ENV TLS_KEY_PATH=${ROOT_DIR}/tls/tls.key
ENV TLS_CRT_PATH=${ROOT_DIR}/tls/tls.crt
ENV CA_CRT_PATH=${ROOT_DIR}/etc/pki/tls/certs/tigera-ca-bundle.crt

ENV ELASTIC_HOST=elasticsearch
ENV ELASTIC_PORT=9200
ENV ELASTIC_FLUSH_INTERVAL=5s

ENV KUBE_AUDIT_LOG=${ROOT_DIR}/var/log/calico/audit/kube-audit.log
ENV KUBE_AUDIT_POS=${POS_DIR}/kube-audit.log.pos

ENV ELASTIC_INDEX_SUFFIX=cluster

ENV S3_FLUSH_INTERVAL=5s
ENV S3_STORAGE=false

ENV ELASTIC_FLOWS_INDEX_SHARDS=1
ENV ELASTIC_FLOWS_INDEX_REPLICAS=0
ENV ELASTIC_DNS_INDEX_SHARDS=1
ENV ELASTIC_DNS_INDEX_REPLICAS=0
ENV ELASTIC_AUDIT_INDEX_REPLICAS=0
ENV ELASTIC_L7_INDEX_SHARDS=1
ENV ELASTIC_L7_INDEX_REPLICAS=0
ENV ELASTIC_WAF_INDEX_SHARDS=1
ENV ELASTIC_WAF_INDEX_REPLICAS=0
ENV ELASTIC_TEMPLATE_OVERWRITE=true
ENV ELASTIC_BGP_INDEX_SHARDS=1
ENV ELASTIC_BGP_INDEX_REPLICAS=0
ENV ELASTIC_RUNTIME_INDEX_SHARDS=1
ENV ELASTIC_RUNTIME_INDEX_REPLICAS=0
ENV ELASTIC_POLICY_ACTIVITY_INDEX_REPLICAS=0
ENV ELASTIC_POLICY_ACTIVITY_INDEX_SHARDS=1

ENV SYSLOG_PACKET_SIZE=1024

# LINSEED DEFAULT PARAMS
ENV LINSEED_ENABLED=false
ENV LINSEED_ENDPOINT=ENDPOINT
ENV LINSEED_CA_PATH=${ROOT_DIR}/etc/flu/ca.pem
ENV LINSEED_CERT_PATH=${ROOT_DIR}/etc/flu/crt.pem
ENV LINSEED_KEY_PATH=${ROOT_DIR}/etc/flu/key.pem
ENV LINSEED_FLUSH_INTERVAL=5s
ENV LINSEED_TOKEN="${ROOT_DIR}/var/run/secrets/kubernetes.io/serviceaccount/token"

COPY readiness.sh /bin/readiness.sh
COPY liveness.sh /bin/liveness.sh
COPY syslog-environment.sh /bin/syslog-environment.sh
COPY syslog-config.sh /bin/syslog-config.sh
COPY splunk-environment.sh /bin/splunk-environment.sh
COPY splunk-config.sh /bin/splunk-config.sh
COPY ee_entrypoint.sh /bin/ee_entrypoint.sh
COPY eks/bin/eks-log-forwarder-startup.exe /bin/eks-log-forwarder-startup.exe

EXPOSE 24284

ENTRYPOINT []
# Must use the "exec" form of CMD to work for both docker and containerd
# https://github.com/containerd/containerd/issues/5067
CMD ["C:/ruby34/msys64/usr/bin/bash.exe", "-lc", "C:/bin/ee_entrypoint.sh C:/ruby34/bin/fluentd -c C:/fluentd/etc/fluent.conf -p C:/fluentd/plugins"]
