##
# Copyright (c) 2025 Tigera, Inc. All rights reserved.
##

ARG CALICO_BASE=calico/base:latest

FROM scratch AS source

ARG TARGETARCH

COPY bin/gateway-l7-collector-${TARGETARCH} /usr/bin/gateway-l7-collector

FROM ${CALICO_BASE}

COPY --from=source / /

ENTRYPOINT ["/usr/bin/gateway-l7-collector"]
