kind: ConfigMap
apiVersion: v1
metadata:
  name: fw-config
  namespace: kube-system
data:
  etcd_endpoints: "http://10.96.232.136:6666"
  fw_hostname: "54.245.165.191"
  fw_devicegroup: "test-dg"

---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: fw-secret-config
  namespace: kube-system
data:
  fw_username: YXBpdXNlcg==
  fw_password: aENiOFZ2N21DM3VtNHlRdQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-integ
  namespace: kube-system
  labels:
    k8s-app: firewall-integration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: firewall-integration-controller
  template:
    metadata:
      labels:
        k8s-app: firewall-integration-controller
    spec:
      imagePullSecrets:
        - name: cnx-pull-secret
      containers:
        - name: fw-integ
          image: gcr.io/unique-caldron-775/cnx/tigera/firewall-integration:latest
          env:
            # Panorama info.
            - name: FW_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: fw-config
                  key: fw_hostname
            - name: FW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fw-secret-config
                  key: fw_username
            - name: FW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fw-secret-config
                  key: fw_password
            - name: FW_DEVGROUP
              value: test-dg
            # TSEE info.
            - name: TSEE_TIER_PREFIX
              value: fw
            - name: TSEE_NETWORK_PREFIX
              value: panw
            - name: TSEE_TIER_ORDER
              value: "101"
            # etcd info.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: fw-config
                  key: etcd_endpoints
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
