action: init
kind: NetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: egress-to-any
  namespace: "{{.Namespace}}"
spec:
  selector: egress-to-any == 'yes'
  egress:
    - action: Allow
      destination:
        selector: "all()"
  types:
    - Egress
