apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: network-operators
  name: calico-node-monitor
spec:
  endpoints:
    - honorLabels: true
      interval: 5s
      port: calico-metrics-port
      scheme: https
      scrapeTimeout: 5s
      tlsConfig:
        caFile: /etc/pki/tigera/ca.crt
        certFile: /calico-node-prometheus-client-tls/tls.crt
        keyFile: /calico-node-prometheus-client-tls/tls.key
        serverName: calico-node-metrics
    - honorLabels: true
      interval: 5s
      port: calico-bgp-metrics-port
      scheme: https
      scrapeTimeout: 5s
      tlsConfig:
        caFile: /etc/pki/tigera/ca.crt
        certFile: /calico-node-prometheus-client-tls/tls.crt
        keyFile: /calico-node-prometheus-client-tls/tls.key
        serverName: calico-node-metrics
  namespaceSelector:
    matchNames:
      - calico-system
  selector:
    matchLabels:
      k8s-app: calico-node
