AWSTemplateFormatVersion: 2010-09-09
Description: Per-cluster Tigera resources
# Creates:
# - Pod default Security Group
Parameters:
  VpcId:
    Description: The cluster's VPC
    Type: AWS::EC2::VPC::Id
  KubernetesHostDefaultSGId:
    Description: The security group of your Kubernetes worker nodes.
    Type: AWS::EC2::SecurityGroup::Id
  KubernetesControlPlaneSGId:
    Description: The security group of your Kubernetes master nodes.
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  # Create a security group to be used as the default for Kubernetes pods. All pods will be
  # automatically added to this security group.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  TigeraPodDefault:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Tigera pod default security group
      VpcId:
        Ref: VpcId

  # Create rules for the kubernetes pod SG which implement basic Kubernetes networking requirements.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html
  TigeraPodDefaultSGEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt:
          - TigeraPodDefault
          - GroupId
      Description: "Allow all egress"
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0
  TigeraPodDefaultSGIngressFromItself:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt:
          - TigeraPodDefault
          - GroupId
      Description: "Allow from other pods"
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId:
        Fn::GetAtt:
          - TigeraPodDefault
          - GroupId
  TigeraPodDefaultSGIngressFromK8sHost:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt:
          - TigeraPodDefault
          - GroupId
      Description: "Allow from Kubernetes worker nodes"
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId:
        Ref: KubernetesHostDefaultSGId
  TigeraPodDefaultSGIngressFromK8sControlPlane:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt:
          - TigeraPodDefault
          - GroupId
      Description: "Allow from Kubernetes control plane nodes"
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId:
        Ref: KubernetesControlPlaneSGId

# Output values.
Outputs:
  TigeraDefaultPodSG:
    Description: Default Security Group for pods
    Value: !GetAtt
      - TigeraPodDefault
      - GroupId
