# Copyright {{now | date "2006"}} Tigera Inc. All rights reserved.
include ../metadata.mk

PACKAGE_NAME    ?= github.com/projectcalico/calico/{{ lower .Name }}

#############################################
# Env vars related to packaging and releasing
#############################################
{{ snakecase .Name | upper }}_IMAGE	?={{ lower .Name }}
BUILD_IMAGES?=$({{ snakecase .Name | upper }}_IMAGE)

###############################################################################
# Include ../lib.Makefile
#   Additions to EXTRA_DOCKER_ARGS need to happen before the include since
#   that variable is evaluated when we declare DOCKER_RUN and siblings.
###############################################################################
include ../lib.Makefile

###############################################################################
# Env vars related to building
###############################################################################
SRC_FILES = $(shell find pkg cmd -name '*.go')

# We use -X to insert the version information into the placeholder variables
# in the version package.
LDFLAGS = -X $(PACKAGE_NAME)/pkg/config/BuildVersion=$(GIT_VERSION) \
              -X $(PACKAGE_NAME)/pkg/config/BuildDate=$(DATE) \
              -X $(PACKAGE_NAME)/pkg/config/GitDescription=$(GIT_DESCRIPTION) \
              -X $(PACKAGE_NAME)/pkg/config/GitRevision=$(GIT_COMMIT)

###############################################################################
# BUILD BINARY
###############################################################################
# This section builds the output binaries.
build: bin/{{ lower .Name }}-$(ARCH)

.PHONY: bin/{{ lower .Name }}-$(ARCH)
bin/{{ lower .Name }}-$(ARCH): $(SRC_FILES)
	$(call build_binary, cmd/$*/*.go, $@)

###############################################################################
# BUILD IMAGE
###############################################################################
{{ snakecase .Name | upper }}_CONTAINER_CREATED=.{{ lower .Name }}.created-$(ARCH)

# Build the docker image.
.PHONY: $(BUILD_IMAGES)

# by default, build the image for the target architecture
.PHONY: image-all
image-all: $(addprefix sub-image-,$(VALIDARCHES))
sub-image-%:
	$(MAKE) image ARCH=$*

.PHONY: image
image: $({{ snakecase .Name | upper }}_IMAGE)

$({{ snakecase .Name | upper }}_IMAGE): $({{ snakecase .Name | upper }}_CONTAINER_CREATED)
$({{ snakecase .Name | upper }}_CONTAINER_CREATED): docker-image/Dockerfile.$(ARCH) bin/{{ lower .Name }}-$(ARCH)
	$(DOCKER_BUILD) -t $({{ snakecase .Name | upper }}_IMAGE):latest-$(ARCH) -f docker-image/Dockerfile.$(ARCH) .
	$(MAKE) retag-build-images-with-registries VALIDARCHES=$(ARCH) IMAGETAG=latest
	touch $@

.PHONY: clean
clean:
	rm -rf bin \
		report/*.xml \
		config/
	find . -name '*.coverprofile' -type f -delete
	rm -f $({{ snakecase .Name | upper }}_CREATED)
	-docker image rm -f $$(docker images $({{ snakecase .Name | upper }}_IMAGE) -a -q)

###############################################################################
# Testing
###############################################################################
#MOCKERY_FILE_PATHS= \
#	pkg/ \

#############################################
# Run unit level tests
#############################################
# Comma separated paths to packages containing fv tests

.PHONY: ut
## Run only Unit Tests.
ut: ut-fast

ut-fast:
	# We run the tests n times to try and weed out test flakes.
	$(DOCKER_GO_BUILD) sh -c '$(GIT_CONFIG_SSH) go test ./... -cover -count 1'


st:
	@echo "No STs available"

###############################################################################
# FV Tests
###############################################################################

# Run {{ camelcase .Name }} as a local Docker container.
run-image: stop-image
	docker run --detach \
		--net=host \
		--name=tigera-$({{ snakecase .Name | upper }}_IMAGE) \
		tigera/$({{ snakecase .Name | upper }}_IMAGE):latest
	# Wait until {{ camelcase .Name }} is accepting requests on its readiness port.
	while ! curl -k http://localhost:8080/readiness; do echo "Waiting for {{ camelcase .Name }} to come up..."; sleep 2; done

stop-image:
	-docker rm -f $(shell docker ps -aq --filter "name=tigera-$({{ snakecase .Name | upper }})")

## Run the FVs
fv:
	@echo "No FVs available at the moment"

###############################################################################
# CI/CD
###############################################################################
.PHONY: ci cd

## run CI cycle - build, test, etc.
## Run UTs and only if they pass build image and continue along.
## Building the image is required for fvs.
ci: clean static-checks build test

## Deploys images to registry
cd: image-all cd-common
