// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// Refresh provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) Refresh() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockTokenProvider_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
func (_e *MockTokenProvider_Expecter) Refresh() *MockTokenProvider_Refresh_Call {
	return &MockTokenProvider_Refresh_Call{Call: _e.mock.On("Refresh")}
}

func (_c *MockTokenProvider_Refresh_Call) Run(run func()) *MockTokenProvider_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenProvider_Refresh_Call) Return(s string, err error) *MockTokenProvider_Refresh_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_Refresh_Call) RunAndReturn(run func() (string, error)) *MockTokenProvider_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) Token() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockTokenProvider_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockTokenProvider_Expecter) Token() *MockTokenProvider_Token_Call {
	return &MockTokenProvider_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockTokenProvider_Token_Call) Run(run func()) *MockTokenProvider_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenProvider_Token_Call) Return(s string, err error) *MockTokenProvider_Token_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenProvider_Token_Call) RunAndReturn(run func() (string, error)) *MockTokenProvider_Token_Call {
	_c.Call.Return(run)
	return _c
}
