# Source: tigera-prometheus-operator/templates/04-serviceaccount-prometheus-operator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-prometheus-operator
  namespace: tigera-prometheus
