// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package elastic

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClusterContextClientFactory creates a new instance of MockClusterContextClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterContextClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterContextClientFactory {
	mock := &MockClusterContextClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClusterContextClientFactory is an autogenerated mock type for the ClusterContextClientFactory type
type MockClusterContextClientFactory struct {
	mock.Mock
}

type MockClusterContextClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterContextClientFactory) EXPECT() *MockClusterContextClientFactory_Expecter {
	return &MockClusterContextClientFactory_Expecter{mock: &_m.Mock}
}

// ClientForCluster provides a mock function for the type MockClusterContextClientFactory
func (_mock *MockClusterContextClientFactory) ClientForCluster(s string) (Client, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ClientForCluster")
	}

	var r0 Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Client, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Client); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClusterContextClientFactory_ClientForCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientForCluster'
type MockClusterContextClientFactory_ClientForCluster_Call struct {
	*mock.Call
}

// ClientForCluster is a helper method to define mock.On call
//   - s string
func (_e *MockClusterContextClientFactory_Expecter) ClientForCluster(s interface{}) *MockClusterContextClientFactory_ClientForCluster_Call {
	return &MockClusterContextClientFactory_ClientForCluster_Call{Call: _e.mock.On("ClientForCluster", s)}
}

func (_c *MockClusterContextClientFactory_ClientForCluster_Call) Run(run func(s string)) *MockClusterContextClientFactory_ClientForCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClusterContextClientFactory_ClientForCluster_Call) Return(client Client, err error) *MockClusterContextClientFactory_ClientForCluster_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClusterContextClientFactory_ClientForCluster_Call) RunAndReturn(run func(s string) (Client, error)) *MockClusterContextClientFactory_ClientForCluster_Call {
	_c.Call.Return(run)
	return _c
}
