// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package elastic

import (
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockFlowFilter creates a new instance of MockFlowFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowFilter {
	mock := &MockFlowFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlowFilter is an autogenerated mock type for the FlowFilter type
type MockFlowFilter struct {
	mock.Mock
}

type MockFlowFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlowFilter) EXPECT() *MockFlowFilter_Expecter {
	return &MockFlowFilter_Expecter{mock: &_m.Mock}
}

// IncludeFlow provides a mock function for the type MockFlowFilter
func (_mock *MockFlowFilter) IncludeFlow(flow *CompositeAggregationBucket) (bool, error) {
	ret := _mock.Called(flow)

	if len(ret) == 0 {
		panic("no return value specified for IncludeFlow")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*CompositeAggregationBucket) (bool, error)); ok {
		return returnFunc(flow)
	}
	if returnFunc, ok := ret.Get(0).(func(*CompositeAggregationBucket) bool); ok {
		r0 = returnFunc(flow)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*CompositeAggregationBucket) error); ok {
		r1 = returnFunc(flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowFilter_IncludeFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncludeFlow'
type MockFlowFilter_IncludeFlow_Call struct {
	*mock.Call
}

// IncludeFlow is a helper method to define mock.On call
//   - flow *CompositeAggregationBucket
func (_e *MockFlowFilter_Expecter) IncludeFlow(flow interface{}) *MockFlowFilter_IncludeFlow_Call {
	return &MockFlowFilter_IncludeFlow_Call{Call: _e.mock.On("IncludeFlow", flow)}
}

func (_c *MockFlowFilter_IncludeFlow_Call) Run(run func(flow *CompositeAggregationBucket)) *MockFlowFilter_IncludeFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *CompositeAggregationBucket
		if args[0] != nil {
			arg0 = args[0].(*CompositeAggregationBucket)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowFilter_IncludeFlow_Call) Return(include bool, err error) *MockFlowFilter_IncludeFlow_Call {
	_c.Call.Return(include, err)
	return _c
}

func (_c *MockFlowFilter_IncludeFlow_Call) RunAndReturn(run func(flow *CompositeAggregationBucket) (bool, error)) *MockFlowFilter_IncludeFlow_Call {
	_c.Call.Return(run)
	return _c
}

// IncludeLinseedFlow provides a mock function for the type MockFlowFilter
func (_mock *MockFlowFilter) IncludeLinseedFlow(flow *v1.L3Flow) (bool, error) {
	ret := _mock.Called(flow)

	if len(ret) == 0 {
		panic("no return value specified for IncludeLinseedFlow")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*v1.L3Flow) (bool, error)); ok {
		return returnFunc(flow)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1.L3Flow) bool); ok {
		r0 = returnFunc(flow)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*v1.L3Flow) error); ok {
		r1 = returnFunc(flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowFilter_IncludeLinseedFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncludeLinseedFlow'
type MockFlowFilter_IncludeLinseedFlow_Call struct {
	*mock.Call
}

// IncludeLinseedFlow is a helper method to define mock.On call
//   - flow *v1.L3Flow
func (_e *MockFlowFilter_Expecter) IncludeLinseedFlow(flow interface{}) *MockFlowFilter_IncludeLinseedFlow_Call {
	return &MockFlowFilter_IncludeLinseedFlow_Call{Call: _e.mock.On("IncludeLinseedFlow", flow)}
}

func (_c *MockFlowFilter_IncludeLinseedFlow_Call) Run(run func(flow *v1.L3Flow)) *MockFlowFilter_IncludeLinseedFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.L3Flow
		if args[0] != nil {
			arg0 = args[0].(*v1.L3Flow)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowFilter_IncludeLinseedFlow_Call) Return(include bool, err error) *MockFlowFilter_IncludeLinseedFlow_Call {
	_c.Call.Return(include, err)
	return _c
}

func (_c *MockFlowFilter_IncludeLinseedFlow_Call) RunAndReturn(run func(flow *v1.L3Flow) (bool, error)) *MockFlowFilter_IncludeLinseedFlow_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyFlow provides a mock function for the type MockFlowFilter
func (_mock *MockFlowFilter) ModifyFlow(flow *CompositeAggregationBucket) error {
	ret := _mock.Called(flow)

	if len(ret) == 0 {
		panic("no return value specified for ModifyFlow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*CompositeAggregationBucket) error); ok {
		r0 = returnFunc(flow)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFlowFilter_ModifyFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyFlow'
type MockFlowFilter_ModifyFlow_Call struct {
	*mock.Call
}

// ModifyFlow is a helper method to define mock.On call
//   - flow *CompositeAggregationBucket
func (_e *MockFlowFilter_Expecter) ModifyFlow(flow interface{}) *MockFlowFilter_ModifyFlow_Call {
	return &MockFlowFilter_ModifyFlow_Call{Call: _e.mock.On("ModifyFlow", flow)}
}

func (_c *MockFlowFilter_ModifyFlow_Call) Run(run func(flow *CompositeAggregationBucket)) *MockFlowFilter_ModifyFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *CompositeAggregationBucket
		if args[0] != nil {
			arg0 = args[0].(*CompositeAggregationBucket)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowFilter_ModifyFlow_Call) Return(err error) *MockFlowFilter_ModifyFlow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFlowFilter_ModifyFlow_Call) RunAndReturn(run func(flow *CompositeAggregationBucket) error) *MockFlowFilter_ModifyFlow_Call {
	_c.Call.Return(run)
	return _c
}
