// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package elastic

import (
	"context"
	"time"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	"github.com/projectcalico/calico/lma/pkg/api"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Backend provides a mock function for the type MockClient
func (_mock *MockClient) Backend() *elastic.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Backend")
	}

	var r0 *elastic.Client
	if returnFunc, ok := ret.Get(0).(func() *elastic.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Client)
		}
	}
	return r0
}

// MockClient_Backend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backend'
type MockClient_Backend_Call struct {
	*mock.Call
}

// Backend is a helper method to define mock.On call
func (_e *MockClient_Expecter) Backend() *MockClient_Backend_Call {
	return &MockClient_Backend_Call{Call: _e.mock.On("Backend")}
}

func (_c *MockClient_Backend_Call) Run(run func()) *MockClient_Backend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Backend_Call) Return(client *elastic.Client) *MockClient_Backend_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClient_Backend_Call) RunAndReturn(run func() *elastic.Client) *MockClient_Backend_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterAlias provides a mock function for the type MockClient
func (_mock *MockClient) ClusterAlias(s string) string {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ClusterAlias")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_ClusterAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterAlias'
type MockClient_ClusterAlias_Call struct {
	*mock.Call
}

// ClusterAlias is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) ClusterAlias(s interface{}) *MockClient_ClusterAlias_Call {
	return &MockClient_ClusterAlias_Call{Call: _e.mock.On("ClusterAlias", s)}
}

func (_c *MockClient_ClusterAlias_Call) Run(run func(s string)) *MockClient_ClusterAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ClusterAlias_Call) Return(s1 string) *MockClient_ClusterAlias_Call {
	_c.Call.Return(s1)
	return _c
}

func (_c *MockClient_ClusterAlias_Call) RunAndReturn(run func(s string) string) *MockClient_ClusterAlias_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterIndex provides a mock function for the type MockClient
func (_mock *MockClient) ClusterIndex(s string, s1 string) string {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterIndex")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_ClusterIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterIndex'
type MockClient_ClusterIndex_Call struct {
	*mock.Call
}

// ClusterIndex is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockClient_Expecter) ClusterIndex(s interface{}, s1 interface{}) *MockClient_ClusterIndex_Call {
	return &MockClient_ClusterIndex_Call{Call: _e.mock.On("ClusterIndex", s, s1)}
}

func (_c *MockClient_ClusterIndex_Call) Run(run func(s string, s1 string)) *MockClient_ClusterIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ClusterIndex_Call) Return(s2 string) *MockClient_ClusterIndex_Call {
	_c.Call.Return(s2)
	return _c
}

func (_c *MockClient_ClusterIndex_Call) RunAndReturn(run func(s string, s1 string) string) *MockClient_ClusterIndex_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type MockClient
func (_mock *MockClient) Do(ctx context.Context, s *elastic.SearchService) (*elastic.SearchResult, error) {
	ret := _mock.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *elastic.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elastic.SearchService) (*elastic.SearchResult, error)); ok {
		return returnFunc(ctx, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *elastic.SearchService) *elastic.SearchResult); ok {
		r0 = returnFunc(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *elastic.SearchService) error); ok {
		r1 = returnFunc(ctx, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockClient_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - s *elastic.SearchService
func (_e *MockClient_Expecter) Do(ctx interface{}, s interface{}) *MockClient_Do_Call {
	return &MockClient_Do_Call{Call: _e.mock.On("Do", ctx, s)}
}

func (_c *MockClient_Do_Call) Run(run func(ctx context.Context, s *elastic.SearchService)) *MockClient_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *elastic.SearchService
		if args[1] != nil {
			arg1 = args[1].(*elastic.SearchService)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Do_Call) Return(searchResult *elastic.SearchResult, err error) *MockClient_Do_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockClient_Do_Call) RunAndReturn(run func(ctx context.Context, s *elastic.SearchService) (*elastic.SearchResult, error)) *MockClient_Do_Call {
	_c.Call.Return(run)
	return _c
}

// IndexTemplateName provides a mock function for the type MockClient
func (_mock *MockClient) IndexTemplateName(index string) string {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for IndexTemplateName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(index)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_IndexTemplateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexTemplateName'
type MockClient_IndexTemplateName_Call struct {
	*mock.Call
}

// IndexTemplateName is a helper method to define mock.On call
//   - index string
func (_e *MockClient_Expecter) IndexTemplateName(index interface{}) *MockClient_IndexTemplateName_Call {
	return &MockClient_IndexTemplateName_Call{Call: _e.mock.On("IndexTemplateName", index)}
}

func (_c *MockClient_IndexTemplateName_Call) Run(run func(index string)) *MockClient_IndexTemplateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_IndexTemplateName_Call) Return(s string) *MockClient_IndexTemplateName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_IndexTemplateName_Call) RunAndReturn(run func(index string) string) *MockClient_IndexTemplateName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchCompositeAggregations provides a mock function for the type MockClient
func (_mock *MockClient) SearchCompositeAggregations(context1 context.Context, compositeAggregationQuery *CompositeAggregationQuery, compositeAggregationKey CompositeAggregationKey) (<-chan *CompositeAggregationBucket, <-chan error) {
	ret := _mock.Called(context1, compositeAggregationQuery, compositeAggregationKey)

	if len(ret) == 0 {
		panic("no return value specified for SearchCompositeAggregations")
	}

	var r0 <-chan *CompositeAggregationBucket
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CompositeAggregationQuery, CompositeAggregationKey) (<-chan *CompositeAggregationBucket, <-chan error)); ok {
		return returnFunc(context1, compositeAggregationQuery, compositeAggregationKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CompositeAggregationQuery, CompositeAggregationKey) <-chan *CompositeAggregationBucket); ok {
		r0 = returnFunc(context1, compositeAggregationQuery, compositeAggregationKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *CompositeAggregationBucket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CompositeAggregationQuery, CompositeAggregationKey) <-chan error); ok {
		r1 = returnFunc(context1, compositeAggregationQuery, compositeAggregationKey)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// MockClient_SearchCompositeAggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchCompositeAggregations'
type MockClient_SearchCompositeAggregations_Call struct {
	*mock.Call
}

// SearchCompositeAggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - compositeAggregationQuery *CompositeAggregationQuery
//   - compositeAggregationKey CompositeAggregationKey
func (_e *MockClient_Expecter) SearchCompositeAggregations(context1 interface{}, compositeAggregationQuery interface{}, compositeAggregationKey interface{}) *MockClient_SearchCompositeAggregations_Call {
	return &MockClient_SearchCompositeAggregations_Call{Call: _e.mock.On("SearchCompositeAggregations", context1, compositeAggregationQuery, compositeAggregationKey)}
}

func (_c *MockClient_SearchCompositeAggregations_Call) Run(run func(context1 context.Context, compositeAggregationQuery *CompositeAggregationQuery, compositeAggregationKey CompositeAggregationKey)) *MockClient_SearchCompositeAggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CompositeAggregationQuery
		if args[1] != nil {
			arg1 = args[1].(*CompositeAggregationQuery)
		}
		var arg2 CompositeAggregationKey
		if args[2] != nil {
			arg2 = args[2].(CompositeAggregationKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_SearchCompositeAggregations_Call) Return(compositeAggregationBucketCh <-chan *CompositeAggregationBucket, errCh <-chan error) *MockClient_SearchCompositeAggregations_Call {
	_c.Call.Return(compositeAggregationBucketCh, errCh)
	return _c
}

func (_c *MockClient_SearchCompositeAggregations_Call) RunAndReturn(run func(context1 context.Context, compositeAggregationQuery *CompositeAggregationQuery, compositeAggregationKey CompositeAggregationKey) (<-chan *CompositeAggregationBucket, <-chan error)) *MockClient_SearchCompositeAggregations_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDNSLogs provides a mock function for the type MockClient
func (_mock *MockClient) SearchDNSLogs(ctx context.Context, filter *api.DNSLogsSelection, start *time.Time, end *time.Time) <-chan *api.DNSResult {
	ret := _mock.Called(ctx, filter, start, end)

	if len(ret) == 0 {
		panic("no return value specified for SearchDNSLogs")
	}

	var r0 <-chan *api.DNSResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.DNSLogsSelection, *time.Time, *time.Time) <-chan *api.DNSResult); ok {
		r0 = returnFunc(ctx, filter, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *api.DNSResult)
		}
	}
	return r0
}

// MockClient_SearchDNSLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDNSLogs'
type MockClient_SearchDNSLogs_Call struct {
	*mock.Call
}

// SearchDNSLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *api.DNSLogsSelection
//   - start *time.Time
//   - end *time.Time
func (_e *MockClient_Expecter) SearchDNSLogs(ctx interface{}, filter interface{}, start interface{}, end interface{}) *MockClient_SearchDNSLogs_Call {
	return &MockClient_SearchDNSLogs_Call{Call: _e.mock.On("SearchDNSLogs", ctx, filter, start, end)}
}

func (_c *MockClient_SearchDNSLogs_Call) Run(run func(ctx context.Context, filter *api.DNSLogsSelection, start *time.Time, end *time.Time)) *MockClient_SearchDNSLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *api.DNSLogsSelection
		if args[1] != nil {
			arg1 = args[1].(*api.DNSLogsSelection)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_SearchDNSLogs_Call) Return(dNSResultCh <-chan *api.DNSResult) *MockClient_SearchDNSLogs_Call {
	_c.Call.Return(dNSResultCh)
	return _c
}

func (_c *MockClient_SearchDNSLogs_Call) RunAndReturn(run func(ctx context.Context, filter *api.DNSLogsSelection, start *time.Time, end *time.Time) <-chan *api.DNSResult) *MockClient_SearchDNSLogs_Call {
	_c.Call.Return(run)
	return _c
}
