// Code generated by mockery v2.53.4. DO NOT EDIT.

package elastic

import mock "github.com/stretchr/testify/mock"

// MockClusterContextClientFactory is an autogenerated mock type for the ClusterContextClientFactory type
type MockClusterContextClientFactory struct {
	mock.Mock
}

// ClientForCluster provides a mock function with given fields: _a0
func (_m *MockClusterContextClientFactory) ClientForCluster(_a0 string) (Client, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ClientForCluster")
	}

	var r0 Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Client, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) Client); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClusterContextClientFactory creates a new instance of MockClusterContextClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterContextClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterContextClientFactory {
	mock := &MockClusterContextClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
