// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exec

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExec creates a new instance of MockExec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExec {
	mock := &MockExec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExec is an autogenerated mock type for the Exec type
type MockExec struct {
	mock.Mock
}

type MockExec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExec) EXPECT() *MockExec_Expecter {
	return &MockExec_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockExec
func (_mock *MockExec) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExec_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockExec_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockExec_Expecter) Start() *MockExec_Start_Call {
	return &MockExec_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockExec_Start_Call) Run(run func()) *MockExec_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExec_Start_Call) Return(err error) *MockExec_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExec_Start_Call) RunAndReturn(run func() error) *MockExec_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockExec
func (_mock *MockExec) Stop() {
	_mock.Called()
	return
}

// MockExec_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockExec_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockExec_Expecter) Stop() *MockExec_Stop_Call {
	return &MockExec_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockExec_Stop_Call) Run(run func()) *MockExec_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExec_Stop_Call) Return() *MockExec_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExec_Stop_Call) RunAndReturn(run func()) *MockExec_Stop_Call {
	_c.Run(run)
	return _c
}

// Wait provides a mock function for the type MockExec
func (_mock *MockExec) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExec_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockExec_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockExec_Expecter) Wait() *MockExec_Wait_Call {
	return &MockExec_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockExec_Wait_Call) Run(run func()) *MockExec_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExec_Wait_Call) Return(err error) *MockExec_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExec_Wait_Call) RunAndReturn(run func() error) *MockExec_Wait_Call {
	_c.Call.Return(run)
	return _c
}
