action: update
kind: NetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: ingress-from-any
  namespace: "{{.Namespace}}"
  labels:
    churner: "whoohooo"
spec:
  selector: ingress-from-any == 'yes'
  ingress:
    - action: Allow
      source:
        selector: "all()"
  types:
    - Ingress
