// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package capture

import (
	mock "github.com/stretchr/testify/mock"
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
)

// NewMockK8sCommands creates a new instance of MockK8sCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK8sCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK8sCommands {
	mock := &MockK8sCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK8sCommands is an autogenerated mock type for the K8sCommands type
type MockK8sCommands struct {
	mock.Mock
}

type MockK8sCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK8sCommands) EXPECT() *MockK8sCommands_Expecter {
	return &MockK8sCommands_Expecter{mock: &_m.Mock}
}

// GetEntryPod provides a mock function for the type MockK8sCommands
func (_mock *MockK8sCommands) GetEntryPod(clusterID string, node string) (*EntryPod, error) {
	ret := _mock.Called(clusterID, node)

	if len(ret) == 0 {
		panic("no return value specified for GetEntryPod")
	}

	var r0 *EntryPod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*EntryPod, error)); ok {
		return returnFunc(clusterID, node)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *EntryPod); ok {
		r0 = returnFunc(clusterID, node)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EntryPod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(clusterID, node)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK8sCommands_GetEntryPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntryPod'
type MockK8sCommands_GetEntryPod_Call struct {
	*mock.Call
}

// GetEntryPod is a helper method to define mock.On call
//   - clusterID string
//   - node string
func (_e *MockK8sCommands_Expecter) GetEntryPod(clusterID interface{}, node interface{}) *MockK8sCommands_GetEntryPod_Call {
	return &MockK8sCommands_GetEntryPod_Call{Call: _e.mock.On("GetEntryPod", clusterID, node)}
}

func (_c *MockK8sCommands_GetEntryPod_Call) Run(run func(clusterID string, node string)) *MockK8sCommands_GetEntryPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockK8sCommands_GetEntryPod_Call) Return(entryPod *EntryPod, err error) *MockK8sCommands_GetEntryPod_Call {
	_c.Call.Return(entryPod, err)
	return _c
}

func (_c *MockK8sCommands_GetEntryPod_Call) RunAndReturn(run func(clusterID string, node string) (*EntryPod, error)) *MockK8sCommands_GetEntryPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPacketCapture provides a mock function for the type MockK8sCommands
func (_mock *MockK8sCommands) GetPacketCapture(clusterID string, name string, namespace string) (*v3.PacketCapture, error) {
	ret := _mock.Called(clusterID, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetPacketCapture")
	}

	var r0 *v3.PacketCapture
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*v3.PacketCapture, error)); ok {
		return returnFunc(clusterID, name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *v3.PacketCapture); ok {
		r0 = returnFunc(clusterID, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.PacketCapture)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(clusterID, name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK8sCommands_GetPacketCapture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPacketCapture'
type MockK8sCommands_GetPacketCapture_Call struct {
	*mock.Call
}

// GetPacketCapture is a helper method to define mock.On call
//   - clusterID string
//   - name string
//   - namespace string
func (_e *MockK8sCommands_Expecter) GetPacketCapture(clusterID interface{}, name interface{}, namespace interface{}) *MockK8sCommands_GetPacketCapture_Call {
	return &MockK8sCommands_GetPacketCapture_Call{Call: _e.mock.On("GetPacketCapture", clusterID, name, namespace)}
}

func (_c *MockK8sCommands_GetPacketCapture_Call) Run(run func(clusterID string, name string, namespace string)) *MockK8sCommands_GetPacketCapture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK8sCommands_GetPacketCapture_Call) Return(packetCapture *v3.PacketCapture, err error) *MockK8sCommands_GetPacketCapture_Call {
	_c.Call.Return(packetCapture, err)
	return _c
}

func (_c *MockK8sCommands_GetPacketCapture_Call) RunAndReturn(run func(clusterID string, name string, namespace string) (*v3.PacketCapture, error)) *MockK8sCommands_GetPacketCapture_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePacketCaptureStatusWithNoFiles provides a mock function for the type MockK8sCommands
func (_mock *MockK8sCommands) UpdatePacketCaptureStatusWithNoFiles(clusterID string, name string, namespace string, nodes map[string]struct{}) error {
	ret := _mock.Called(clusterID, name, namespace, nodes)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePacketCaptureStatusWithNoFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, map[string]struct{}) error); ok {
		r0 = returnFunc(clusterID, name, namespace, nodes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePacketCaptureStatusWithNoFiles'
type MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call struct {
	*mock.Call
}

// UpdatePacketCaptureStatusWithNoFiles is a helper method to define mock.On call
//   - clusterID string
//   - name string
//   - namespace string
//   - nodes map[string]struct{}
func (_e *MockK8sCommands_Expecter) UpdatePacketCaptureStatusWithNoFiles(clusterID interface{}, name interface{}, namespace interface{}, nodes interface{}) *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call {
	return &MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call{Call: _e.mock.On("UpdatePacketCaptureStatusWithNoFiles", clusterID, name, namespace, nodes)}
}

func (_c *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call) Run(run func(clusterID string, name string, namespace string, nodes map[string]struct{})) *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]struct{}
		if args[3] != nil {
			arg3 = args[3].(map[string]struct{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call) Return(err error) *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call) RunAndReturn(run func(clusterID string, name string, namespace string, nodes map[string]struct{}) error) *MockK8sCommands_UpdatePacketCaptureStatusWithNoFiles_Call {
	_c.Call.Return(run)
	return _c
}
