// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package index

import (
	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
	"github.com/projectcalico/calico/linseed/pkg/backend/api"
	v10 "github.com/projectcalico/calico/lma/pkg/apis/v1"
)

// NewMockHelper creates a new instance of MockHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelper {
	mock := &MockHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelper is an autogenerated mock type for the Helper type
type MockHelper struct {
	mock.Mock
}

type MockHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelper) EXPECT() *MockHelper_Expecter {
	return &MockHelper_Expecter{mock: &_m.Mock}
}

// BaseQuery provides a mock function for the type MockHelper
func (_mock *MockHelper) BaseQuery(i api.ClusterInfo, logParams v1.Params) (*elastic.BoolQuery, error) {
	ret := _mock.Called(i, logParams)

	if len(ret) == 0 {
		panic("no return value specified for BaseQuery")
	}

	var r0 *elastic.BoolQuery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.ClusterInfo, v1.Params) (*elastic.BoolQuery, error)); ok {
		return returnFunc(i, logParams)
	}
	if returnFunc, ok := ret.Get(0).(func(api.ClusterInfo, v1.Params) *elastic.BoolQuery); ok {
		r0 = returnFunc(i, logParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.BoolQuery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(api.ClusterInfo, v1.Params) error); ok {
		r1 = returnFunc(i, logParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelper_BaseQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseQuery'
type MockHelper_BaseQuery_Call struct {
	*mock.Call
}

// BaseQuery is a helper method to define mock.On call
//   - i api.ClusterInfo
//   - logParams v1.Params
func (_e *MockHelper_Expecter) BaseQuery(i interface{}, logParams interface{}) *MockHelper_BaseQuery_Call {
	return &MockHelper_BaseQuery_Call{Call: _e.mock.On("BaseQuery", i, logParams)}
}

func (_c *MockHelper_BaseQuery_Call) Run(run func(i api.ClusterInfo, logParams v1.Params)) *MockHelper_BaseQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.ClusterInfo
		if args[0] != nil {
			arg0 = args[0].(api.ClusterInfo)
		}
		var arg1 v1.Params
		if args[1] != nil {
			arg1 = args[1].(v1.Params)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHelper_BaseQuery_Call) Return(boolQuery *elastic.BoolQuery, err error) *MockHelper_BaseQuery_Call {
	_c.Call.Return(boolQuery, err)
	return _c
}

func (_c *MockHelper_BaseQuery_Call) RunAndReturn(run func(i api.ClusterInfo, logParams v1.Params) (*elastic.BoolQuery, error)) *MockHelper_BaseQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeField provides a mock function for the type MockHelper
func (_mock *MockHelper) GetTimeField() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTimeField")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHelper_GetTimeField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeField'
type MockHelper_GetTimeField_Call struct {
	*mock.Call
}

// GetTimeField is a helper method to define mock.On call
func (_e *MockHelper_Expecter) GetTimeField() *MockHelper_GetTimeField_Call {
	return &MockHelper_GetTimeField_Call{Call: _e.mock.On("GetTimeField")}
}

func (_c *MockHelper_GetTimeField_Call) Run(run func()) *MockHelper_GetTimeField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHelper_GetTimeField_Call) Return(s string) *MockHelper_GetTimeField_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHelper_GetTimeField_Call) RunAndReturn(run func() string) *MockHelper_GetTimeField_Call {
	_c.Call.Return(run)
	return _c
}

// NewRBACQuery provides a mock function for the type MockHelper
func (_mock *MockHelper) NewRBACQuery(resources []v3.AuthorizedResourceVerbs) (elastic.Query, error) {
	ret := _mock.Called(resources)

	if len(ret) == 0 {
		panic("no return value specified for NewRBACQuery")
	}

	var r0 elastic.Query
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]v3.AuthorizedResourceVerbs) (elastic.Query, error)); ok {
		return returnFunc(resources)
	}
	if returnFunc, ok := ret.Get(0).(func([]v3.AuthorizedResourceVerbs) elastic.Query); ok {
		r0 = returnFunc(resources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elastic.Query)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]v3.AuthorizedResourceVerbs) error); ok {
		r1 = returnFunc(resources)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelper_NewRBACQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRBACQuery'
type MockHelper_NewRBACQuery_Call struct {
	*mock.Call
}

// NewRBACQuery is a helper method to define mock.On call
//   - resources []v3.AuthorizedResourceVerbs
func (_e *MockHelper_Expecter) NewRBACQuery(resources interface{}) *MockHelper_NewRBACQuery_Call {
	return &MockHelper_NewRBACQuery_Call{Call: _e.mock.On("NewRBACQuery", resources)}
}

func (_c *MockHelper_NewRBACQuery_Call) Run(run func(resources []v3.AuthorizedResourceVerbs)) *MockHelper_NewRBACQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []v3.AuthorizedResourceVerbs
		if args[0] != nil {
			arg0 = args[0].([]v3.AuthorizedResourceVerbs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelper_NewRBACQuery_Call) Return(query elastic.Query, err error) *MockHelper_NewRBACQuery_Call {
	_c.Call.Return(query, err)
	return _c
}

func (_c *MockHelper_NewRBACQuery_Call) RunAndReturn(run func(resources []v3.AuthorizedResourceVerbs) (elastic.Query, error)) *MockHelper_NewRBACQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewSelectorQuery provides a mock function for the type MockHelper
func (_mock *MockHelper) NewSelectorQuery(selector string) (elastic.Query, error) {
	ret := _mock.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for NewSelectorQuery")
	}

	var r0 elastic.Query
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (elastic.Query, error)); ok {
		return returnFunc(selector)
	}
	if returnFunc, ok := ret.Get(0).(func(string) elastic.Query); ok {
		r0 = returnFunc(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elastic.Query)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelper_NewSelectorQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSelectorQuery'
type MockHelper_NewSelectorQuery_Call struct {
	*mock.Call
}

// NewSelectorQuery is a helper method to define mock.On call
//   - selector string
func (_e *MockHelper_Expecter) NewSelectorQuery(selector interface{}) *MockHelper_NewSelectorQuery_Call {
	return &MockHelper_NewSelectorQuery_Call{Call: _e.mock.On("NewSelectorQuery", selector)}
}

func (_c *MockHelper_NewSelectorQuery_Call) Run(run func(selector string)) *MockHelper_NewSelectorQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelper_NewSelectorQuery_Call) Return(query elastic.Query, err error) *MockHelper_NewSelectorQuery_Call {
	_c.Call.Return(query, err)
	return _c
}

func (_c *MockHelper_NewSelectorQuery_Call) RunAndReturn(run func(selector string) (elastic.Query, error)) *MockHelper_NewSelectorQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewTimeRangeQuery provides a mock function for the type MockHelper
func (_mock *MockHelper) NewTimeRangeQuery(r *v10.TimeRange) elastic.Query {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for NewTimeRangeQuery")
	}

	var r0 elastic.Query
	if returnFunc, ok := ret.Get(0).(func(*v10.TimeRange) elastic.Query); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elastic.Query)
		}
	}
	return r0
}

// MockHelper_NewTimeRangeQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTimeRangeQuery'
type MockHelper_NewTimeRangeQuery_Call struct {
	*mock.Call
}

// NewTimeRangeQuery is a helper method to define mock.On call
//   - r *v10.TimeRange
func (_e *MockHelper_Expecter) NewTimeRangeQuery(r interface{}) *MockHelper_NewTimeRangeQuery_Call {
	return &MockHelper_NewTimeRangeQuery_Call{Call: _e.mock.On("NewTimeRangeQuery", r)}
}

func (_c *MockHelper_NewTimeRangeQuery_Call) Run(run func(r *v10.TimeRange)) *MockHelper_NewTimeRangeQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v10.TimeRange
		if args[0] != nil {
			arg0 = args[0].(*v10.TimeRange)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelper_NewTimeRangeQuery_Call) Return(query elastic.Query) *MockHelper_NewTimeRangeQuery_Call {
	_c.Call.Return(query)
	return _c
}

func (_c *MockHelper_NewTimeRangeQuery_Call) RunAndReturn(run func(r *v10.TimeRange) elastic.Query) *MockHelper_NewTimeRangeQuery_Call {
	_c.Call.Return(run)
	return _c
}
