version: v2
workflows:
  - name: cc-dashboard-query-api-ci
    workflowFile: cc-dashboard-query-api/.argoci/ciworkflow.yaml
    runWhen:
      runOnTag: true
      changes:
        in:
          - cc-dashboard-query-api\/.*

