apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: grafana
      name: grafana
  selector:
    app: grafana
