// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dispatcher

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher {
	mock := &MockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher struct {
	mock.Mock
}

type MockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatcher) EXPECT() *MockDispatcher_Expecter {
	return &MockDispatcher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDispatcher
func (_mock *MockDispatcher) Close() {
	_mock.Called()
	return
}

// MockDispatcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDispatcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDispatcher_Expecter) Close() *MockDispatcher_Close_Call {
	return &MockDispatcher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDispatcher_Close_Call) Run(run func()) *MockDispatcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatcher_Close_Call) Return() *MockDispatcher_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Close_Call) RunAndReturn(run func()) *MockDispatcher_Close_Call {
	_c.Run(run)
	return _c
}

// Dispatch provides a mock function for the type MockDispatcher
func (_mock *MockDispatcher) Dispatch(context1 context.Context, cacheRequests []CacheRequest) {
	_mock.Called(context1, cacheRequests)
	return
}

// MockDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - context1 context.Context
//   - cacheRequests []CacheRequest
func (_e *MockDispatcher_Expecter) Dispatch(context1 interface{}, cacheRequests interface{}) *MockDispatcher_Dispatch_Call {
	return &MockDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", context1, cacheRequests)}
}

func (_c *MockDispatcher_Dispatch_Call) Run(run func(context1 context.Context, cacheRequests []CacheRequest)) *MockDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []CacheRequest
		if args[1] != nil {
			arg1 = args[1].([]CacheRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) Return() *MockDispatcher_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Dispatch_Call) RunAndReturn(run func(context1 context.Context, cacheRequests []CacheRequest)) *MockDispatcher_Dispatch_Call {
	_c.Run(run)
	return _c
}
