#!/bin/bash

set -e


SKIP="pkg"

echo "Removing old coverprofiles..."
find . -name "*.coverprofile" -type f -delete

echo "Calculating packages to cover..."

files=$(find tests -name '*_test.go')
if [ -z "$files" ]; then
  echo "No tests found."
  exit 0
fi

go_dirs=$(echo "$files" | \
          grep -vE '/vendor/|.glide|.git' | \
          xargs -n 1 dirname | \
          sort | uniq | \
          tr '\n' ',' | \
          sed 's/,$//' )

echo "Covering: $go_dirs"
test ! -z "$go_dirs"

# Run tests in random order find tests recursively (-r).
ginkgo --cover --coverpkg=${go_dirs} -r --skip-package $SKIP ./tests/fv

echo
echo '+==============+'
echo '| All coverage |'
echo '+==============+'
echo
find . -iname '*.coverprofile' | xargs -I _ go tool cover -func=_

echo
echo '+==================+'
echo '| Missing coverage |'
echo '+==================+'
echo
find . -iname '*.coverprofile' | xargs -I _ go tool cover -func=_ | grep -v '100.0%'
