// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package elasticsearch

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientBuilder creates a new instance of MockClientBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientBuilder {
	mock := &MockClientBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientBuilder is an autogenerated mock type for the ClientBuilder type
type MockClientBuilder struct {
	mock.Mock
}

type MockClientBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientBuilder) EXPECT() *MockClientBuilder_Expecter {
	return &MockClientBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockClientBuilder
func (_mock *MockClientBuilder) Build() (Client, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (Client, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockClientBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockClientBuilder_Expecter) Build() *MockClientBuilder_Build_Call {
	return &MockClientBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockClientBuilder_Build_Call) Run(run func()) *MockClientBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientBuilder_Build_Call) Return(client Client, err error) *MockClientBuilder_Build_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientBuilder_Build_Call) RunAndReturn(run func() (Client, error)) *MockClientBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
