// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tunnel

import (
	"crypto/tls"
	"crypto/x509"
	"net"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnel creates a new instance of MockTunnel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnel {
	mock := &MockTunnel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnel is an autogenerated mock type for the Tunnel type
type MockTunnel struct {
	mock.Mock
}

type MockTunnel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnel) EXPECT() *MockTunnel_Expecter {
	return &MockTunnel_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Accept() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnel_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockTunnel_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Accept() *MockTunnel_Accept_Call {
	return &MockTunnel_Accept_Call{Call: _e.mock.On("Accept")}
}

func (_c *MockTunnel_Accept_Call) Run(run func()) *MockTunnel_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Accept_Call) Return(conn net.Conn, err error) *MockTunnel_Accept_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockTunnel_Accept_Call) RunAndReturn(run func() (net.Conn, error)) *MockTunnel_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// AcceptWithChannel provides a mock function for the type MockTunnel
func (_mock *MockTunnel) AcceptWithChannel(acceptChan chan ConnOrError) chan bool {
	ret := _mock.Called(acceptChan)

	if len(ret) == 0 {
		panic("no return value specified for AcceptWithChannel")
	}

	var r0 chan bool
	if returnFunc, ok := ret.Get(0).(func(chan ConnOrError) chan bool); ok {
		r0 = returnFunc(acceptChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan bool)
		}
	}
	return r0
}

// MockTunnel_AcceptWithChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptWithChannel'
type MockTunnel_AcceptWithChannel_Call struct {
	*mock.Call
}

// AcceptWithChannel is a helper method to define mock.On call
//   - acceptChan chan ConnOrError
func (_e *MockTunnel_Expecter) AcceptWithChannel(acceptChan interface{}) *MockTunnel_AcceptWithChannel_Call {
	return &MockTunnel_AcceptWithChannel_Call{Call: _e.mock.On("AcceptWithChannel", acceptChan)}
}

func (_c *MockTunnel_AcceptWithChannel_Call) Run(run func(acceptChan chan ConnOrError)) *MockTunnel_AcceptWithChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan ConnOrError
		if args[0] != nil {
			arg0 = args[0].(chan ConnOrError)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnel_AcceptWithChannel_Call) Return(boolCh chan bool) *MockTunnel_AcceptWithChannel_Call {
	_c.Call.Return(boolCh)
	return _c
}

func (_c *MockTunnel_AcceptWithChannel_Call) RunAndReturn(run func(acceptChan chan ConnOrError) chan bool) *MockTunnel_AcceptWithChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Addr provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Addr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// MockTunnel_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type MockTunnel_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Addr() *MockTunnel_Addr_Call {
	return &MockTunnel_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *MockTunnel_Addr_Call) Run(run func()) *MockTunnel_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Addr_Call) Return(addr net.Addr) *MockTunnel_Addr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *MockTunnel_Addr_Call) RunAndReturn(run func() net.Addr) *MockTunnel_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Certificate provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Certificate() *x509.Certificate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Certificate")
	}

	var r0 *x509.Certificate
	if returnFunc, ok := ret.Get(0).(func() *x509.Certificate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	return r0
}

// MockTunnel_Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Certificate'
type MockTunnel_Certificate_Call struct {
	*mock.Call
}

// Certificate is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Certificate() *MockTunnel_Certificate_Call {
	return &MockTunnel_Certificate_Call{Call: _e.mock.On("Certificate")}
}

func (_c *MockTunnel_Certificate_Call) Run(run func()) *MockTunnel_Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Certificate_Call) Return(certificate *x509.Certificate) *MockTunnel_Certificate_Call {
	_c.Call.Return(certificate)
	return _c
}

func (_c *MockTunnel_Certificate_Call) RunAndReturn(run func() *x509.Certificate) *MockTunnel_Certificate_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTunnel_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Close() *MockTunnel_Close_Call {
	return &MockTunnel_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTunnel_Close_Call) Run(run func()) *MockTunnel_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Close_Call) Return(err error) *MockTunnel_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Close_Call) RunAndReturn(run func() error) *MockTunnel_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterID provides a mock function for the type MockTunnel
func (_mock *MockTunnel) ClusterID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_ClusterID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterID'
type MockTunnel_ClusterID_Call struct {
	*mock.Call
}

// ClusterID is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) ClusterID() *MockTunnel_ClusterID_Call {
	return &MockTunnel_ClusterID_Call{Call: _e.mock.On("ClusterID")}
}

func (_c *MockTunnel_ClusterID_Call) Run(run func()) *MockTunnel_ClusterID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_ClusterID_Call) Return(s string) *MockTunnel_ClusterID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_ClusterID_Call) RunAndReturn(run func() string) *MockTunnel_ClusterID_Call {
	_c.Call.Return(run)
	return _c
}

// DialTimeout provides a mock function for the type MockTunnel
func (_mock *MockTunnel) DialTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DialTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTunnel_DialTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialTimeout'
type MockTunnel_DialTimeout_Call struct {
	*mock.Call
}

// DialTimeout is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) DialTimeout() *MockTunnel_DialTimeout_Call {
	return &MockTunnel_DialTimeout_Call{Call: _e.mock.On("DialTimeout")}
}

func (_c *MockTunnel_DialTimeout_Call) Run(run func()) *MockTunnel_DialTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_DialTimeout_Call) Return(duration time.Duration) *MockTunnel_DialTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTunnel_DialTimeout_Call) RunAndReturn(run func() time.Duration) *MockTunnel_DialTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ErrChan provides a mock function for the type MockTunnel
func (_mock *MockTunnel) ErrChan() chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrChan")
	}

	var r0 chan struct{}
	if returnFunc, ok := ret.Get(0).(func() chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan struct{})
		}
	}
	return r0
}

// MockTunnel_ErrChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrChan'
type MockTunnel_ErrChan_Call struct {
	*mock.Call
}

// ErrChan is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) ErrChan() *MockTunnel_ErrChan_Call {
	return &MockTunnel_ErrChan_Call{Call: _e.mock.On("ErrChan")}
}

func (_c *MockTunnel_ErrChan_Call) Run(run func()) *MockTunnel_ErrChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_ErrChan_Call) Return(valCh chan struct{}) *MockTunnel_ErrChan_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockTunnel_ErrChan_Call) RunAndReturn(run func() chan struct{}) *MockTunnel_ErrChan_Call {
	_c.Call.Return(run)
	return _c
}

// Fingerprint provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Fingerprint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type MockTunnel_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Fingerprint() *MockTunnel_Fingerprint_Call {
	return &MockTunnel_Fingerprint_Call{Call: _e.mock.On("Fingerprint")}
}

func (_c *MockTunnel_Fingerprint_Call) Run(run func()) *MockTunnel_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Fingerprint_Call) Return(s string) *MockTunnel_Fingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Fingerprint_Call) RunAndReturn(run func() string) *MockTunnel_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// IsClosed provides a mock function for the type MockTunnel
func (_mock *MockTunnel) IsClosed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTunnel_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type MockTunnel_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) IsClosed() *MockTunnel_IsClosed_Call {
	return &MockTunnel_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *MockTunnel_IsClosed_Call) Run(run func()) *MockTunnel_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_IsClosed_Call) Return(b bool) *MockTunnel_IsClosed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTunnel_IsClosed_Call) RunAndReturn(run func() bool) *MockTunnel_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}

// LastErr provides a mock function for the type MockTunnel
func (_mock *MockTunnel) LastErr() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastErr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_LastErr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastErr'
type MockTunnel_LastErr_Call struct {
	*mock.Call
}

// LastErr is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) LastErr() *MockTunnel_LastErr_Call {
	return &MockTunnel_LastErr_Call{Call: _e.mock.On("LastErr")}
}

func (_c *MockTunnel_LastErr_Call) Run(run func()) *MockTunnel_LastErr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_LastErr_Call) Return(err error) *MockTunnel_LastErr_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_LastErr_Call) RunAndReturn(run func() error) *MockTunnel_LastErr_Call {
	_c.Call.Return(run)
	return _c
}

// MD5Fingerprint provides a mock function for the type MockTunnel
func (_mock *MockTunnel) MD5Fingerprint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MD5Fingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_MD5Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MD5Fingerprint'
type MockTunnel_MD5Fingerprint_Call struct {
	*mock.Call
}

// MD5Fingerprint is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) MD5Fingerprint() *MockTunnel_MD5Fingerprint_Call {
	return &MockTunnel_MD5Fingerprint_Call{Call: _e.mock.On("MD5Fingerprint")}
}

func (_c *MockTunnel_MD5Fingerprint_Call) Run(run func()) *MockTunnel_MD5Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_MD5Fingerprint_Call) Return(s string) *MockTunnel_MD5Fingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_MD5Fingerprint_Call) RunAndReturn(run func() string) *MockTunnel_MD5Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Open() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnel_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockTunnel_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Open() *MockTunnel_Open_Call {
	return &MockTunnel_Open_Call{Call: _e.mock.On("Open")}
}

func (_c *MockTunnel_Open_Call) Run(run func()) *MockTunnel_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Open_Call) Return(conn net.Conn, err error) *MockTunnel_Open_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockTunnel_Open_Call) RunAndReturn(run func() (net.Conn, error)) *MockTunnel_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenTLS provides a mock function for the type MockTunnel
func (_mock *MockTunnel) OpenTLS(config *tls.Config) (net.Conn, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for OpenTLS")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*tls.Config) (net.Conn, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(*tls.Config) net.Conn); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*tls.Config) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTunnel_OpenTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenTLS'
type MockTunnel_OpenTLS_Call struct {
	*mock.Call
}

// OpenTLS is a helper method to define mock.On call
//   - config *tls.Config
func (_e *MockTunnel_Expecter) OpenTLS(config interface{}) *MockTunnel_OpenTLS_Call {
	return &MockTunnel_OpenTLS_Call{Call: _e.mock.On("OpenTLS", config)}
}

func (_c *MockTunnel_OpenTLS_Call) Run(run func(config *tls.Config)) *MockTunnel_OpenTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tls.Config
		if args[0] != nil {
			arg0 = args[0].(*tls.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTunnel_OpenTLS_Call) Return(conn net.Conn, err error) *MockTunnel_OpenTLS_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockTunnel_OpenTLS_Call) RunAndReturn(run func(config *tls.Config) (net.Conn, error)) *MockTunnel_OpenTLS_Call {
	_c.Call.Return(run)
	return _c
}
