// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tunnel

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDialer creates a new instance of MockDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialer {
	mock := &MockDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDialer is an autogenerated mock type for the Dialer type
type MockDialer struct {
	mock.Mock
}

type MockDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDialer) EXPECT() *MockDialer_Expecter {
	return &MockDialer_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function for the type MockDialer
func (_mock *MockDialer) Dial() (Tunnel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 Tunnel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (Tunnel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() Tunnel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Tunnel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDialer_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type MockDialer_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
func (_e *MockDialer_Expecter) Dial() *MockDialer_Dial_Call {
	return &MockDialer_Dial_Call{Call: _e.mock.On("Dial")}
}

func (_c *MockDialer_Dial_Call) Run(run func()) *MockDialer_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDialer_Dial_Call) Return(tunnel Tunnel, err error) *MockDialer_Dial_Call {
	_c.Call.Return(tunnel, err)
	return _c
}

func (_c *MockDialer_Dial_Call) RunAndReturn(run func() (Tunnel, error)) *MockDialer_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// Timeout provides a mock function for the type MockDialer
func (_mock *MockDialer) Timeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockDialer_Timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timeout'
type MockDialer_Timeout_Call struct {
	*mock.Call
}

// Timeout is a helper method to define mock.On call
func (_e *MockDialer_Expecter) Timeout() *MockDialer_Timeout_Call {
	return &MockDialer_Timeout_Call{Call: _e.mock.On("Timeout")}
}

func (_c *MockDialer_Timeout_Call) Run(run func()) *MockDialer_Timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDialer_Timeout_Call) Return(duration time.Duration) *MockDialer_Timeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockDialer_Timeout_Call) RunAndReturn(run func() time.Duration) *MockDialer_Timeout_Call {
	_c.Call.Return(run)
	return _c
}
