// Copyright (c) 2019, 2023 Tigera, Inc. All rights reserved.

package tunnel

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net"
	"sync"
	"time"

	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"

	calicotls "github.com/projectcalico/calico/crypto/pkg/tls"
	"github.com/projectcalico/calico/voltron/internal/pkg/utils"
)

type Server interface {
	Accept() (*tls.Conn, error)
	AcceptTunnel(opts ...Option) (Tunnel, error)
	ServeTLS(lis net.Listener) error
	GetClientCertificatePool() *x509.CertPool
	Stop()
}

// Server is a connection server that accepts connections from the provided
// Listener and provides the data streams for the tunnel.
type server struct {
	ctx     context.Context
	cancel  context.CancelFunc
	wg      sync.WaitGroup
	streamC chan *tls.Conn

	// serverCerts contains the certificate chains voltron should present to connecting guardians.
	serverCerts []tls.Certificate

	// clientCertPool defines the set of root certificate authorities this server can use to verify a client certificate.
	// This should be filled with certs generated by the root CA bundle.
	clientCertPool *x509.CertPool

	tlsHandshakeTimeout time.Duration
}

// ServerOption is option for NewServer
type ServerOption func(*server) error

// WithServerCert adds to the certificate chain which voltron should present to connecting guardians.
// This can either be a cert issued by a public CA, or the same cert used as part of the certificate bundle.
func WithServerCert(certs tls.Certificate) ServerOption {
	return func(s *server) error {
		s.serverCerts = append(s.serverCerts, certs)

		log.Debug("tunnel.Server: TLS creds set")
		return nil
	}
}

// WithClientCert adds to the set of root certificate authorities this server can use to verify a client certificate.
// This should be filled with certs generated by the root CA bundle.
func WithClientCert(cert *x509.Certificate) ServerOption {
	return func(s *server) error {
		certPem := utils.CertPEMEncode(cert)
		for {
			block, rest := pem.Decode(certPem)
			if block == nil {
				break
			}

			xCert, err := x509.ParseCertificate(block.Bytes)
			if err != nil {
				return fmt.Errorf("parsing cert PEM failed: %s", err)
			}
			// s.certManager.AddCert(fmt.Sprintf("%x", sha256.Sum256(xCert.Raw)), xCert)
			s.clientCertPool.AddCert(xCert)
			certPem = rest
		}
		//nolint:staticcheck // Ignore SA1019 deprecated
		if len(s.clientCertPool.Subjects()) < 1 {
			return fmt.Errorf("no block in cert key")
		}

		log.Debug("tunnel.Server: TLS client creds set")
		return nil
	}
}

// WithTLSHandshakeTimeout overrides the default 1s timeout for TLS handshake
func WithTLSHandshakeTimeout(to time.Duration) ServerOption {
	return func(s *server) error {
		s.tlsHandshakeTimeout = to
		return nil
	}
}

// NewServer returns a new server
func NewServer(opts ...ServerOption) (Server, error) {
	s := &server{
		streamC:             make(chan *tls.Conn),
		clientCertPool:      x509.NewCertPool(),
		tlsHandshakeTimeout: time.Second,
	}

	for _, opt := range opts {
		err := opt(s)
		if err != nil {
			return nil, errors.WithMessage(err, "tunnel.Server.New")
		}
	}

	s.ctx, s.cancel = context.WithCancel(context.Background())

	return s, nil
}

// ServeTLS starts serving TLS connections using the provided listener and the
// configured certs
func (s *server) ServeTLS(lis net.Listener) error {
	config, err := calicotls.NewTLSConfig()
	if err != nil {
		return err
	}
	config.Certificates = s.serverCerts
	config.ClientAuth = tls.RequireAndVerifyClientCert
	config.ClientCAs = s.clientCertPool

	s.wg.Add(1)
	go func() {
		defer s.wg.Done()
		<-s.ctx.Done()
		_ = lis.Close()
	}()

	tlsLis := tls.NewListener(lis, config)
	for {
		conn, err := tlsLis.Accept()
		if err != nil {
			s.cancel()
			return errors.WithMessage(err, "lis.Accept")
		}

		tlsConn, ok := conn.(*tls.Conn)
		if !ok {
			log.Errorf("tlsConn is not a tls.Conn")
			continue
		}

		log.Debugf("tunnel.Server: new connection from %s", tlsConn.RemoteAddr().String())

		select {
		case s.streamC <- tlsConn:
		case <-s.ctx.Done():
			_ = tlsConn.Close()
			return errors.New("server stopped")
		}
	}
}

// Accept returns the next available stream or returns an error
func (s *server) Accept() (*tls.Conn, error) {
	select {
	case ss := <-s.streamC:
		if !ss.ConnectionState().HandshakeComplete {
			// Set timeout not to hang for ever
			_ = ss.SetReadDeadline(time.Now().Add(s.tlsHandshakeTimeout))
			err := ss.Handshake()
			if err != nil {
				_ = ss.Close()
				return nil, fmt.Errorf("tunnel.Server TLS handshake error from %s: %w", ss.RemoteAddr().String(), err)
			}
			// reset the deadline to no timeout
			_ = ss.SetReadDeadline(time.Time{})
			log.Debugf("TLS HandshakeComplete %t certs %d", ss.ConnectionState().HandshakeComplete, len(ss.ConnectionState().PeerCertificates))
		}

		log.Debugf("tunnel.Server accepted connection from %s", ss.RemoteAddr().String())
		return ss, nil
	case <-s.ctx.Done():
		return nil, errors.New("server is exiting")
	}
}

// AcceptTunnel accepts a new connection as a tunnel
func (s *server) AcceptTunnel(opts ...Option) (Tunnel, error) {
	c, err := s.Accept()
	if err != nil {
		return nil, err
	}

	t, err := NewServerTunnel(c, opts...)
	if err != nil {
		_ = c.Close()
		return nil, err
	}

	// We want to signal that the tunnel is closed when either the tunnel itself has been closed or the server
	// has been shutdown (in which case the context will be cancelled).
	s.wg.Go(func() {
		select {
		case <-t.CloseChan():
		case <-s.ctx.Done():
			_ = t.Close()
		}
	})
	return t, nil
}

func (s *server) GetClientCertificatePool() *x509.CertPool {
	return s.clientCertPool
}

// Stop stops the server and terminates all connections.
func (s *server) Stop() {
	s.cancel()
	s.wg.Wait()
}
