// Code generated by "stringer -type=RouteClass"; DO NOT EDIT.

package routetable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RouteClassLocalWorkload-0]
	_ = x[RouteClassBPFSpecial-1]
	_ = x[RouteClassWireguard-2]
	_ = x[RouteClassVXLANSameSubnet-3]
	_ = x[RouteClassVXLANTunnel-4]
	_ = x[RouteClassIPIPSameSubnet-5]
	_ = x[RouteClassIPIPTunnel-6]
	_ = x[RouteClassIPAMBlockDrop-7]
	_ = x[RouteClassEgress-8]
	_ = x[RouteClassAWSDefault-9]
	_ = x[RouteClassAWSThrow-10]
	_ = x[RouteClassTPROXY-11]
	_ = x[RouteClassMax-12]
}

const _RouteClass_name = "RouteClassLocalWorkloadRouteClassBPFSpecialRouteClassWireguardRouteClassVXLANSameSubnetRouteClassVXLANTunnelRouteClassIPIPSameSubnetRouteClassIPIPTunnelRouteClassIPAMBlockDropRouteClassEgressRouteClassAWSDefaultRouteClassAWSThrowRouteClassTPROXYRouteClassMax"

var _RouteClass_index = [...]uint16{0, 23, 43, 62, 87, 108, 132, 152, 175, 191, 211, 229, 245, 258}

func (i RouteClass) String() string {
	if i < 0 || i >= RouteClass(len(_RouteClass_index)-1) {
		return "RouteClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RouteClass_name[_RouteClass_index[i]:_RouteClass_index[i+1]]
}
