// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package alert

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockForwarder creates a new instance of MockForwarder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForwarder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForwarder {
	mock := &MockForwarder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockForwarder is an autogenerated mock type for the Forwarder type
type MockForwarder struct {
	mock.Mock
}

type MockForwarder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForwarder) EXPECT() *MockForwarder_Expecter {
	return &MockForwarder_Expecter{mock: &_m.Mock}
}

// Forward provides a mock function for the type MockForwarder
func (_mock *MockForwarder) Forward(item v1.Event) {
	_mock.Called(item)
	return
}

// MockForwarder_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockForwarder_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - item v1.Event
func (_e *MockForwarder_Expecter) Forward(item interface{}) *MockForwarder_Forward_Call {
	return &MockForwarder_Forward_Call{Call: _e.mock.On("Forward", item)}
}

func (_c *MockForwarder_Forward_Call) Run(run func(item v1.Event)) *MockForwarder_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1.Event
		if args[0] != nil {
			arg0 = args[0].(v1.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockForwarder_Forward_Call) Return() *MockForwarder_Forward_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockForwarder_Forward_Call) RunAndReturn(run func(item v1.Event)) *MockForwarder_Forward_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockForwarder
func (_mock *MockForwarder) Run(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockForwarder_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockForwarder_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockForwarder_Expecter) Run(ctx interface{}) *MockForwarder_Run_Call {
	return &MockForwarder_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockForwarder_Run_Call) Run(run func(ctx context.Context)) *MockForwarder_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockForwarder_Run_Call) Return() *MockForwarder_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockForwarder_Run_Call) RunAndReturn(run func(ctx context.Context)) *MockForwarder_Run_Call {
	_c.Run(run)
	return _c
}
