apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Namespace}}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "tigera-operator.labels" (dict "context" .) | nindent 4}}
imagePullSecrets:
  {{- include "tigera-operator.imagePullSecrets" . | nindent 2}}
