- apiVersion: projectcalico.org/v3
  kind: Profile
  metadata:
    name: group1
  spec:
    ingress:
      - action: Allow
        source:
          selector: projectcalico.org/namespace == 'group1'
- apiVersion: projectcalico.org/v3
  kind: Profile
  metadata:
    name: group2
  spec:
    ingress:
      - action: Allow
        source:
          selector: projectcalico.org/namespace == 'group2'
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g1w1-eth0
    namespace: group1
    labels:
      app: frontend
      projectcalico.org/namespace: group1
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:e1
    ipNetworks:
      - 192.168.0.1/32
    profiles:
      - group1
    workload: g1w1
    orchestrator: k8s
    node: host1
    pod: g1w1
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g1w2-eth0
    namespace: group1
    labels:
      app: frontend
      projectcalico.org/namespace: group1
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:e2
    ipNetworks:
      - 192.168.0.2/32
    profiles:
      - group1
    workload: g1w2
    orchestrator: k8s
    node: host1
    pod: g1w2
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g1w3-eth0
    namespace: group1
    labels:
      app: frontend
      projectcalico.org/namespace: group1
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:e3
    ipNetworks:
      - 192.168.0.3/32
    profiles:
      - group1
    workload: g1w3
    orchestrator: k8s
    node: host1
    pod: g1w3
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g2w1-eth0
    namespace: group2
    labels:
      app: frontend
      projectcalico.org/namespace: group2
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:f1
    ipNetworks:
      - 192.168.1.1/32
    profiles:
      - group2
    workload: g2w1
    orchestrator: k8s
    node: host1
    pod: g2w1
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g2w2-eth0
    namespace: group2
    labels:
      app: frontend
      projectcalico.org/namespace: group2
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:f2
    ipNetworks:
      - 192.168.1.2/32
    profiles:
      - group2
    workload: g2w2
    orchestrator: k8s
    node: host1
    pod: g2w2
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    name: host1-k8s-g2w3-eth0
    namespace: group2
    labels:
      app: frontend
      projectcalico.org/namespace: group2
  spec:
    interfaceName: cali0ef24ba
    mac: ca:fe:1d:52:bb:f3
    ipNetworks:
      - 192.168.1.3/32
    profiles:
      - group2
    workload: g2w3
    orchestrator: k8s
    node: host1
    pod: g2w3
    endpoint: eth0
- apiVersion: projectcalico.org/v3
  kind: NetworkPolicy
  metadata:
    name: p1
    namespace: group1
  spec:
    selector: projectcalico.org/namespace == 'group1'
    order: 500
    egress:
      - action: Deny
        destination:
          selector: projectcalico.org/namespace == 'group1'
    ingress:
      - action: Allow
        source:
          selector: projectcalico.org/namespace == 'group2'
- apiVersion: projectcalico.org/v3
  kind: NetworkPolicy
  metadata:
    name: abcdefghijklmnopqrstuvwxyz
    namespace: group2
  spec:
    selector: projectcalico.org/namespace == 'group2'
    order: 400
    egress:
      - action: Allow
        destination:
          selector: projectcalico.org/namespace in {'group1','group2'}
    ingress:
      - action: Deny
        source:
          selector: projectcalico.org/namespace in {'group1','group2'}
