action: update
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-from-any-ns
  namespace: "{{.Namespace}}"
  labels:
    churn-k8s: "red-fish"
spec:
  podSelector:
    matchLabels:
      ingress-from-any-ns: "yes"
  ingress:
    - from:
        - namespaceSelector: {}
