#!/bin/bash

set -e

if [ -z $SKIP ]
then
    SKIP="tests,vendor"
else
    SKIP="tests,vendor,$SKIP"
fi

echo "Removing old coverprofiles..."
find . -name "coverprofile.out" -type f -delete

if [ -z $WHAT ]
then
    echo "Calculating packages to cover..."
    go_dirs=$(find -type f -name '*.go' | \
	          grep -vE '/tests/|/vendor/|.glide|.git' | \
	          xargs -n 1 dirname | \
	          sort | uniq | \
	          tr '\n' ',' | \
	          sed 's/,$//' )
else
    go_dirs=$WHAT
fi

echo "Covering: $go_dirs"
test ! -z "$go_dirs"

# Run tests in random order find tests recursively (-r).
echo WHAT: $WHAT
echo SKIP: $SKIP
ginkgo --cover --coverpkg=${go_dirs} -r --skip-package $SKIP $WHAT

echo
echo '+==============+'
echo '| All coverage |'
echo '+==============+'
echo
find . -iname 'coverprofile.out' | xargs -I _ go tool cover -func=_

echo
echo '+==================+'
echo '| Missing coverage |'
echo '+==================+'
echo
find . -iname 'coverprofile.out' | xargs -I _ go tool cover -func=_ | grep -v '100.0%'
