# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# This Dockerfile packages the istio install-cni binary built from source into a minimal container.
# The binary is built separately using the Makefile, which compiles istio with Calico patches applied.

ARG CALICO_BASE
ARG UBI_IMAGE

FROM ${UBI_IMAGE} AS ubi

RUN microdnf upgrade -y && \
  microdnf install -y iptables nftables

# Prepare a rootfs for necessary files from UBI.
# Symbolic links are preserved.
RUN mkdir -p /rootfs/lib64 /rootfs/usr/sbin && \
    # required binaries
    cp -L /usr/sbin/xtables-nft-multi /rootfs/usr/sbin/xtables-nft-multi && \
    cp -L /usr/sbin/nft /rootfs/usr/sbin/nft && \

    # required libraries
    cp -L /lib64/libxtables.so.12 /rootfs/lib64/libxtables.so.12 && \
    cp -L /lib64/libxtables.so.12.7.0 /rootfs/lib64/libxtables.so.12.7.0 && \
    cp -L /lib64/libmnl.so.0 /rootfs/lib64/libmnl.so.0 && \
    cp -L /lib64/libnftnl.so.11 /rootfs/lib64/libnftnl.so.11 && \
    cp -L /lib64/libc.so.6 /rootfs/lib64/libc.so.6 && \
    cp -L /lib64/ld-linux-x86-64.so.2 /rootfs/lib64/ld-linux-x86-64.so.2 && \
    cp -L /lib64/libnftables.so.1 /rootfs/lib64/libnftables.so.1 && \
    cp -L /lib64/libreadline.so.8 /rootfs/lib64/libreadline.so.8 && \
    cp -L /lib64/libjansson.so.4 /rootfs/lib64/libjansson.so.4 && \
    cp -L /lib64/libgmp.so.10 /rootfs/lib64/libgmp.so.10 && \
    cp -L /lib64/libtinfo.so.6 /rootfs/lib64/libtinfo.so.6 && \

    # create symlinks to xtables-nft-multi 
    cd /rootfs/usr/sbin && \
    ln -s xtables-nft-multi arptables && \
    ln -s xtables-nft-multi arptables-nft && \
    ln -s xtables-nft-multi arptables-nft-restore && \
    ln -s xtables-nft-multi arptables-nft-save && \
    ln -s xtables-nft-multi arptables-restore && \
    ln -s xtables-nft-multi arptables-save && \
    ln -s xtables-nft-multi ebtables && \
    ln -s xtables-nft-multi ebtables-nft && \
    ln -s xtables-nft-multi ebtables-nft-restore && \
    ln -s xtables-nft-multi ebtables-nft-save && \
    ln -s xtables-nft-multi ebtables-restore && \
    ln -s xtables-nft-multi ebtables-save && \
    ln -s xtables-nft-multi ebtables-translate && \
    ln -s xtables-nft-multi ip6tables && \
    ln -s xtables-nft-multi ip6tables-nft && \
    ln -s xtables-nft-multi ip6tables-nft-restore && \
    ln -s xtables-nft-multi ip6tables-nft-save && \
    ln -s xtables-nft-multi ip6tables-restore && \
    ln -s xtables-nft-multi ip6tables-restore-translate && \
    ln -s xtables-nft-multi ip6tables-save && \
    ln -s xtables-nft-multi ip6tables-translate && \
    ln -s xtables-nft-multi iptables && \
    ln -s xtables-nft-multi iptables-nft && \
    ln -s xtables-nft-multi iptables-nft-restore && \
    ln -s xtables-nft-multi iptables-nft-save && \
    ln -s xtables-nft-multi iptables-restore && \
    ln -s xtables-nft-multi iptables-restore-translate && \
    ln -s xtables-nft-multi iptables-save && \
    ln -s xtables-nft-multi iptables-translate && \
    ln -s xtables-nft-multi xtables-monitor

FROM scratch AS source

ARG TARGETARCH

COPY bin/install-cni-${TARGETARCH} /usr/bin/install-cni
COPY bin/LICENSE /LICENSE

COPY --from=ubi /rootfs /

FROM ${CALICO_BASE}

ARG GIT_VERSION=unknown

LABEL description="This image contains a build of Istio's CNI component from github.com/istio/istio with Calico patches applied"
LABEL maintainer="maintainers@tigera.io"
LABEL name="Calico Istio CNI"
LABEL release="1"
LABEL summary="Istio CNI is the CNI plugin for Calico's integration with Istio ambient mesh"
LABEL vendor="Project Calico"
LABEL version="${GIT_VERSION}"

LABEL org.opencontainers.image.description="This image contains a build of Istio's CNI component from github.com/istio/istio with Calico patches applied"
LABEL org.opencontainers.image.authors="maintainers@tigera.io"
LABEL org.opencontainers.image.source="https://github.com/projectcalico/calico"
LABEL org.opencontainers.image.title="Istio CNI is the CNI plugin for Calico's integration with Istio ambient mesh"
LABEL org.opencontainers.image.vendor="Project Calico"
LABEL org.opencontainers.image.version="${GIT_VERSION}"
LABEL org.opencontainers.image.licenses="Apache-2.0"

COPY --from=source / /

USER 10001:10001

ENTRYPOINT ["/usr/bin/install-cni"]
