# Copyright (c) 2025 Tigera, Inc. All rights reserved.
#
# This Dockerfile packages the istio install-cni binary built from source into a minimal container.
# The binary is built separately using the Makefile, which compiles istio with Calico patches applied.

ARG CALICO_BASE
ARG UBI_IMAGE

FROM ${UBI_IMAGE} AS ubi

RUN microdnf upgrade -y && \
  microdnf install -y iptables nftables

FROM scratch AS source

ARG TARGETARCH

COPY bin/install-cni-${TARGETARCH} /usr/bin/install-cni
COPY bin/LICENSE /LICENSE

# xtables-nft-multi is the actual binary - copy it to standard iptables/ip6tables names
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/xtables-nft-multi
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/iptables
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/iptables-restore
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/iptables-save
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/ip6tables
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/ip6tables-restore
COPY --from=ubi /usr/sbin/xtables-nft-multi /usr/sbin/ip6tables-save

# nftables
COPY --from=ubi /usr/sbin/nft /usr/sbin/nft

# xtables plugins directory
COPY --from=ubi /usr/lib64/xtables /lib64/xtables

# required libraries (ldd shows they're expected in /lib64)
COPY --from=ubi /usr/lib64/libxtables.so.12 /lib64/libxtables.so.12
COPY --from=ubi /usr/lib64/libxtables.so.12.7.0 /lib64/libxtables.so.12.7.0
COPY --from=ubi /lib64/libmnl.so.0 /lib64/libmnl.so.0
COPY --from=ubi /lib64/libnftnl.so.11 /lib64/libnftnl.so.11
COPY --from=ubi /lib64/libm.so.6 /lib64/libm.so.6

FROM ${CALICO_BASE}

ARG GIT_VERSION=unknown

LABEL description="This image contains a build of Istio's CNI component from github.com/istio/istio with Calico patches applied"
LABEL maintainer="maintainers@tigera.io"
LABEL name="Calico Istio CNI"
LABEL release="1"
LABEL summary="Istio CNI is the CNI plugin for Calico's integration with Istio ambient mesh"
LABEL vendor="Project Calico"
LABEL version="${GIT_VERSION}"

LABEL org.opencontainers.image.description="This image contains a build of Istio's CNI component from github.com/istio/istio with Calico patches applied"
LABEL org.opencontainers.image.authors="maintainers@tigera.io"
LABEL org.opencontainers.image.source="https://github.com/projectcalico/calico"
LABEL org.opencontainers.image.title="Istio CNI is the CNI plugin for Calico's integration with Istio ambient mesh"
LABEL org.opencontainers.image.vendor="Project Calico"
LABEL org.opencontainers.image.version="${GIT_VERSION}"
LABEL org.opencontainers.image.licenses="Apache-2.0"

COPY --from=source / /

USER 10001:10001

ENTRYPOINT ["/usr/bin/install-cni"]
