// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryInterface creates a new instance of MockQueryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryInterface {
	mock := &MockQueryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryInterface is an autogenerated mock type for the QueryInterface type
type MockQueryInterface struct {
	mock.Mock
}

type MockQueryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryInterface) EXPECT() *MockQueryInterface_Expecter {
	return &MockQueryInterface_Expecter{mock: &_m.Mock}
}

// RunQuery provides a mock function for the type MockQueryInterface
func (_mock *MockQueryInterface) RunQuery(ctx context.Context, req any) (any, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RunQuery")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) (any, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) any); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, any) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryInterface_RunQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunQuery'
type MockQueryInterface_RunQuery_Call struct {
	*mock.Call
}

// RunQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - req any
func (_e *MockQueryInterface_Expecter) RunQuery(ctx interface{}, req interface{}) *MockQueryInterface_RunQuery_Call {
	return &MockQueryInterface_RunQuery_Call{Call: _e.mock.On("RunQuery", ctx, req)}
}

func (_c *MockQueryInterface_RunQuery_Call) Run(run func(ctx context.Context, req any)) *MockQueryInterface_RunQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryInterface_RunQuery_Call) Return(v any, err error) *MockQueryInterface_RunQuery_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockQueryInterface_RunQuery_Call) RunAndReturn(run func(ctx context.Context, req any) (any, error)) *MockQueryInterface_RunQuery_Call {
	_c.Call.Return(run)
	return _c
}
