// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	v3 "github.com/tigera/api/pkg/apis/projectcalico/v3"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ExecuteAlert provides a mock function for the type MockService
func (_mock *MockService) ExecuteAlert(context1 context.Context, globalAlert *v3.GlobalAlert) v3.GlobalAlertStatus {
	ret := _mock.Called(context1, globalAlert)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteAlert")
	}

	var r0 v3.GlobalAlertStatus
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v3.GlobalAlert) v3.GlobalAlertStatus); ok {
		r0 = returnFunc(context1, globalAlert)
	} else {
		r0 = ret.Get(0).(v3.GlobalAlertStatus)
	}
	return r0
}

// MockService_ExecuteAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteAlert'
type MockService_ExecuteAlert_Call struct {
	*mock.Call
}

// ExecuteAlert is a helper method to define mock.On call
//   - context1 context.Context
//   - globalAlert *v3.GlobalAlert
func (_e *MockService_Expecter) ExecuteAlert(context1 interface{}, globalAlert interface{}) *MockService_ExecuteAlert_Call {
	return &MockService_ExecuteAlert_Call{Call: _e.mock.On("ExecuteAlert", context1, globalAlert)}
}

func (_c *MockService_ExecuteAlert_Call) Run(run func(context1 context.Context, globalAlert *v3.GlobalAlert)) *MockService_ExecuteAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v3.GlobalAlert
		if args[1] != nil {
			arg1 = args[1].(*v3.GlobalAlert)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ExecuteAlert_Call) Return(globalAlertStatus v3.GlobalAlertStatus) *MockService_ExecuteAlert_Call {
	_c.Call.Return(globalAlertStatus)
	return _c
}

func (_c *MockService_ExecuteAlert_Call) RunAndReturn(run func(context1 context.Context, globalAlert *v3.GlobalAlert) v3.GlobalAlertStatus) *MockService_ExecuteAlert_Call {
	_c.Call.Return(run)
	return _c
}
