// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dpiupdater

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/projectcalico/calico/libcalico-go/lib/backend/model"
)

// NewMockDPIStatusUpdater creates a new instance of MockDPIStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDPIStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDPIStatusUpdater {
	mock := &MockDPIStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDPIStatusUpdater is an autogenerated mock type for the DPIStatusUpdater type
type MockDPIStatusUpdater struct {
	mock.Mock
}

type MockDPIStatusUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDPIStatusUpdater) EXPECT() *MockDPIStatusUpdater_Expecter {
	return &MockDPIStatusUpdater_Expecter{mock: &_m.Mock}
}

// UpdateStatus provides a mock function for the type MockDPIStatusUpdater
func (_mock *MockDPIStatusUpdater) UpdateStatus(ctx context.Context, dpiKey model.ResourceKey, isActive bool) {
	_mock.Called(ctx, dpiKey, isActive)
	return
}

// MockDPIStatusUpdater_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockDPIStatusUpdater_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - dpiKey model.ResourceKey
//   - isActive bool
func (_e *MockDPIStatusUpdater_Expecter) UpdateStatus(ctx interface{}, dpiKey interface{}, isActive interface{}) *MockDPIStatusUpdater_UpdateStatus_Call {
	return &MockDPIStatusUpdater_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, dpiKey, isActive)}
}

func (_c *MockDPIStatusUpdater_UpdateStatus_Call) Run(run func(ctx context.Context, dpiKey model.ResourceKey, isActive bool)) *MockDPIStatusUpdater_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ResourceKey
		if args[1] != nil {
			arg1 = args[1].(model.ResourceKey)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDPIStatusUpdater_UpdateStatus_Call) Return() *MockDPIStatusUpdater_UpdateStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDPIStatusUpdater_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, dpiKey model.ResourceKey, isActive bool)) *MockDPIStatusUpdater_UpdateStatus_Call {
	_c.Run(run)
	return _c
}

// UpdateStatusWithError provides a mock function for the type MockDPIStatusUpdater
func (_mock *MockDPIStatusUpdater) UpdateStatusWithError(ctx context.Context, dpiKey model.ResourceKey, isActive bool, errMsg string) {
	_mock.Called(ctx, dpiKey, isActive, errMsg)
	return
}

// MockDPIStatusUpdater_UpdateStatusWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusWithError'
type MockDPIStatusUpdater_UpdateStatusWithError_Call struct {
	*mock.Call
}

// UpdateStatusWithError is a helper method to define mock.On call
//   - ctx context.Context
//   - dpiKey model.ResourceKey
//   - isActive bool
//   - errMsg string
func (_e *MockDPIStatusUpdater_Expecter) UpdateStatusWithError(ctx interface{}, dpiKey interface{}, isActive interface{}, errMsg interface{}) *MockDPIStatusUpdater_UpdateStatusWithError_Call {
	return &MockDPIStatusUpdater_UpdateStatusWithError_Call{Call: _e.mock.On("UpdateStatusWithError", ctx, dpiKey, isActive, errMsg)}
}

func (_c *MockDPIStatusUpdater_UpdateStatusWithError_Call) Run(run func(ctx context.Context, dpiKey model.ResourceKey, isActive bool, errMsg string)) *MockDPIStatusUpdater_UpdateStatusWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ResourceKey
		if args[1] != nil {
			arg1 = args[1].(model.ResourceKey)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDPIStatusUpdater_UpdateStatusWithError_Call) Return() *MockDPIStatusUpdater_UpdateStatusWithError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDPIStatusUpdater_UpdateStatusWithError_Call) RunAndReturn(run func(ctx context.Context, dpiKey model.ResourceKey, isActive bool, errMsg string)) *MockDPIStatusUpdater_UpdateStatusWithError_Call {
	_c.Run(run)
	return _c
}
