// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockWAFBackend creates a new instance of MockWAFBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWAFBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWAFBackend {
	mock := &MockWAFBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWAFBackend is an autogenerated mock type for the WAFBackend type
type MockWAFBackend struct {
	mock.Mock
}

type MockWAFBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWAFBackend) EXPECT() *MockWAFBackend_Expecter {
	return &MockWAFBackend_Expecter{mock: &_m.Mock}
}

// Aggregations provides a mock function for the type MockWAFBackend
func (_mock *MockWAFBackend) Aggregations(context1 context.Context, clusterInfo ClusterInfo, wAFLogAggregationParams *v1.WAFLogAggregationParams) (*elastic.Aggregations, error) {
	ret := _mock.Called(context1, clusterInfo, wAFLogAggregationParams)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.WAFLogAggregationParams) (*elastic.Aggregations, error)); ok {
		return returnFunc(context1, clusterInfo, wAFLogAggregationParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.WAFLogAggregationParams) *elastic.Aggregations); ok {
		r0 = returnFunc(context1, clusterInfo, wAFLogAggregationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.WAFLogAggregationParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, wAFLogAggregationParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWAFBackend_Aggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregations'
type MockWAFBackend_Aggregations_Call struct {
	*mock.Call
}

// Aggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - wAFLogAggregationParams *v1.WAFLogAggregationParams
func (_e *MockWAFBackend_Expecter) Aggregations(context1 interface{}, clusterInfo interface{}, wAFLogAggregationParams interface{}) *MockWAFBackend_Aggregations_Call {
	return &MockWAFBackend_Aggregations_Call{Call: _e.mock.On("Aggregations", context1, clusterInfo, wAFLogAggregationParams)}
}

func (_c *MockWAFBackend_Aggregations_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogAggregationParams *v1.WAFLogAggregationParams)) *MockWAFBackend_Aggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.WAFLogAggregationParams
		if args[2] != nil {
			arg2 = args[2].(*v1.WAFLogAggregationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWAFBackend_Aggregations_Call) Return(aggregations *elastic.Aggregations, err error) *MockWAFBackend_Aggregations_Call {
	_c.Call.Return(aggregations, err)
	return _c
}

func (_c *MockWAFBackend_Aggregations_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogAggregationParams *v1.WAFLogAggregationParams) (*elastic.Aggregations, error)) *MockWAFBackend_Aggregations_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockWAFBackend
func (_mock *MockWAFBackend) Create(context1 context.Context, clusterInfo ClusterInfo, wAFLogs []v1.WAFLog) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, wAFLogs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.WAFLog) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, wAFLogs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.WAFLog) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, wAFLogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.WAFLog) error); ok {
		r1 = returnFunc(context1, clusterInfo, wAFLogs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWAFBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWAFBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - wAFLogs []v1.WAFLog
func (_e *MockWAFBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, wAFLogs interface{}) *MockWAFBackend_Create_Call {
	return &MockWAFBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, wAFLogs)}
}

func (_c *MockWAFBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogs []v1.WAFLog)) *MockWAFBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.WAFLog
		if args[2] != nil {
			arg2 = args[2].([]v1.WAFLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWAFBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockWAFBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockWAFBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogs []v1.WAFLog) (*v1.BulkResponse, error)) *MockWAFBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWAFBackend
func (_mock *MockWAFBackend) List(context1 context.Context, clusterInfo ClusterInfo, wAFLogParams *v1.WAFLogParams) (*v1.List[v1.WAFLog], error) {
	ret := _mock.Called(context1, clusterInfo, wAFLogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.WAFLog]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.WAFLogParams) (*v1.List[v1.WAFLog], error)); ok {
		return returnFunc(context1, clusterInfo, wAFLogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.WAFLogParams) *v1.List[v1.WAFLog]); ok {
		r0 = returnFunc(context1, clusterInfo, wAFLogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.WAFLog])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.WAFLogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, wAFLogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWAFBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWAFBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - wAFLogParams *v1.WAFLogParams
func (_e *MockWAFBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, wAFLogParams interface{}) *MockWAFBackend_List_Call {
	return &MockWAFBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, wAFLogParams)}
}

func (_c *MockWAFBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogParams *v1.WAFLogParams)) *MockWAFBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.WAFLogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.WAFLogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWAFBackend_List_Call) Return(list *v1.List[v1.WAFLog], err error) *MockWAFBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockWAFBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, wAFLogParams *v1.WAFLogParams) (*v1.List[v1.WAFLog], error)) *MockWAFBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
