// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockSnapshotsBackend creates a new instance of MockSnapshotsBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotsBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotsBackend {
	mock := &MockSnapshotsBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotsBackend is an autogenerated mock type for the SnapshotsBackend type
type MockSnapshotsBackend struct {
	mock.Mock
}

type MockSnapshotsBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotsBackend) EXPECT() *MockSnapshotsBackend_Expecter {
	return &MockSnapshotsBackend_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSnapshotsBackend
func (_mock *MockSnapshotsBackend) Create(context1 context.Context, clusterInfo ClusterInfo, snapshots []v1.Snapshot) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, snapshots)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Snapshot) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, snapshots)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Snapshot) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, snapshots)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.Snapshot) error); ok {
		r1 = returnFunc(context1, clusterInfo, snapshots)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotsBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSnapshotsBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - snapshots []v1.Snapshot
func (_e *MockSnapshotsBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, snapshots interface{}) *MockSnapshotsBackend_Create_Call {
	return &MockSnapshotsBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, snapshots)}
}

func (_c *MockSnapshotsBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, snapshots []v1.Snapshot)) *MockSnapshotsBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.Snapshot
		if args[2] != nil {
			arg2 = args[2].([]v1.Snapshot)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotsBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockSnapshotsBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockSnapshotsBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, snapshots []v1.Snapshot) (*v1.BulkResponse, error)) *MockSnapshotsBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSnapshotsBackend
func (_mock *MockSnapshotsBackend) List(context1 context.Context, clusterInfo ClusterInfo, snapshotParams *v1.SnapshotParams) (*v1.List[v1.Snapshot], error) {
	ret := _mock.Called(context1, clusterInfo, snapshotParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.Snapshot]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.SnapshotParams) (*v1.List[v1.Snapshot], error)); ok {
		return returnFunc(context1, clusterInfo, snapshotParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.SnapshotParams) *v1.List[v1.Snapshot]); ok {
		r0 = returnFunc(context1, clusterInfo, snapshotParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.Snapshot])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.SnapshotParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, snapshotParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSnapshotsBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSnapshotsBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - snapshotParams *v1.SnapshotParams
func (_e *MockSnapshotsBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, snapshotParams interface{}) *MockSnapshotsBackend_List_Call {
	return &MockSnapshotsBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, snapshotParams)}
}

func (_c *MockSnapshotsBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, snapshotParams *v1.SnapshotParams)) *MockSnapshotsBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.SnapshotParams
		if args[2] != nil {
			arg2 = args[2].(*v1.SnapshotParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSnapshotsBackend_List_Call) Return(list *v1.List[v1.Snapshot], err error) *MockSnapshotsBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockSnapshotsBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, snapshotParams *v1.SnapshotParams) (*v1.List[v1.Snapshot], error)) *MockSnapshotsBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
