// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockL7FlowBackend creates a new instance of MockL7FlowBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockL7FlowBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockL7FlowBackend {
	mock := &MockL7FlowBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockL7FlowBackend is an autogenerated mock type for the L7FlowBackend type
type MockL7FlowBackend struct {
	mock.Mock
}

type MockL7FlowBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockL7FlowBackend) EXPECT() *MockL7FlowBackend_Expecter {
	return &MockL7FlowBackend_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockL7FlowBackend
func (_mock *MockL7FlowBackend) List(context1 context.Context, clusterInfo ClusterInfo, l7FlowParams *v1.L7FlowParams) (*v1.List[v1.L7Flow], error) {
	ret := _mock.Called(context1, clusterInfo, l7FlowParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.L7Flow]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7FlowParams) (*v1.List[v1.L7Flow], error)); ok {
		return returnFunc(context1, clusterInfo, l7FlowParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7FlowParams) *v1.List[v1.L7Flow]); ok {
		r0 = returnFunc(context1, clusterInfo, l7FlowParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.L7Flow])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L7FlowParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, l7FlowParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockL7FlowBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockL7FlowBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l7FlowParams *v1.L7FlowParams
func (_e *MockL7FlowBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, l7FlowParams interface{}) *MockL7FlowBackend_List_Call {
	return &MockL7FlowBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, l7FlowParams)}
}

func (_c *MockL7FlowBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l7FlowParams *v1.L7FlowParams)) *MockL7FlowBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.L7FlowParams
		if args[2] != nil {
			arg2 = args[2].(*v1.L7FlowParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockL7FlowBackend_List_Call) Return(list *v1.List[v1.L7Flow], err error) *MockL7FlowBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockL7FlowBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l7FlowParams *v1.L7FlowParams) (*v1.List[v1.L7Flow], error)) *MockL7FlowBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
