// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockBGPBackend creates a new instance of MockBGPBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBGPBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBGPBackend {
	mock := &MockBGPBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBGPBackend is an autogenerated mock type for the BGPBackend type
type MockBGPBackend struct {
	mock.Mock
}

type MockBGPBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBGPBackend) EXPECT() *MockBGPBackend_Expecter {
	return &MockBGPBackend_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBGPBackend
func (_mock *MockBGPBackend) Create(context1 context.Context, clusterInfo ClusterInfo, bGPLogs []v1.BGPLog) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, bGPLogs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.BGPLog) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, bGPLogs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.BGPLog) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, bGPLogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.BGPLog) error); ok {
		r1 = returnFunc(context1, clusterInfo, bGPLogs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBGPBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBGPBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - bGPLogs []v1.BGPLog
func (_e *MockBGPBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, bGPLogs interface{}) *MockBGPBackend_Create_Call {
	return &MockBGPBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, bGPLogs)}
}

func (_c *MockBGPBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, bGPLogs []v1.BGPLog)) *MockBGPBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.BGPLog
		if args[2] != nil {
			arg2 = args[2].([]v1.BGPLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBGPBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockBGPBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockBGPBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, bGPLogs []v1.BGPLog) (*v1.BulkResponse, error)) *MockBGPBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBGPBackend
func (_mock *MockBGPBackend) List(context1 context.Context, clusterInfo ClusterInfo, bGPLogParams *v1.BGPLogParams) (*v1.List[v1.BGPLog], error) {
	ret := _mock.Called(context1, clusterInfo, bGPLogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.BGPLog]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.BGPLogParams) (*v1.List[v1.BGPLog], error)); ok {
		return returnFunc(context1, clusterInfo, bGPLogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.BGPLogParams) *v1.List[v1.BGPLog]); ok {
		r0 = returnFunc(context1, clusterInfo, bGPLogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.BGPLog])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.BGPLogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, bGPLogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBGPBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBGPBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - bGPLogParams *v1.BGPLogParams
func (_e *MockBGPBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, bGPLogParams interface{}) *MockBGPBackend_List_Call {
	return &MockBGPBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, bGPLogParams)}
}

func (_c *MockBGPBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, bGPLogParams *v1.BGPLogParams)) *MockBGPBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.BGPLogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.BGPLogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBGPBackend_List_Call) Return(list *v1.List[v1.BGPLog], err error) *MockBGPBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockBGPBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, bGPLogParams *v1.BGPLogParams) (*v1.List[v1.BGPLog], error)) *MockBGPBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
