// Code generated by mockery v2.46.3. DO NOT EDIT.

package api

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// MockFlowBackend is an autogenerated mock type for the FlowBackend type
type MockFlowBackend struct {
	mock.Mock
}

// List provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFlowBackend) List(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.L3FlowParams) (*v1.List[v1.L3Flow], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.L3Flow]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowParams) (*v1.List[v1.L3Flow], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowParams) *v1.List[v1.L3Flow]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.L3Flow])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L3FlowParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockFlowBackend) Count(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.L3FlowCountParams) (*v1.CountResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *v1.CountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) (*v1.CountResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) *v1.CountResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFlowBackend creates a new instance of MockFlowBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowBackend {
	mock := &MockFlowBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
