// Code generated by mockery v2.46.3. DO NOT EDIT.

package api

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// MockPolicyBackend is an autogenerated mock type for the PolicyBackend type
type MockPolicyBackend struct {
	mock.Mock
}

// Close provides a mock function
func (_m *MockPolicyBackend) Close() {
	_m.Called()
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockPolicyBackend) Create(_a0 context.Context, _a1 ClusterInfo, _a2 []v1.PolicyActivity) (*v1.BulkResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.PolicyActivity) (*v1.BulkResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.PolicyActivity) *v1.BulkResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.PolicyActivity) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicyActivities provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockPolicyBackend) GetPolicyActivities(_a0 context.Context, _a1 ClusterInfo, _a2 *v1.PolicyActivityParams) (*v1.PolicyActivityResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyActivities")
	}

	var r0 *v1.PolicyActivityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.PolicyActivityParams) (*v1.PolicyActivityResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.PolicyActivityParams) *v1.PolicyActivityResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PolicyActivityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.PolicyActivityParams) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPolicyBackend creates a new instance of MockPolicyBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyBackend {
	mock := &MockPolicyBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
