// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockL7LogBackend creates a new instance of MockL7LogBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockL7LogBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockL7LogBackend {
	mock := &MockL7LogBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockL7LogBackend is an autogenerated mock type for the L7LogBackend type
type MockL7LogBackend struct {
	mock.Mock
}

type MockL7LogBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockL7LogBackend) EXPECT() *MockL7LogBackend_Expecter {
	return &MockL7LogBackend_Expecter{mock: &_m.Mock}
}

// Aggregations provides a mock function for the type MockL7LogBackend
func (_mock *MockL7LogBackend) Aggregations(context1 context.Context, clusterInfo ClusterInfo, l7AggregationParams *v1.L7AggregationParams) (*elastic.Aggregations, error) {
	ret := _mock.Called(context1, clusterInfo, l7AggregationParams)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7AggregationParams) (*elastic.Aggregations, error)); ok {
		return returnFunc(context1, clusterInfo, l7AggregationParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7AggregationParams) *elastic.Aggregations); ok {
		r0 = returnFunc(context1, clusterInfo, l7AggregationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L7AggregationParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, l7AggregationParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockL7LogBackend_Aggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregations'
type MockL7LogBackend_Aggregations_Call struct {
	*mock.Call
}

// Aggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l7AggregationParams *v1.L7AggregationParams
func (_e *MockL7LogBackend_Expecter) Aggregations(context1 interface{}, clusterInfo interface{}, l7AggregationParams interface{}) *MockL7LogBackend_Aggregations_Call {
	return &MockL7LogBackend_Aggregations_Call{Call: _e.mock.On("Aggregations", context1, clusterInfo, l7AggregationParams)}
}

func (_c *MockL7LogBackend_Aggregations_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l7AggregationParams *v1.L7AggregationParams)) *MockL7LogBackend_Aggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.L7AggregationParams
		if args[2] != nil {
			arg2 = args[2].(*v1.L7AggregationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockL7LogBackend_Aggregations_Call) Return(aggregations *elastic.Aggregations, err error) *MockL7LogBackend_Aggregations_Call {
	_c.Call.Return(aggregations, err)
	return _c
}

func (_c *MockL7LogBackend_Aggregations_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l7AggregationParams *v1.L7AggregationParams) (*elastic.Aggregations, error)) *MockL7LogBackend_Aggregations_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockL7LogBackend
func (_mock *MockL7LogBackend) Create(context1 context.Context, clusterInfo ClusterInfo, l7Logs []v1.L7Log) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, l7Logs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.L7Log) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, l7Logs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.L7Log) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, l7Logs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.L7Log) error); ok {
		r1 = returnFunc(context1, clusterInfo, l7Logs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockL7LogBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockL7LogBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l7Logs []v1.L7Log
func (_e *MockL7LogBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, l7Logs interface{}) *MockL7LogBackend_Create_Call {
	return &MockL7LogBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, l7Logs)}
}

func (_c *MockL7LogBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l7Logs []v1.L7Log)) *MockL7LogBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.L7Log
		if args[2] != nil {
			arg2 = args[2].([]v1.L7Log)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockL7LogBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockL7LogBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockL7LogBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l7Logs []v1.L7Log) (*v1.BulkResponse, error)) *MockL7LogBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockL7LogBackend
func (_mock *MockL7LogBackend) List(context1 context.Context, clusterInfo ClusterInfo, l7LogParams *v1.L7LogParams) (*v1.List[v1.L7Log], error) {
	ret := _mock.Called(context1, clusterInfo, l7LogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.L7Log]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7LogParams) (*v1.List[v1.L7Log], error)); ok {
		return returnFunc(context1, clusterInfo, l7LogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L7LogParams) *v1.List[v1.L7Log]); ok {
		r0 = returnFunc(context1, clusterInfo, l7LogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.L7Log])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L7LogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, l7LogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockL7LogBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockL7LogBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l7LogParams *v1.L7LogParams
func (_e *MockL7LogBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, l7LogParams interface{}) *MockL7LogBackend_List_Call {
	return &MockL7LogBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, l7LogParams)}
}

func (_c *MockL7LogBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l7LogParams *v1.L7LogParams)) *MockL7LogBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.L7LogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.L7LogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockL7LogBackend_List_Call) Return(list *v1.List[v1.L7Log], err error) *MockL7LogBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockL7LogBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l7LogParams *v1.L7LogParams) (*v1.List[v1.L7Log], error)) *MockL7LogBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
