// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockEventsBackend creates a new instance of MockEventsBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsBackend {
	mock := &MockEventsBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventsBackend is an autogenerated mock type for the EventsBackend type
type MockEventsBackend struct {
	mock.Mock
}

type MockEventsBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsBackend) EXPECT() *MockEventsBackend_Expecter {
	return &MockEventsBackend_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEventsBackend
func (_mock *MockEventsBackend) Create(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, events)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, events)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.Event) error); ok {
		r1 = returnFunc(context1, clusterInfo, events)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventsBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - events []v1.Event
func (_e *MockEventsBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, events interface{}) *MockEventsBackend_Create_Call {
	return &MockEventsBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, events)}
}

func (_c *MockEventsBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event)) *MockEventsBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.Event
		if args[2] != nil {
			arg2 = args[2].([]v1.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockEventsBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockEventsBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error)) *MockEventsBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEventsBackend
func (_mock *MockEventsBackend) Delete(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, events)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, events)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.Event) error); ok {
		r1 = returnFunc(context1, clusterInfo, events)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventsBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - events []v1.Event
func (_e *MockEventsBackend_Expecter) Delete(context1 interface{}, clusterInfo interface{}, events interface{}) *MockEventsBackend_Delete_Call {
	return &MockEventsBackend_Delete_Call{Call: _e.mock.On("Delete", context1, clusterInfo, events)}
}

func (_c *MockEventsBackend_Delete_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event)) *MockEventsBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.Event
		if args[2] != nil {
			arg2 = args[2].([]v1.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsBackend_Delete_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockEventsBackend_Delete_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockEventsBackend_Delete_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error)) *MockEventsBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventsBackend
func (_mock *MockEventsBackend) List(context1 context.Context, clusterInfo ClusterInfo, eventParams *v1.EventParams) (*v1.List[v1.Event], error) {
	ret := _mock.Called(context1, clusterInfo, eventParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.Event]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.EventParams) (*v1.List[v1.Event], error)); ok {
		return returnFunc(context1, clusterInfo, eventParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.EventParams) *v1.List[v1.Event]); ok {
		r0 = returnFunc(context1, clusterInfo, eventParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.Event])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.EventParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, eventParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventsBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - eventParams *v1.EventParams
func (_e *MockEventsBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, eventParams interface{}) *MockEventsBackend_List_Call {
	return &MockEventsBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, eventParams)}
}

func (_c *MockEventsBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, eventParams *v1.EventParams)) *MockEventsBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.EventParams
		if args[2] != nil {
			arg2 = args[2].(*v1.EventParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsBackend_List_Call) Return(list *v1.List[v1.Event], err error) *MockEventsBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockEventsBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, eventParams *v1.EventParams) (*v1.List[v1.Event], error)) *MockEventsBackend_List_Call {
	_c.Call.Return(run)
	return _c
}

// Statistics provides a mock function for the type MockEventsBackend
func (_mock *MockEventsBackend) Statistics(context1 context.Context, clusterInfo ClusterInfo, eventStatisticsParams *v1.EventStatisticsParams) (*v1.EventStatistics, error) {
	ret := _mock.Called(context1, clusterInfo, eventStatisticsParams)

	if len(ret) == 0 {
		panic("no return value specified for Statistics")
	}

	var r0 *v1.EventStatistics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.EventStatisticsParams) (*v1.EventStatistics, error)); ok {
		return returnFunc(context1, clusterInfo, eventStatisticsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.EventStatisticsParams) *v1.EventStatistics); ok {
		r0 = returnFunc(context1, clusterInfo, eventStatisticsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.EventStatistics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.EventStatisticsParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, eventStatisticsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsBackend_Statistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Statistics'
type MockEventsBackend_Statistics_Call struct {
	*mock.Call
}

// Statistics is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - eventStatisticsParams *v1.EventStatisticsParams
func (_e *MockEventsBackend_Expecter) Statistics(context1 interface{}, clusterInfo interface{}, eventStatisticsParams interface{}) *MockEventsBackend_Statistics_Call {
	return &MockEventsBackend_Statistics_Call{Call: _e.mock.On("Statistics", context1, clusterInfo, eventStatisticsParams)}
}

func (_c *MockEventsBackend_Statistics_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, eventStatisticsParams *v1.EventStatisticsParams)) *MockEventsBackend_Statistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.EventStatisticsParams
		if args[2] != nil {
			arg2 = args[2].(*v1.EventStatisticsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsBackend_Statistics_Call) Return(eventStatistics *v1.EventStatistics, err error) *MockEventsBackend_Statistics_Call {
	_c.Call.Return(eventStatistics, err)
	return _c
}

func (_c *MockEventsBackend_Statistics_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, eventStatisticsParams *v1.EventStatisticsParams) (*v1.EventStatistics, error)) *MockEventsBackend_Statistics_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDismissFlag provides a mock function for the type MockEventsBackend
func (_mock *MockEventsBackend) UpdateDismissFlag(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, events)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDismissFlag")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, events)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.Event) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.Event) error); ok {
		r1 = returnFunc(context1, clusterInfo, events)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventsBackend_UpdateDismissFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDismissFlag'
type MockEventsBackend_UpdateDismissFlag_Call struct {
	*mock.Call
}

// UpdateDismissFlag is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - events []v1.Event
func (_e *MockEventsBackend_Expecter) UpdateDismissFlag(context1 interface{}, clusterInfo interface{}, events interface{}) *MockEventsBackend_UpdateDismissFlag_Call {
	return &MockEventsBackend_UpdateDismissFlag_Call{Call: _e.mock.On("UpdateDismissFlag", context1, clusterInfo, events)}
}

func (_c *MockEventsBackend_UpdateDismissFlag_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event)) *MockEventsBackend_UpdateDismissFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.Event
		if args[2] != nil {
			arg2 = args[2].([]v1.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventsBackend_UpdateDismissFlag_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockEventsBackend_UpdateDismissFlag_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockEventsBackend_UpdateDismissFlag_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, events []v1.Event) (*v1.BulkResponse, error)) *MockEventsBackend_UpdateDismissFlag_Call {
	_c.Call.Return(run)
	return _c
}
