// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockDNSLogBackend creates a new instance of MockDNSLogBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSLogBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSLogBackend {
	mock := &MockDNSLogBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSLogBackend is an autogenerated mock type for the DNSLogBackend type
type MockDNSLogBackend struct {
	mock.Mock
}

type MockDNSLogBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSLogBackend) EXPECT() *MockDNSLogBackend_Expecter {
	return &MockDNSLogBackend_Expecter{mock: &_m.Mock}
}

// Aggregations provides a mock function for the type MockDNSLogBackend
func (_mock *MockDNSLogBackend) Aggregations(context1 context.Context, clusterInfo ClusterInfo, dNSAggregationParams *v1.DNSAggregationParams) (*elastic.Aggregations, error) {
	ret := _mock.Called(context1, clusterInfo, dNSAggregationParams)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSAggregationParams) (*elastic.Aggregations, error)); ok {
		return returnFunc(context1, clusterInfo, dNSAggregationParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSAggregationParams) *elastic.Aggregations); ok {
		r0 = returnFunc(context1, clusterInfo, dNSAggregationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.DNSAggregationParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, dNSAggregationParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSLogBackend_Aggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregations'
type MockDNSLogBackend_Aggregations_Call struct {
	*mock.Call
}

// Aggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - dNSAggregationParams *v1.DNSAggregationParams
func (_e *MockDNSLogBackend_Expecter) Aggregations(context1 interface{}, clusterInfo interface{}, dNSAggregationParams interface{}) *MockDNSLogBackend_Aggregations_Call {
	return &MockDNSLogBackend_Aggregations_Call{Call: _e.mock.On("Aggregations", context1, clusterInfo, dNSAggregationParams)}
}

func (_c *MockDNSLogBackend_Aggregations_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, dNSAggregationParams *v1.DNSAggregationParams)) *MockDNSLogBackend_Aggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.DNSAggregationParams
		if args[2] != nil {
			arg2 = args[2].(*v1.DNSAggregationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSLogBackend_Aggregations_Call) Return(aggregations *elastic.Aggregations, err error) *MockDNSLogBackend_Aggregations_Call {
	_c.Call.Return(aggregations, err)
	return _c
}

func (_c *MockDNSLogBackend_Aggregations_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, dNSAggregationParams *v1.DNSAggregationParams) (*elastic.Aggregations, error)) *MockDNSLogBackend_Aggregations_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockDNSLogBackend
func (_mock *MockDNSLogBackend) Create(context1 context.Context, clusterInfo ClusterInfo, dNSLogs []v1.DNSLog) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, dNSLogs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.DNSLog) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, dNSLogs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.DNSLog) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, dNSLogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.DNSLog) error); ok {
		r1 = returnFunc(context1, clusterInfo, dNSLogs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSLogBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDNSLogBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - dNSLogs []v1.DNSLog
func (_e *MockDNSLogBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, dNSLogs interface{}) *MockDNSLogBackend_Create_Call {
	return &MockDNSLogBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, dNSLogs)}
}

func (_c *MockDNSLogBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, dNSLogs []v1.DNSLog)) *MockDNSLogBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.DNSLog
		if args[2] != nil {
			arg2 = args[2].([]v1.DNSLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSLogBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockDNSLogBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockDNSLogBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, dNSLogs []v1.DNSLog) (*v1.BulkResponse, error)) *MockDNSLogBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDNSLogBackend
func (_mock *MockDNSLogBackend) List(context1 context.Context, clusterInfo ClusterInfo, dNSLogParams *v1.DNSLogParams) (*v1.List[v1.DNSLog], error) {
	ret := _mock.Called(context1, clusterInfo, dNSLogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.DNSLog]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSLogParams) (*v1.List[v1.DNSLog], error)); ok {
		return returnFunc(context1, clusterInfo, dNSLogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSLogParams) *v1.List[v1.DNSLog]); ok {
		r0 = returnFunc(context1, clusterInfo, dNSLogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.DNSLog])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.DNSLogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, dNSLogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSLogBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDNSLogBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - dNSLogParams *v1.DNSLogParams
func (_e *MockDNSLogBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, dNSLogParams interface{}) *MockDNSLogBackend_List_Call {
	return &MockDNSLogBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, dNSLogParams)}
}

func (_c *MockDNSLogBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, dNSLogParams *v1.DNSLogParams)) *MockDNSLogBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.DNSLogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.DNSLogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSLogBackend_List_Call) Return(list *v1.List[v1.DNSLog], err error) *MockDNSLogBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockDNSLogBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, dNSLogParams *v1.DNSLogParams) (*v1.List[v1.DNSLog], error)) *MockDNSLogBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
