// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockReportsBackend creates a new instance of MockReportsBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportsBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportsBackend {
	mock := &MockReportsBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportsBackend is an autogenerated mock type for the ReportsBackend type
type MockReportsBackend struct {
	mock.Mock
}

type MockReportsBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportsBackend) EXPECT() *MockReportsBackend_Expecter {
	return &MockReportsBackend_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReportsBackend
func (_mock *MockReportsBackend) Create(context1 context.Context, clusterInfo ClusterInfo, reportDatas []v1.ReportData) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, reportDatas)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.ReportData) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, reportDatas)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.ReportData) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, reportDatas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.ReportData) error); ok {
		r1 = returnFunc(context1, clusterInfo, reportDatas)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportsBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReportsBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - reportDatas []v1.ReportData
func (_e *MockReportsBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, reportDatas interface{}) *MockReportsBackend_Create_Call {
	return &MockReportsBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, reportDatas)}
}

func (_c *MockReportsBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, reportDatas []v1.ReportData)) *MockReportsBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.ReportData
		if args[2] != nil {
			arg2 = args[2].([]v1.ReportData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportsBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockReportsBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockReportsBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, reportDatas []v1.ReportData) (*v1.BulkResponse, error)) *MockReportsBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockReportsBackend
func (_mock *MockReportsBackend) List(context1 context.Context, clusterInfo ClusterInfo, reportDataParams *v1.ReportDataParams) (*v1.List[v1.ReportData], error) {
	ret := _mock.Called(context1, clusterInfo, reportDataParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.ReportData]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.ReportDataParams) (*v1.List[v1.ReportData], error)); ok {
		return returnFunc(context1, clusterInfo, reportDataParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.ReportDataParams) *v1.List[v1.ReportData]); ok {
		r0 = returnFunc(context1, clusterInfo, reportDataParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.ReportData])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.ReportDataParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, reportDataParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportsBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockReportsBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - reportDataParams *v1.ReportDataParams
func (_e *MockReportsBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, reportDataParams interface{}) *MockReportsBackend_List_Call {
	return &MockReportsBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, reportDataParams)}
}

func (_c *MockReportsBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, reportDataParams *v1.ReportDataParams)) *MockReportsBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.ReportDataParams
		if args[2] != nil {
			arg2 = args[2].(*v1.ReportDataParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportsBackend_List_Call) Return(list *v1.List[v1.ReportData], err error) *MockReportsBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockReportsBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, reportDataParams *v1.ReportDataParams) (*v1.List[v1.ReportData], error)) *MockReportsBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
