// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockFlowBackend creates a new instance of MockFlowBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowBackend {
	mock := &MockFlowBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlowBackend is an autogenerated mock type for the FlowBackend type
type MockFlowBackend struct {
	mock.Mock
}

type MockFlowBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlowBackend) EXPECT() *MockFlowBackend_Expecter {
	return &MockFlowBackend_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockFlowBackend
func (_mock *MockFlowBackend) Count(context1 context.Context, clusterInfo ClusterInfo, l3FlowCountParams *v1.L3FlowCountParams) (*v1.CountResponse, error) {
	ret := _mock.Called(context1, clusterInfo, l3FlowCountParams)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *v1.CountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) (*v1.CountResponse, error)); ok {
		return returnFunc(context1, clusterInfo, l3FlowCountParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) *v1.CountResponse); ok {
		r0 = returnFunc(context1, clusterInfo, l3FlowCountParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CountResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L3FlowCountParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, l3FlowCountParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowBackend_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockFlowBackend_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l3FlowCountParams *v1.L3FlowCountParams
func (_e *MockFlowBackend_Expecter) Count(context1 interface{}, clusterInfo interface{}, l3FlowCountParams interface{}) *MockFlowBackend_Count_Call {
	return &MockFlowBackend_Count_Call{Call: _e.mock.On("Count", context1, clusterInfo, l3FlowCountParams)}
}

func (_c *MockFlowBackend_Count_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l3FlowCountParams *v1.L3FlowCountParams)) *MockFlowBackend_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.L3FlowCountParams
		if args[2] != nil {
			arg2 = args[2].(*v1.L3FlowCountParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowBackend_Count_Call) Return(countResponse *v1.CountResponse, err error) *MockFlowBackend_Count_Call {
	_c.Call.Return(countResponse, err)
	return _c
}

func (_c *MockFlowBackend_Count_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l3FlowCountParams *v1.L3FlowCountParams) (*v1.CountResponse, error)) *MockFlowBackend_Count_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFlowBackend
func (_mock *MockFlowBackend) List(context1 context.Context, clusterInfo ClusterInfo, l3FlowParams *v1.L3FlowParams) (*v1.List[v1.L3Flow], error) {
	ret := _mock.Called(context1, clusterInfo, l3FlowParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.L3Flow]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowParams) (*v1.List[v1.L3Flow], error)); ok {
		return returnFunc(context1, clusterInfo, l3FlowParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.L3FlowParams) *v1.List[v1.L3Flow]); ok {
		r0 = returnFunc(context1, clusterInfo, l3FlowParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.L3Flow])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.L3FlowParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, l3FlowParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlowBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - l3FlowParams *v1.L3FlowParams
func (_e *MockFlowBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, l3FlowParams interface{}) *MockFlowBackend_List_Call {
	return &MockFlowBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, l3FlowParams)}
}

func (_c *MockFlowBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, l3FlowParams *v1.L3FlowParams)) *MockFlowBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.L3FlowParams
		if args[2] != nil {
			arg2 = args[2].(*v1.L3FlowParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowBackend_List_Call) Return(list *v1.List[v1.L3Flow], err error) *MockFlowBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockFlowBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, l3FlowParams *v1.L3FlowParams) (*v1.List[v1.L3Flow], error)) *MockFlowBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
