// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockFlowLogBackend creates a new instance of MockFlowLogBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowLogBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowLogBackend {
	mock := &MockFlowLogBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlowLogBackend is an autogenerated mock type for the FlowLogBackend type
type MockFlowLogBackend struct {
	mock.Mock
}

type MockFlowLogBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlowLogBackend) EXPECT() *MockFlowLogBackend_Expecter {
	return &MockFlowLogBackend_Expecter{mock: &_m.Mock}
}

// Aggregations provides a mock function for the type MockFlowLogBackend
func (_mock *MockFlowLogBackend) Aggregations(context1 context.Context, clusterInfo ClusterInfo, flowLogAggregationParams *v1.FlowLogAggregationParams) (*elastic.Aggregations, error) {
	ret := _mock.Called(context1, clusterInfo, flowLogAggregationParams)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogAggregationParams) (*elastic.Aggregations, error)); ok {
		return returnFunc(context1, clusterInfo, flowLogAggregationParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogAggregationParams) *elastic.Aggregations); ok {
		r0 = returnFunc(context1, clusterInfo, flowLogAggregationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.FlowLogAggregationParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, flowLogAggregationParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowLogBackend_Aggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregations'
type MockFlowLogBackend_Aggregations_Call struct {
	*mock.Call
}

// Aggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - flowLogAggregationParams *v1.FlowLogAggregationParams
func (_e *MockFlowLogBackend_Expecter) Aggregations(context1 interface{}, clusterInfo interface{}, flowLogAggregationParams interface{}) *MockFlowLogBackend_Aggregations_Call {
	return &MockFlowLogBackend_Aggregations_Call{Call: _e.mock.On("Aggregations", context1, clusterInfo, flowLogAggregationParams)}
}

func (_c *MockFlowLogBackend_Aggregations_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogAggregationParams *v1.FlowLogAggregationParams)) *MockFlowLogBackend_Aggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.FlowLogAggregationParams
		if args[2] != nil {
			arg2 = args[2].(*v1.FlowLogAggregationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowLogBackend_Aggregations_Call) Return(aggregations *elastic.Aggregations, err error) *MockFlowLogBackend_Aggregations_Call {
	_c.Call.Return(aggregations, err)
	return _c
}

func (_c *MockFlowLogBackend_Aggregations_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogAggregationParams *v1.FlowLogAggregationParams) (*elastic.Aggregations, error)) *MockFlowLogBackend_Aggregations_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockFlowLogBackend
func (_mock *MockFlowLogBackend) Count(context1 context.Context, clusterInfo ClusterInfo, flowLogCountParams *v1.FlowLogCountParams) (*v1.CountResponse, error) {
	ret := _mock.Called(context1, clusterInfo, flowLogCountParams)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 *v1.CountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogCountParams) (*v1.CountResponse, error)); ok {
		return returnFunc(context1, clusterInfo, flowLogCountParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogCountParams) *v1.CountResponse); ok {
		r0 = returnFunc(context1, clusterInfo, flowLogCountParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CountResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.FlowLogCountParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, flowLogCountParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowLogBackend_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockFlowLogBackend_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - flowLogCountParams *v1.FlowLogCountParams
func (_e *MockFlowLogBackend_Expecter) Count(context1 interface{}, clusterInfo interface{}, flowLogCountParams interface{}) *MockFlowLogBackend_Count_Call {
	return &MockFlowLogBackend_Count_Call{Call: _e.mock.On("Count", context1, clusterInfo, flowLogCountParams)}
}

func (_c *MockFlowLogBackend_Count_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogCountParams *v1.FlowLogCountParams)) *MockFlowLogBackend_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.FlowLogCountParams
		if args[2] != nil {
			arg2 = args[2].(*v1.FlowLogCountParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowLogBackend_Count_Call) Return(countResponse *v1.CountResponse, err error) *MockFlowLogBackend_Count_Call {
	_c.Call.Return(countResponse, err)
	return _c
}

func (_c *MockFlowLogBackend_Count_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogCountParams *v1.FlowLogCountParams) (*v1.CountResponse, error)) *MockFlowLogBackend_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockFlowLogBackend
func (_mock *MockFlowLogBackend) Create(context1 context.Context, clusterInfo ClusterInfo, flowLogs []v1.FlowLog) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, clusterInfo, flowLogs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.FlowLog) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, clusterInfo, flowLogs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, []v1.FlowLog) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, clusterInfo, flowLogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, []v1.FlowLog) error); ok {
		r1 = returnFunc(context1, clusterInfo, flowLogs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowLogBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFlowLogBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - flowLogs []v1.FlowLog
func (_e *MockFlowLogBackend_Expecter) Create(context1 interface{}, clusterInfo interface{}, flowLogs interface{}) *MockFlowLogBackend_Create_Call {
	return &MockFlowLogBackend_Create_Call{Call: _e.mock.On("Create", context1, clusterInfo, flowLogs)}
}

func (_c *MockFlowLogBackend_Create_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogs []v1.FlowLog)) *MockFlowLogBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 []v1.FlowLog
		if args[2] != nil {
			arg2 = args[2].([]v1.FlowLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowLogBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockFlowLogBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockFlowLogBackend_Create_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogs []v1.FlowLog) (*v1.BulkResponse, error)) *MockFlowLogBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFlowLogBackend
func (_mock *MockFlowLogBackend) List(context1 context.Context, clusterInfo ClusterInfo, flowLogParams *v1.FlowLogParams) (*v1.List[v1.FlowLog], error) {
	ret := _mock.Called(context1, clusterInfo, flowLogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.FlowLog]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogParams) (*v1.List[v1.FlowLog], error)); ok {
		return returnFunc(context1, clusterInfo, flowLogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.FlowLogParams) *v1.List[v1.FlowLog]); ok {
		r0 = returnFunc(context1, clusterInfo, flowLogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.FlowLog])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.FlowLogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, flowLogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowLogBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlowLogBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - flowLogParams *v1.FlowLogParams
func (_e *MockFlowLogBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, flowLogParams interface{}) *MockFlowLogBackend_List_Call {
	return &MockFlowLogBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, flowLogParams)}
}

func (_c *MockFlowLogBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogParams *v1.FlowLogParams)) *MockFlowLogBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.FlowLogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.FlowLogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlowLogBackend_List_Call) Return(list *v1.List[v1.FlowLog], err error) *MockFlowLogBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockFlowLogBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, flowLogParams *v1.FlowLogParams) (*v1.List[v1.FlowLog], error)) *MockFlowLogBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
