// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockAuditBackend creates a new instance of MockAuditBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditBackend {
	mock := &MockAuditBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditBackend is an autogenerated mock type for the AuditBackend type
type MockAuditBackend struct {
	mock.Mock
}

type MockAuditBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditBackend) EXPECT() *MockAuditBackend_Expecter {
	return &MockAuditBackend_Expecter{mock: &_m.Mock}
}

// Aggregations provides a mock function for the type MockAuditBackend
func (_mock *MockAuditBackend) Aggregations(context1 context.Context, clusterInfo ClusterInfo, auditLogAggregationParams *v1.AuditLogAggregationParams) (*elastic.Aggregations, error) {
	ret := _mock.Called(context1, clusterInfo, auditLogAggregationParams)

	if len(ret) == 0 {
		panic("no return value specified for Aggregations")
	}

	var r0 *elastic.Aggregations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) (*elastic.Aggregations, error)); ok {
		return returnFunc(context1, clusterInfo, auditLogAggregationParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) *elastic.Aggregations); ok {
		r0 = returnFunc(context1, clusterInfo, auditLogAggregationParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Aggregations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.AuditLogAggregationParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, auditLogAggregationParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditBackend_Aggregations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregations'
type MockAuditBackend_Aggregations_Call struct {
	*mock.Call
}

// Aggregations is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - auditLogAggregationParams *v1.AuditLogAggregationParams
func (_e *MockAuditBackend_Expecter) Aggregations(context1 interface{}, clusterInfo interface{}, auditLogAggregationParams interface{}) *MockAuditBackend_Aggregations_Call {
	return &MockAuditBackend_Aggregations_Call{Call: _e.mock.On("Aggregations", context1, clusterInfo, auditLogAggregationParams)}
}

func (_c *MockAuditBackend_Aggregations_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, auditLogAggregationParams *v1.AuditLogAggregationParams)) *MockAuditBackend_Aggregations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.AuditLogAggregationParams
		if args[2] != nil {
			arg2 = args[2].(*v1.AuditLogAggregationParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditBackend_Aggregations_Call) Return(aggregations *elastic.Aggregations, err error) *MockAuditBackend_Aggregations_Call {
	_c.Call.Return(aggregations, err)
	return _c
}

func (_c *MockAuditBackend_Aggregations_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, auditLogAggregationParams *v1.AuditLogAggregationParams) (*elastic.Aggregations, error)) *MockAuditBackend_Aggregations_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAuditBackend
func (_mock *MockAuditBackend) Create(context1 context.Context, auditLogType v1.AuditLogType, clusterInfo ClusterInfo, auditLogs []v1.AuditLog) (*v1.BulkResponse, error) {
	ret := _mock.Called(context1, auditLogType, clusterInfo, auditLogs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BulkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) (*v1.BulkResponse, error)); ok {
		return returnFunc(context1, auditLogType, clusterInfo, auditLogs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) *v1.BulkResponse); ok {
		r0 = returnFunc(context1, auditLogType, clusterInfo, auditLogs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BulkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1.AuditLogType, ClusterInfo, []v1.AuditLog) error); ok {
		r1 = returnFunc(context1, auditLogType, clusterInfo, auditLogs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditBackend_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditBackend_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - auditLogType v1.AuditLogType
//   - clusterInfo ClusterInfo
//   - auditLogs []v1.AuditLog
func (_e *MockAuditBackend_Expecter) Create(context1 interface{}, auditLogType interface{}, clusterInfo interface{}, auditLogs interface{}) *MockAuditBackend_Create_Call {
	return &MockAuditBackend_Create_Call{Call: _e.mock.On("Create", context1, auditLogType, clusterInfo, auditLogs)}
}

func (_c *MockAuditBackend_Create_Call) Run(run func(context1 context.Context, auditLogType v1.AuditLogType, clusterInfo ClusterInfo, auditLogs []v1.AuditLog)) *MockAuditBackend_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.AuditLogType
		if args[1] != nil {
			arg1 = args[1].(v1.AuditLogType)
		}
		var arg2 ClusterInfo
		if args[2] != nil {
			arg2 = args[2].(ClusterInfo)
		}
		var arg3 []v1.AuditLog
		if args[3] != nil {
			arg3 = args[3].([]v1.AuditLog)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuditBackend_Create_Call) Return(bulkResponse *v1.BulkResponse, err error) *MockAuditBackend_Create_Call {
	_c.Call.Return(bulkResponse, err)
	return _c
}

func (_c *MockAuditBackend_Create_Call) RunAndReturn(run func(context1 context.Context, auditLogType v1.AuditLogType, clusterInfo ClusterInfo, auditLogs []v1.AuditLog) (*v1.BulkResponse, error)) *MockAuditBackend_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAuditBackend
func (_mock *MockAuditBackend) List(context1 context.Context, clusterInfo ClusterInfo, auditLogParams *v1.AuditLogParams) (*v1.List[v1.AuditLog], error) {
	ret := _mock.Called(context1, clusterInfo, auditLogParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.AuditLog]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogParams) (*v1.List[v1.AuditLog], error)); ok {
		return returnFunc(context1, clusterInfo, auditLogParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.AuditLogParams) *v1.List[v1.AuditLog]); ok {
		r0 = returnFunc(context1, clusterInfo, auditLogParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.AuditLog])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.AuditLogParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, auditLogParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - auditLogParams *v1.AuditLogParams
func (_e *MockAuditBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, auditLogParams interface{}) *MockAuditBackend_List_Call {
	return &MockAuditBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, auditLogParams)}
}

func (_c *MockAuditBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, auditLogParams *v1.AuditLogParams)) *MockAuditBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.AuditLogParams
		if args[2] != nil {
			arg2 = args[2].(*v1.AuditLogParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditBackend_List_Call) Return(list *v1.List[v1.AuditLog], err error) *MockAuditBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockAuditBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, auditLogParams *v1.AuditLogParams) (*v1.List[v1.AuditLog], error)) *MockAuditBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
