// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/projectcalico/calico/linseed/pkg/apis/v1"
)

// NewMockDNSFlowBackend creates a new instance of MockDNSFlowBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSFlowBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSFlowBackend {
	mock := &MockDNSFlowBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSFlowBackend is an autogenerated mock type for the DNSFlowBackend type
type MockDNSFlowBackend struct {
	mock.Mock
}

type MockDNSFlowBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSFlowBackend) EXPECT() *MockDNSFlowBackend_Expecter {
	return &MockDNSFlowBackend_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockDNSFlowBackend
func (_mock *MockDNSFlowBackend) List(context1 context.Context, clusterInfo ClusterInfo, dNSFlowParams *v1.DNSFlowParams) (*v1.List[v1.DNSFlow], error) {
	ret := _mock.Called(context1, clusterInfo, dNSFlowParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.List[v1.DNSFlow]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSFlowParams) (*v1.List[v1.DNSFlow], error)); ok {
		return returnFunc(context1, clusterInfo, dNSFlowParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ClusterInfo, *v1.DNSFlowParams) *v1.List[v1.DNSFlow]); ok {
		r0 = returnFunc(context1, clusterInfo, dNSFlowParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.List[v1.DNSFlow])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ClusterInfo, *v1.DNSFlowParams) error); ok {
		r1 = returnFunc(context1, clusterInfo, dNSFlowParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSFlowBackend_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDNSFlowBackend_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - clusterInfo ClusterInfo
//   - dNSFlowParams *v1.DNSFlowParams
func (_e *MockDNSFlowBackend_Expecter) List(context1 interface{}, clusterInfo interface{}, dNSFlowParams interface{}) *MockDNSFlowBackend_List_Call {
	return &MockDNSFlowBackend_List_Call{Call: _e.mock.On("List", context1, clusterInfo, dNSFlowParams)}
}

func (_c *MockDNSFlowBackend_List_Call) Run(run func(context1 context.Context, clusterInfo ClusterInfo, dNSFlowParams *v1.DNSFlowParams)) *MockDNSFlowBackend_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ClusterInfo
		if args[1] != nil {
			arg1 = args[1].(ClusterInfo)
		}
		var arg2 *v1.DNSFlowParams
		if args[2] != nil {
			arg2 = args[2].(*v1.DNSFlowParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDNSFlowBackend_List_Call) Return(list *v1.List[v1.DNSFlow], err error) *MockDNSFlowBackend_List_Call {
	_c.Call.Return(list, err)
	return _c
}

func (_c *MockDNSFlowBackend_List_Call) RunAndReturn(run func(context1 context.Context, clusterInfo ClusterInfo, dNSFlowParams *v1.DNSFlowParams) (*v1.List[v1.DNSFlow], error)) *MockDNSFlowBackend_List_Call {
	_c.Call.Return(run)
	return _c
}
