// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// Flow is an autogenerated mock type for the Flow type
type Flow struct {
	mock.Mock
}

// GetDestIP provides a mock function with no fields
func (_m *Flow) GetDestIP() net.IP {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDestIP")
	}

	var r0 net.IP
	if rf, ok := ret.Get(0).(func() net.IP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}

	return r0
}

// GetDestLabels provides a mock function with no fields
func (_m *Flow) GetDestLabels() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDestLabels")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetDestPort provides a mock function with no fields
func (_m *Flow) GetDestPort() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDestPort")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetDestPrincipal provides a mock function with no fields
func (_m *Flow) GetDestPrincipal() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDestPrincipal")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetHttpHeaders provides a mock function with no fields
func (_m *Flow) GetHttpHeaders() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHttpHeaders")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetHttpMethod provides a mock function with no fields
func (_m *Flow) GetHttpMethod() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHttpMethod")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetHttpPath provides a mock function with no fields
func (_m *Flow) GetHttpPath() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHttpPath")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetProtocol provides a mock function with no fields
func (_m *Flow) GetProtocol() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProtocol")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetSourceIP provides a mock function with no fields
func (_m *Flow) GetSourceIP() net.IP {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourceIP")
	}

	var r0 net.IP
	if rf, ok := ret.Get(0).(func() net.IP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}

	return r0
}

// GetSourceLabels provides a mock function with no fields
func (_m *Flow) GetSourceLabels() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourceLabels")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetSourcePort provides a mock function with no fields
func (_m *Flow) GetSourcePort() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourcePort")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetSourcePrincipal provides a mock function with no fields
func (_m *Flow) GetSourcePrincipal() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourcePrincipal")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// NewFlow creates a new instance of Flow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlow(t interface {
	mock.TestingT
	Cleanup(func())
}) *Flow {
	mock := &Flow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
