// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/rest"

	"github.com/projectcalico/calico/lma/pkg/auth"
	"github.com/projectcalico/calico/lma/pkg/k8s"
)

// NewMockClientCache creates a new instance of MockClientCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientCache {
	mock := &MockClientCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientCache is an autogenerated mock type for the ClientCache type
type MockClientCache struct {
	mock.Mock
}

type MockClientCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientCache) EXPECT() *MockClientCache_Expecter {
	return &MockClientCache_Expecter{mock: &_m.Mock}
}

// GetAuthorizer provides a mock function for the type MockClientCache
func (_mock *MockClientCache) GetAuthorizer(clusterID string) (auth.RBACAuthorizer, error) {
	ret := _mock.Called(clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizer")
	}

	var r0 auth.RBACAuthorizer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (auth.RBACAuthorizer, error)); ok {
		return returnFunc(clusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) auth.RBACAuthorizer); ok {
		r0 = returnFunc(clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.RBACAuthorizer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(clusterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientCache_GetAuthorizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizer'
type MockClientCache_GetAuthorizer_Call struct {
	*mock.Call
}

// GetAuthorizer is a helper method to define mock.On call
//   - clusterID string
func (_e *MockClientCache_Expecter) GetAuthorizer(clusterID interface{}) *MockClientCache_GetAuthorizer_Call {
	return &MockClientCache_GetAuthorizer_Call{Call: _e.mock.On("GetAuthorizer", clusterID)}
}

func (_c *MockClientCache_GetAuthorizer_Call) Run(run func(clusterID string)) *MockClientCache_GetAuthorizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientCache_GetAuthorizer_Call) Return(rBACAuthorizer auth.RBACAuthorizer, err error) *MockClientCache_GetAuthorizer_Call {
	_c.Call.Return(rBACAuthorizer, err)
	return _c
}

func (_c *MockClientCache_GetAuthorizer_Call) RunAndReturn(run func(clusterID string) (auth.RBACAuthorizer, error)) *MockClientCache_GetAuthorizer_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientAndConfig provides a mock function for the type MockClientCache
func (_mock *MockClientCache) GetClientAndConfig(clusterID string) (k8s.ClientSet, *rest.Config, error) {
	ret := _mock.Called(clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientAndConfig")
	}

	var r0 k8s.ClientSet
	var r1 *rest.Config
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (k8s.ClientSet, *rest.Config, error)); ok {
		return returnFunc(clusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) k8s.ClientSet); ok {
		r0 = returnFunc(clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(k8s.ClientSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *rest.Config); ok {
		r1 = returnFunc(clusterID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rest.Config)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(clusterID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClientCache_GetClientAndConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientAndConfig'
type MockClientCache_GetClientAndConfig_Call struct {
	*mock.Call
}

// GetClientAndConfig is a helper method to define mock.On call
//   - clusterID string
func (_e *MockClientCache_Expecter) GetClientAndConfig(clusterID interface{}) *MockClientCache_GetClientAndConfig_Call {
	return &MockClientCache_GetClientAndConfig_Call{Call: _e.mock.On("GetClientAndConfig", clusterID)}
}

func (_c *MockClientCache_GetClientAndConfig_Call) Run(run func(clusterID string)) *MockClientCache_GetClientAndConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientCache_GetClientAndConfig_Call) Return(clientSet k8s.ClientSet, config *rest.Config, err error) *MockClientCache_GetClientAndConfig_Call {
	_c.Call.Return(clientSet, config, err)
	return _c
}

func (_c *MockClientCache_GetClientAndConfig_Call) RunAndReturn(run func(clusterID string) (k8s.ClientSet, *rest.Config, error)) *MockClientCache_GetClientAndConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockClientCache
func (_mock *MockClientCache) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientCache_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockClientCache_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockClientCache_Expecter) Init() *MockClientCache_Init_Call {
	return &MockClientCache_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockClientCache_Init_Call) Run(run func()) *MockClientCache_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientCache_Init_Call) Return(err error) *MockClientCache_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientCache_Init_Call) RunAndReturn(run func() error) *MockClientCache_Init_Call {
	_c.Call.Return(run)
	return _c
}

// StartBackendSync provides a mock function for the type MockClientCache
func (_mock *MockClientCache) StartBackendSync(stop chan struct{}) error {
	ret := _mock.Called(stop)

	if len(ret) == 0 {
		panic("no return value specified for StartBackendSync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(chan struct{}) error); ok {
		r0 = returnFunc(stop)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientCache_StartBackendSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartBackendSync'
type MockClientCache_StartBackendSync_Call struct {
	*mock.Call
}

// StartBackendSync is a helper method to define mock.On call
//   - stop chan struct{}
func (_e *MockClientCache_Expecter) StartBackendSync(stop interface{}) *MockClientCache_StartBackendSync_Call {
	return &MockClientCache_StartBackendSync_Call{Call: _e.mock.On("StartBackendSync", stop)}
}

func (_c *MockClientCache_StartBackendSync_Call) Run(run func(stop chan struct{})) *MockClientCache_StartBackendSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan struct{}
		if args[0] != nil {
			arg0 = args[0].(chan struct{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientCache_StartBackendSync_Call) Return(err error) *MockClientCache_StartBackendSync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientCache_StartBackendSync_Call) RunAndReturn(run func(stop chan struct{}) error) *MockClientCache_StartBackendSync_Call {
	_c.Call.Return(run)
	return _c
}
