- name: prometheus-service
  run:
    when: "${CHANGE_IN(prometheus-service)}"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - cd prometheus-service
    jobs:
      - name: prometheus-service tests
        commands:
          - ../.semaphore/run-and-monitor ci.log make ci
      - name: Build binary
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../.semaphore/run-and-monitor build-$ARCH.log make build ARCH=$ARCH
