- name: Prometheus Service
  run:
    when: "${CHANGE_IN(prometheus-service)}"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - cd prometheus-service
    jobs:
      - name: "Prometheus Service: CI"
        commands:
          - ../.semaphore/run-and-monitor ci.log make ci
      - name: "Prometheus Service: build arm64"
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../.semaphore/run-and-monitor build-$ARCH.log make build ARCH=$ARCH
    epilogue:
      always:
        commands:
          - 'test-results publish ./report/*.xml --name "Prometheus service: UT" || true'
