- name: Alert Manager
  run:
    when: "${FORCE_RUN} or change_in(['/third_party/alertmanager/'], {pipeline_file: 'ignore', exclude: ['/**/.gitignore', '/**/README.md', '/**/LICENSE']${DEFAULT_BRANCH}})"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - sem-version go 1.25.6
        - cd third_party/alertmanager
    jobs:
      - name: "Alert Manager: CI"
        commands:
          - ../../.semaphore/run-and-monitor ci.log make ci
      - name: "Alert Manager: build arm64 Image"
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../../.semaphore/run-and-monitor build-$ARCH.log make image ARCH=$ARCH
