- name: Prometheus
  run:
    when: "${FORCE_RUN} or change_in(['/third_party/prometheus/'], {pipeline_file: 'ignore', exclude: ['/**/.gitignore', '/**/README.md', '/**/LICENSE']${DEFAULT_BRANCH}})"
  dependencies:
    - Prerequisites
  task:
    agent:
      machine:
        type: f1-standard-4
        os_image: ubuntu2204
    prologue:
      commands:
        - cd third_party/prometheus
    jobs:
      - name: "Prometheus: CI"
        commands:
          - ../../.semaphore/run-and-monitor ci.log make ci
      - name: "Prometheus: build arm64"
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../../.semaphore/run-and-monitor build-$ARCH.log make image ARCH=$ARCH
