- name: Prometheus Operator
  run:
    when: "${FORCE_RUN} or change_in(['/third_party/prometheus-operator/'], {pipeline_file: 'ignore', exclude: ['/**/.gitignore', '/**/README.md', '/**/LICENSE']${DEFAULT_BRANCH}})"
  dependencies:
    - Prerequisites
  task:
    prologue:
      commands:
        - cd third_party/prometheus-operator
    jobs:
      - name: "Prometheus Operator: CI"
        commands:
          - ../../.semaphore/run-and-monitor ci.log make ci
      - name: "Prometheus Operator: build arm64"
        matrix:
          - env_var: ARCH
            values:
              - arm64
        commands:
          - ../../.semaphore/run-and-monitor build-$ARCH.log make image ARCH=$ARCH
