// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package processor

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/projectcalico/calico/libcalico-go/lib/backend/model"
)

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockProcessor
func (_mock *MockProcessor) Add(ctx context.Context, wepKey model.WorkloadEndpointKey, iface string) {
	_mock.Called(ctx, wepKey, iface)
	return
}

// MockProcessor_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProcessor_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - wepKey model.WorkloadEndpointKey
//   - iface string
func (_e *MockProcessor_Expecter) Add(ctx interface{}, wepKey interface{}, iface interface{}) *MockProcessor_Add_Call {
	return &MockProcessor_Add_Call{Call: _e.mock.On("Add", ctx, wepKey, iface)}
}

func (_c *MockProcessor_Add_Call) Run(run func(ctx context.Context, wepKey model.WorkloadEndpointKey, iface string)) *MockProcessor_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.WorkloadEndpointKey
		if args[1] != nil {
			arg1 = args[1].(model.WorkloadEndpointKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessor_Add_Call) Return() *MockProcessor_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProcessor_Add_Call) RunAndReturn(run func(ctx context.Context, wepKey model.WorkloadEndpointKey, iface string)) *MockProcessor_Add_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function for the type MockProcessor
func (_mock *MockProcessor) Close() {
	_mock.Called()
	return
}

// MockProcessor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProcessor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProcessor_Expecter) Close() *MockProcessor_Close_Call {
	return &MockProcessor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProcessor_Close_Call) Run(run func()) *MockProcessor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessor_Close_Call) Return() *MockProcessor_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProcessor_Close_Call) RunAndReturn(run func()) *MockProcessor_Close_Call {
	_c.Run(run)
	return _c
}

// Remove provides a mock function for the type MockProcessor
func (_mock *MockProcessor) Remove(wepKey model.WorkloadEndpointKey) {
	_mock.Called(wepKey)
	return
}

// MockProcessor_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockProcessor_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - wepKey model.WorkloadEndpointKey
func (_e *MockProcessor_Expecter) Remove(wepKey interface{}) *MockProcessor_Remove_Call {
	return &MockProcessor_Remove_Call{Call: _e.mock.On("Remove", wepKey)}
}

func (_c *MockProcessor_Remove_Call) Run(run func(wepKey model.WorkloadEndpointKey)) *MockProcessor_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.WorkloadEndpointKey
		if args[0] != nil {
			arg0 = args[0].(model.WorkloadEndpointKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessor_Remove_Call) Return() *MockProcessor_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProcessor_Remove_Call) RunAndReturn(run func(wepKey model.WorkloadEndpointKey)) *MockProcessor_Remove_Call {
	_c.Run(run)
	return _c
}

// WEPInterfaceCount provides a mock function for the type MockProcessor
func (_mock *MockProcessor) WEPInterfaceCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WEPInterfaceCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockProcessor_WEPInterfaceCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WEPInterfaceCount'
type MockProcessor_WEPInterfaceCount_Call struct {
	*mock.Call
}

// WEPInterfaceCount is a helper method to define mock.On call
func (_e *MockProcessor_Expecter) WEPInterfaceCount() *MockProcessor_WEPInterfaceCount_Call {
	return &MockProcessor_WEPInterfaceCount_Call{Call: _e.mock.On("WEPInterfaceCount")}
}

func (_c *MockProcessor_WEPInterfaceCount_Call) Run(run func()) *MockProcessor_WEPInterfaceCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessor_WEPInterfaceCount_Call) Return(n int) *MockProcessor_WEPInterfaceCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProcessor_WEPInterfaceCount_Call) RunAndReturn(run func() int) *MockProcessor_WEPInterfaceCount_Call {
	_c.Call.Return(run)
	return _c
}
