---
# Source: tigera-prometheus-operator/templates/00-namespace-tigera-prometheus.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tigera-prometheus
  annotations:
    openshift.io/node-selector: ""
  labels:
    name: tigera-prometheus
    openshift.io/run-level: "0"

---
# Source: tigera-prometheus-operator/templates/02-serviceaccount-prometheus-operator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-prometheus-operator
  namespace: tigera-prometheus

---
# Apply an empty image pull secret (e30K={}), as MKE does not allow deployments referring non-existing pull-secrets. As
# soon as the tigera-operator comes up, it will replace this secret with the contents of the pull secret from the
# operator namespace.
apiVersion: v1
kind: Secret
metadata:
  name: tigera-pull-secret
  namespace: tigera-prometheus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K

---
# Source: tigera-prometheus-operator/templates/04-deployment-prometheus-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-prometheus-operator
  namespace: tigera-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      operator: prometheus
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: calico-prometheus-operator
      labels:
        operator: prometheus
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: calico-prometheus-operator
      imagePullSecrets:
        - name: tigera-pull-secret
      containers:
        - name: calico-prometheus-operator
          image: gcr.io/unique-caldron-775/cnx/tigera/prometheus-operator:master
          args:
            - --prometheus-config-reloader=gcr.io/unique-caldron-775/cnx/tigera/prometheus-config-reloader:master
            - --config-reloader-memory-request=50Mi
            - --namespaces=tigera-prometheus
            - --cluster-domain=cluster.local
            - --config-reloader-cpu-limit=150m
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
