package collections

var collectionDNS = Collection{
	name:                 CollectionNameDNS,
	defaultTimeFieldName: "@timestamp",
	fields: []CollectionField{
		{fieldType: FieldTypeDate, fieldName: "@timestamp"},
		{fieldType: FieldTypeIP, fieldName: "client_ip"},
		{fieldType: FieldTypeText, fieldName: "client_name"},
		{fieldType: FieldTypeText, fieldName: "client_name_aggr"},
		{fieldType: FieldTypeText, fieldName: "client_namespace"},
		{fieldType: FieldTypeNumber, fieldName: "count"},
		{fieldType: FieldTypeText, fieldName: "dns.question.class"},
		{fieldType: FieldTypeText, fieldName: "dns.question.name"},
		{fieldType: FieldTypeText, fieldName: "dns.question.registered_domain"},
		{fieldType: FieldTypeText, fieldName: "dns.question.type"},
		{fieldType: FieldTypeText, fieldName: "dns.response_code"},
		{fieldType: FieldTypeDate, fieldName: "end_time"},
		{fieldType: FieldTypeDate, fieldName: "generated_time"},
		{fieldType: FieldTypeText, fieldName: "host"},
		{fieldType: FieldTypeNumber, fieldName: "latency_count"},
		{fieldType: FieldTypeNumber, fieldName: "latency_max"},
		{fieldType: FieldTypeNumber, fieldName: "latency_mean"},
		{fieldType: FieldTypeText, fieldName: "qclass"},
		{fieldType: FieldTypeQName, fieldName: "qname", displayFieldType: FieldTypeText},
		{fieldType: FieldTypeText, fieldName: "qtype"},
		{fieldType: FieldTypeText, fieldName: "rcode"},
		{fieldType: FieldTypeRRSetsName, fieldName: "rrsets.name", displayFieldType: FieldTypeText},
		{fieldType: FieldTypeRRSetsData, fieldName: "rrsets.rdata", displayFieldType: FieldTypeText},
		{fieldType: FieldTypeIP, fieldName: "servers.ip"},
		{fieldType: FieldTypeText, fieldName: "servers.name"},
		{fieldType: FieldTypeText, fieldName: "servers.name_aggr"},
		{fieldType: FieldTypeText, fieldName: "servers.namespace"},
		{fieldType: FieldTypeIP, fieldName: "source.ip"},
		{fieldType: FieldTypeDate, fieldName: "start_time"},
		{fieldType: FieldTypeText, fieldName: "type"},
	},
}
