package collections

var collectionFlows = Collection{
	name:                 CollectionNameFlows,
	defaultTimeFieldName: "@timestamp",
	fields: []CollectionField{
		{fieldType: FieldTypeText, fieldName: "_index"},
		{fieldType: FieldTypeDate, fieldName: "@timestamp"},
		{fieldType: FieldTypeText, fieldName: "action"},
		{fieldType: FieldTypeNumber, fieldName: "bytes_in"},
		{fieldType: FieldTypeNumber, fieldName: "bytes_out"},
		{fieldType: FieldTypeText, fieldName: "dest_domains"},
		{fieldType: FieldTypeIP, fieldName: "dest_ip"},
		{fieldType: FieldTypeText, fieldName: "dest_labels.labels"},
		{fieldType: FieldTypeText, fieldName: "dest_name"},
		{fieldType: FieldTypeText, fieldName: "dest_name_aggr"},
		{fieldType: FieldTypeText, fieldName: "dest_namespace"},
		{fieldType: FieldTypeNumber, fieldName: "dest_port"},
		{fieldType: FieldTypeNumber, fieldName: "dest_port_num"},
		{fieldType: FieldTypeText, fieldName: "dest_service_name"},
		{fieldType: FieldTypeText, fieldName: "dest_service_namespace"},
		{fieldType: FieldTypeText, fieldName: "dest_service_port"},
		{fieldType: FieldTypeText, fieldName: "dest_service_port_name"},
		{fieldType: FieldTypeNumber, fieldName: "dest_service_port_num"},
		{fieldType: FieldTypeText, fieldName: "dest_type"},
		{fieldType: FieldTypeNumber, fieldName: "destination.bytes"},
		{fieldType: FieldTypeIP, fieldName: "destination.ip"},
		{fieldType: FieldTypeNumber, fieldName: "destination.packets"},
		{fieldType: FieldTypeNumber, fieldName: "destination.port"},
		{fieldType: FieldTypeDate, fieldName: "end_time"},
		{fieldType: FieldTypeText, fieldName: "event.action"},
		{fieldType: FieldTypeText, fieldName: "host"},
		{fieldType: FieldTypeNumber, fieldName: "http_requests_allowed_in"},
		{fieldType: FieldTypeNumber, fieldName: "http_requests_denied_in"},
		{fieldType: FieldTypeNumber, fieldName: "nat_outgoing_ports"},
		{fieldType: FieldTypeText, fieldName: "network.protocol"},
		{fieldType: FieldTypeNumber, fieldName: "num_flows"},
		{fieldType: FieldTypeNumber, fieldName: "num_flows_completed"},
		{fieldType: FieldTypeNumber, fieldName: "num_flows_started"},
		{fieldType: FieldTypeNumber, fieldName: "num_original_source_ips"},
		{fieldType: FieldTypeNumber, fieldName: "num_process_args"},
		{fieldType: FieldTypeNumber, fieldName: "num_process_ids"},
		{fieldType: FieldTypeNumber, fieldName: "num_process_names"},
		{fieldType: FieldTypeIP, fieldName: "original_source_ips"},
		{fieldType: FieldTypeNumber, fieldName: "packets_in"},
		{fieldType: FieldTypeNumber, fieldName: "packets_out"},
		{fieldType: FieldTypeText, fieldName: "policies.all_policies"},
		{fieldType: FieldTypeText, fieldName: "process_args"},
		{fieldType: FieldTypeText, fieldName: "process_id"},
		{fieldType: FieldTypeText, fieldName: "process_name"},
		{fieldType: FieldTypeText, fieldName: "proto"},
		{fieldType: FieldTypeText, fieldName: "reporter"},
		{fieldType: FieldTypeNumber, fieldName: "source.bytes"},
		{fieldType: FieldTypeIP, fieldName: "source.ip"},
		{fieldType: FieldTypeNumber, fieldName: "source.packets"},
		{fieldType: FieldTypeIP, fieldName: "source_ip"},
		{fieldType: FieldTypeText, fieldName: "source_labels.labels"},
		{fieldType: FieldTypeText, fieldName: "source_name"},
		{fieldType: FieldTypeText, fieldName: "source_name_aggr"},
		{fieldType: FieldTypeText, fieldName: "source_namespace"},
		{fieldType: FieldTypeNumber, fieldName: "source_port"},
		{fieldType: FieldTypeNumber, fieldName: "source_port_num"},
		{fieldType: FieldTypeText, fieldName: "source_type"},
		{fieldType: FieldTypeDate, fieldName: "start_time"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_lost_packets"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_max_min_rtt"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_max_smooth_rtt"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_mean_min_rtt"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_mean_mss"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_mean_send_congestion_window"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_mean_smooth_rtt"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_min_mss"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_min_send_congestion_window"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_total_retransmissions"},
		{fieldType: FieldTypeNumber, fieldName: "tcp_unrecovered_to"},
	},
}
