// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rbac

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/projectcalico/calico/lma/pkg/api"
)

// NewMockFlowHelper creates a new instance of MockFlowHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlowHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlowHelper {
	mock := &MockFlowHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlowHelper is an autogenerated mock type for the FlowHelper type
type MockFlowHelper struct {
	mock.Mock
}

type MockFlowHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlowHelper) EXPECT() *MockFlowHelper_Expecter {
	return &MockFlowHelper_Expecter{mock: &_m.Mock}
}

// CanListEndpoint provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListEndpoint(endpointType api.EndpointType, s string) (bool, error) {
	ret := _mock.Called(endpointType, s)

	if len(ret) == 0 {
		panic("no return value specified for CanListEndpoint")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.EndpointType, string) (bool, error)); ok {
		return returnFunc(endpointType, s)
	}
	if returnFunc, ok := ret.Get(0).(func(api.EndpointType, string) bool); ok {
		r0 = returnFunc(endpointType, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(api.EndpointType, string) error); ok {
		r1 = returnFunc(endpointType, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListEndpoint'
type MockFlowHelper_CanListEndpoint_Call struct {
	*mock.Call
}

// CanListEndpoint is a helper method to define mock.On call
//   - endpointType api.EndpointType
//   - s string
func (_e *MockFlowHelper_Expecter) CanListEndpoint(endpointType interface{}, s interface{}) *MockFlowHelper_CanListEndpoint_Call {
	return &MockFlowHelper_CanListEndpoint_Call{Call: _e.mock.On("CanListEndpoint", endpointType, s)}
}

func (_c *MockFlowHelper_CanListEndpoint_Call) Run(run func(endpointType api.EndpointType, s string)) *MockFlowHelper_CanListEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.EndpointType
		if args[0] != nil {
			arg0 = args[0].(api.EndpointType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFlowHelper_CanListEndpoint_Call) Return(b bool, err error) *MockFlowHelper_CanListEndpoint_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListEndpoint_Call) RunAndReturn(run func(endpointType api.EndpointType, s string) (bool, error)) *MockFlowHelper_CanListEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CanListGlobalNetworkSets provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListGlobalNetworkSets() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanListGlobalNetworkSets")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListGlobalNetworkSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListGlobalNetworkSets'
type MockFlowHelper_CanListGlobalNetworkSets_Call struct {
	*mock.Call
}

// CanListGlobalNetworkSets is a helper method to define mock.On call
func (_e *MockFlowHelper_Expecter) CanListGlobalNetworkSets() *MockFlowHelper_CanListGlobalNetworkSets_Call {
	return &MockFlowHelper_CanListGlobalNetworkSets_Call{Call: _e.mock.On("CanListGlobalNetworkSets")}
}

func (_c *MockFlowHelper_CanListGlobalNetworkSets_Call) Run(run func()) *MockFlowHelper_CanListGlobalNetworkSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFlowHelper_CanListGlobalNetworkSets_Call) Return(b bool, err error) *MockFlowHelper_CanListGlobalNetworkSets_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListGlobalNetworkSets_Call) RunAndReturn(run func() (bool, error)) *MockFlowHelper_CanListGlobalNetworkSets_Call {
	_c.Call.Return(run)
	return _c
}

// CanListHostEndpoints provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListHostEndpoints() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanListHostEndpoints")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListHostEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListHostEndpoints'
type MockFlowHelper_CanListHostEndpoints_Call struct {
	*mock.Call
}

// CanListHostEndpoints is a helper method to define mock.On call
func (_e *MockFlowHelper_Expecter) CanListHostEndpoints() *MockFlowHelper_CanListHostEndpoints_Call {
	return &MockFlowHelper_CanListHostEndpoints_Call{Call: _e.mock.On("CanListHostEndpoints")}
}

func (_c *MockFlowHelper_CanListHostEndpoints_Call) Run(run func()) *MockFlowHelper_CanListHostEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFlowHelper_CanListHostEndpoints_Call) Return(b bool, err error) *MockFlowHelper_CanListHostEndpoints_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListHostEndpoints_Call) RunAndReturn(run func() (bool, error)) *MockFlowHelper_CanListHostEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// CanListNetworkSets provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListNetworkSets(namespace string) (bool, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for CanListNetworkSets")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListNetworkSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListNetworkSets'
type MockFlowHelper_CanListNetworkSets_Call struct {
	*mock.Call
}

// CanListNetworkSets is a helper method to define mock.On call
//   - namespace string
func (_e *MockFlowHelper_Expecter) CanListNetworkSets(namespace interface{}) *MockFlowHelper_CanListNetworkSets_Call {
	return &MockFlowHelper_CanListNetworkSets_Call{Call: _e.mock.On("CanListNetworkSets", namespace)}
}

func (_c *MockFlowHelper_CanListNetworkSets_Call) Run(run func(namespace string)) *MockFlowHelper_CanListNetworkSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowHelper_CanListNetworkSets_Call) Return(b bool, err error) *MockFlowHelper_CanListNetworkSets_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListNetworkSets_Call) RunAndReturn(run func(namespace string) (bool, error)) *MockFlowHelper_CanListNetworkSets_Call {
	_c.Call.Return(run)
	return _c
}

// CanListPods provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListPods(namespace string) (bool, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for CanListPods")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListPods'
type MockFlowHelper_CanListPods_Call struct {
	*mock.Call
}

// CanListPods is a helper method to define mock.On call
//   - namespace string
func (_e *MockFlowHelper_Expecter) CanListPods(namespace interface{}) *MockFlowHelper_CanListPods_Call {
	return &MockFlowHelper_CanListPods_Call{Call: _e.mock.On("CanListPods", namespace)}
}

func (_c *MockFlowHelper_CanListPods_Call) Run(run func(namespace string)) *MockFlowHelper_CanListPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowHelper_CanListPods_Call) Return(b bool, err error) *MockFlowHelper_CanListPods_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListPods_Call) RunAndReturn(run func(namespace string) (bool, error)) *MockFlowHelper_CanListPods_Call {
	_c.Call.Return(run)
	return _c
}

// CanListPolicy provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) CanListPolicy(p api.PolicyHit) (bool, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for CanListPolicy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(api.PolicyHit) (bool, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func(api.PolicyHit) bool); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(api.PolicyHit) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_CanListPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanListPolicy'
type MockFlowHelper_CanListPolicy_Call struct {
	*mock.Call
}

// CanListPolicy is a helper method to define mock.On call
//   - p api.PolicyHit
func (_e *MockFlowHelper_Expecter) CanListPolicy(p interface{}) *MockFlowHelper_CanListPolicy_Call {
	return &MockFlowHelper_CanListPolicy_Call{Call: _e.mock.On("CanListPolicy", p)}
}

func (_c *MockFlowHelper_CanListPolicy_Call) Run(run func(p api.PolicyHit)) *MockFlowHelper_CanListPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 api.PolicyHit
		if args[0] != nil {
			arg0 = args[0].(api.PolicyHit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowHelper_CanListPolicy_Call) Return(b bool, err error) *MockFlowHelper_CanListPolicy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_CanListPolicy_Call) RunAndReturn(run func(p api.PolicyHit) (bool, error)) *MockFlowHelper_CanListPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// IncludeGlobalNamespace provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) IncludeGlobalNamespace() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IncludeGlobalNamespace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_IncludeGlobalNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncludeGlobalNamespace'
type MockFlowHelper_IncludeGlobalNamespace_Call struct {
	*mock.Call
}

// IncludeGlobalNamespace is a helper method to define mock.On call
func (_e *MockFlowHelper_Expecter) IncludeGlobalNamespace() *MockFlowHelper_IncludeGlobalNamespace_Call {
	return &MockFlowHelper_IncludeGlobalNamespace_Call{Call: _e.mock.On("IncludeGlobalNamespace")}
}

func (_c *MockFlowHelper_IncludeGlobalNamespace_Call) Run(run func()) *MockFlowHelper_IncludeGlobalNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFlowHelper_IncludeGlobalNamespace_Call) Return(b bool, err error) *MockFlowHelper_IncludeGlobalNamespace_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_IncludeGlobalNamespace_Call) RunAndReturn(run func() (bool, error)) *MockFlowHelper_IncludeGlobalNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// IncludeNamespace provides a mock function for the type MockFlowHelper
func (_mock *MockFlowHelper) IncludeNamespace(namespace string) (bool, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for IncludeNamespace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlowHelper_IncludeNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncludeNamespace'
type MockFlowHelper_IncludeNamespace_Call struct {
	*mock.Call
}

// IncludeNamespace is a helper method to define mock.On call
//   - namespace string
func (_e *MockFlowHelper_Expecter) IncludeNamespace(namespace interface{}) *MockFlowHelper_IncludeNamespace_Call {
	return &MockFlowHelper_IncludeNamespace_Call{Call: _e.mock.On("IncludeNamespace", namespace)}
}

func (_c *MockFlowHelper_IncludeNamespace_Call) Run(run func(namespace string)) *MockFlowHelper_IncludeNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlowHelper_IncludeNamespace_Call) Return(b bool, err error) *MockFlowHelper_IncludeNamespace_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlowHelper_IncludeNamespace_Call) RunAndReturn(run func(namespace string) (bool, error)) *MockFlowHelper_IncludeNamespace_Call {
	_c.Call.Return(run)
	return _c
}
