// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package k8s

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apiserver/pkg/authentication/user"
	"k8s.io/client-go/rest"
)

// NewMockClientSetFactory creates a new instance of MockClientSetFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientSetFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientSetFactory {
	mock := &MockClientSetFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientSetFactory is an autogenerated mock type for the ClientSetFactory type
type MockClientSetFactory struct {
	mock.Mock
}

type MockClientSetFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientSetFactory) EXPECT() *MockClientSetFactory_Expecter {
	return &MockClientSetFactory_Expecter{mock: &_m.Mock}
}

// Impersonate provides a mock function for the type MockClientSetFactory
func (_mock *MockClientSetFactory) Impersonate(user1 *user.DefaultInfo) ClientSetFactory {
	ret := _mock.Called(user1)

	if len(ret) == 0 {
		panic("no return value specified for Impersonate")
	}

	var r0 ClientSetFactory
	if returnFunc, ok := ret.Get(0).(func(*user.DefaultInfo) ClientSetFactory); ok {
		r0 = returnFunc(user1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientSetFactory)
		}
	}
	return r0
}

// MockClientSetFactory_Impersonate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Impersonate'
type MockClientSetFactory_Impersonate_Call struct {
	*mock.Call
}

// Impersonate is a helper method to define mock.On call
//   - user1 *user.DefaultInfo
func (_e *MockClientSetFactory_Expecter) Impersonate(user1 interface{}) *MockClientSetFactory_Impersonate_Call {
	return &MockClientSetFactory_Impersonate_Call{Call: _e.mock.On("Impersonate", user1)}
}

func (_c *MockClientSetFactory_Impersonate_Call) Run(run func(user1 *user.DefaultInfo)) *MockClientSetFactory_Impersonate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *user.DefaultInfo
		if args[0] != nil {
			arg0 = args[0].(*user.DefaultInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientSetFactory_Impersonate_Call) Return(clientSetFactory ClientSetFactory) *MockClientSetFactory_Impersonate_Call {
	_c.Call.Return(clientSetFactory)
	return _c
}

func (_c *MockClientSetFactory_Impersonate_Call) RunAndReturn(run func(user1 *user.DefaultInfo) ClientSetFactory) *MockClientSetFactory_Impersonate_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientSetForApplication provides a mock function for the type MockClientSetFactory
func (_mock *MockClientSetFactory) NewClientSetForApplication(cluster string) (ClientSet, error) {
	ret := _mock.Called(cluster)

	if len(ret) == 0 {
		panic("no return value specified for NewClientSetForApplication")
	}

	var r0 ClientSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (ClientSet, error)); ok {
		return returnFunc(cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(string) ClientSet); ok {
		r0 = returnFunc(cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientSetFactory_NewClientSetForApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientSetForApplication'
type MockClientSetFactory_NewClientSetForApplication_Call struct {
	*mock.Call
}

// NewClientSetForApplication is a helper method to define mock.On call
//   - cluster string
func (_e *MockClientSetFactory_Expecter) NewClientSetForApplication(cluster interface{}) *MockClientSetFactory_NewClientSetForApplication_Call {
	return &MockClientSetFactory_NewClientSetForApplication_Call{Call: _e.mock.On("NewClientSetForApplication", cluster)}
}

func (_c *MockClientSetFactory_NewClientSetForApplication_Call) Run(run func(cluster string)) *MockClientSetFactory_NewClientSetForApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientSetFactory_NewClientSetForApplication_Call) Return(clientSet ClientSet, err error) *MockClientSetFactory_NewClientSetForApplication_Call {
	_c.Call.Return(clientSet, err)
	return _c
}

func (_c *MockClientSetFactory_NewClientSetForApplication_Call) RunAndReturn(run func(cluster string) (ClientSet, error)) *MockClientSetFactory_NewClientSetForApplication_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientSetForUser provides a mock function for the type MockClientSetFactory
func (_mock *MockClientSetFactory) NewClientSetForUser(user1 user.Info, clusterID string) (ClientSet, error) {
	ret := _mock.Called(user1, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for NewClientSetForUser")
	}

	var r0 ClientSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.Info, string) (ClientSet, error)); ok {
		return returnFunc(user1, clusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(user.Info, string) ClientSet); ok {
		r0 = returnFunc(user1, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(user.Info, string) error); ok {
		r1 = returnFunc(user1, clusterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientSetFactory_NewClientSetForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientSetForUser'
type MockClientSetFactory_NewClientSetForUser_Call struct {
	*mock.Call
}

// NewClientSetForUser is a helper method to define mock.On call
//   - user1 user.Info
//   - clusterID string
func (_e *MockClientSetFactory_Expecter) NewClientSetForUser(user1 interface{}, clusterID interface{}) *MockClientSetFactory_NewClientSetForUser_Call {
	return &MockClientSetFactory_NewClientSetForUser_Call{Call: _e.mock.On("NewClientSetForUser", user1, clusterID)}
}

func (_c *MockClientSetFactory_NewClientSetForUser_Call) Run(run func(user1 user.Info, clusterID string)) *MockClientSetFactory_NewClientSetForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.Info
		if args[0] != nil {
			arg0 = args[0].(user.Info)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientSetFactory_NewClientSetForUser_Call) Return(clientSet ClientSet, err error) *MockClientSetFactory_NewClientSetForUser_Call {
	_c.Call.Return(clientSet, err)
	return _c
}

func (_c *MockClientSetFactory_NewClientSetForUser_Call) RunAndReturn(run func(user1 user.Info, clusterID string) (ClientSet, error)) *MockClientSetFactory_NewClientSetForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewRestConfigForApplication provides a mock function for the type MockClientSetFactory
func (_mock *MockClientSetFactory) NewRestConfigForApplication(clusterID string) *rest.Config {
	ret := _mock.Called(clusterID)

	if len(ret) == 0 {
		panic("no return value specified for NewRestConfigForApplication")
	}

	var r0 *rest.Config
	if returnFunc, ok := ret.Get(0).(func(string) *rest.Config); ok {
		r0 = returnFunc(clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}
	return r0
}

// MockClientSetFactory_NewRestConfigForApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRestConfigForApplication'
type MockClientSetFactory_NewRestConfigForApplication_Call struct {
	*mock.Call
}

// NewRestConfigForApplication is a helper method to define mock.On call
//   - clusterID string
func (_e *MockClientSetFactory_Expecter) NewRestConfigForApplication(clusterID interface{}) *MockClientSetFactory_NewRestConfigForApplication_Call {
	return &MockClientSetFactory_NewRestConfigForApplication_Call{Call: _e.mock.On("NewRestConfigForApplication", clusterID)}
}

func (_c *MockClientSetFactory_NewRestConfigForApplication_Call) Run(run func(clusterID string)) *MockClientSetFactory_NewRestConfigForApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientSetFactory_NewRestConfigForApplication_Call) Return(config *rest.Config) *MockClientSetFactory_NewRestConfigForApplication_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockClientSetFactory_NewRestConfigForApplication_Call) RunAndReturn(run func(clusterID string) *rest.Config) *MockClientSetFactory_NewRestConfigForApplication_Call {
	_c.Call.Return(run)
	return _c
}
