// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package k8s

import (
	mock "github.com/stretchr/testify/mock"
	v3 "github.com/tigera/api/pkg/client/clientset_generated/clientset/typed/projectcalico/v3"
	"k8s.io/client-go/discovery"
	v1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"
	"k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1"
	"k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1"
	v1alpha12 "k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1"
	v10 "k8s.io/client-go/kubernetes/typed/apps/v1"
	v1beta10 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"
	"k8s.io/client-go/kubernetes/typed/apps/v1beta2"
	v11 "k8s.io/client-go/kubernetes/typed/authentication/v1"
	v1alpha10 "k8s.io/client-go/kubernetes/typed/authentication/v1alpha1"
	v1beta11 "k8s.io/client-go/kubernetes/typed/authentication/v1beta1"
	v12 "k8s.io/client-go/kubernetes/typed/authorization/v1"
	v1beta12 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"
	v13 "k8s.io/client-go/kubernetes/typed/autoscaling/v1"
	v2 "k8s.io/client-go/kubernetes/typed/autoscaling/v2"
	"k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1"
	"k8s.io/client-go/kubernetes/typed/autoscaling/v2beta2"
	v14 "k8s.io/client-go/kubernetes/typed/batch/v1"
	v1beta13 "k8s.io/client-go/kubernetes/typed/batch/v1beta1"
	v15 "k8s.io/client-go/kubernetes/typed/certificates/v1"
	v1alpha11 "k8s.io/client-go/kubernetes/typed/certificates/v1alpha1"
	v1beta14 "k8s.io/client-go/kubernetes/typed/certificates/v1beta1"
	v16 "k8s.io/client-go/kubernetes/typed/coordination/v1"
	"k8s.io/client-go/kubernetes/typed/coordination/v1alpha2"
	v1beta15 "k8s.io/client-go/kubernetes/typed/coordination/v1beta1"
	v17 "k8s.io/client-go/kubernetes/typed/core/v1"
	v18 "k8s.io/client-go/kubernetes/typed/discovery/v1"
	v1beta16 "k8s.io/client-go/kubernetes/typed/discovery/v1beta1"
	v19 "k8s.io/client-go/kubernetes/typed/events/v1"
	v1beta17 "k8s.io/client-go/kubernetes/typed/events/v1beta1"
	v1beta18 "k8s.io/client-go/kubernetes/typed/extensions/v1beta1"
	v110 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1"
	v1beta19 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1"
	v1beta20 "k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2"
	"k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3"
	v111 "k8s.io/client-go/kubernetes/typed/networking/v1"
	v1beta110 "k8s.io/client-go/kubernetes/typed/networking/v1beta1"
	v112 "k8s.io/client-go/kubernetes/typed/node/v1"
	v1alpha13 "k8s.io/client-go/kubernetes/typed/node/v1alpha1"
	v1beta111 "k8s.io/client-go/kubernetes/typed/node/v1beta1"
	v113 "k8s.io/client-go/kubernetes/typed/policy/v1"
	v1beta112 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"
	v114 "k8s.io/client-go/kubernetes/typed/rbac/v1"
	v1alpha14 "k8s.io/client-go/kubernetes/typed/rbac/v1alpha1"
	v1beta113 "k8s.io/client-go/kubernetes/typed/rbac/v1beta1"
	v115 "k8s.io/client-go/kubernetes/typed/resource/v1"
	"k8s.io/client-go/kubernetes/typed/resource/v1alpha3"
	v1beta114 "k8s.io/client-go/kubernetes/typed/resource/v1beta1"
	v1beta21 "k8s.io/client-go/kubernetes/typed/resource/v1beta2"
	v116 "k8s.io/client-go/kubernetes/typed/scheduling/v1"
	v1alpha15 "k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1"
	v1beta115 "k8s.io/client-go/kubernetes/typed/scheduling/v1beta1"
	v117 "k8s.io/client-go/kubernetes/typed/storage/v1"
	v1alpha16 "k8s.io/client-go/kubernetes/typed/storage/v1alpha1"
	v1beta116 "k8s.io/client-go/kubernetes/typed/storage/v1beta1"
	v1beta117 "k8s.io/client-go/kubernetes/typed/storagemigration/v1beta1"
)

// NewMockClientSet creates a new instance of MockClientSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientSet {
	mock := &MockClientSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientSet is an autogenerated mock type for the ClientSet type
type MockClientSet struct {
	mock.Mock
}

type MockClientSet_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientSet) EXPECT() *MockClientSet_Expecter {
	return &MockClientSet_Expecter{mock: &_m.Mock}
}

// AdmissionregistrationV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AdmissionregistrationV1() v1.AdmissionregistrationV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1")
	}

	var r0 v1.AdmissionregistrationV1Interface
	if returnFunc, ok := ret.Get(0).(func() v1.AdmissionregistrationV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.AdmissionregistrationV1Interface)
		}
	}
	return r0
}

// MockClientSet_AdmissionregistrationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1'
type MockClientSet_AdmissionregistrationV1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AdmissionregistrationV1() *MockClientSet_AdmissionregistrationV1_Call {
	return &MockClientSet_AdmissionregistrationV1_Call{Call: _e.mock.On("AdmissionregistrationV1")}
}

func (_c *MockClientSet_AdmissionregistrationV1_Call) Run(run func()) *MockClientSet_AdmissionregistrationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1_Call) Return(admissionregistrationV1Interface v1.AdmissionregistrationV1Interface) *MockClientSet_AdmissionregistrationV1_Call {
	_c.Call.Return(admissionregistrationV1Interface)
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1_Call) RunAndReturn(run func() v1.AdmissionregistrationV1Interface) *MockClientSet_AdmissionregistrationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AdmissionregistrationV1alpha1() v1alpha1.AdmissionregistrationV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1alpha1")
	}

	var r0 v1alpha1.AdmissionregistrationV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha1.AdmissionregistrationV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.AdmissionregistrationV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_AdmissionregistrationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1alpha1'
type MockClientSet_AdmissionregistrationV1alpha1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AdmissionregistrationV1alpha1() *MockClientSet_AdmissionregistrationV1alpha1_Call {
	return &MockClientSet_AdmissionregistrationV1alpha1_Call{Call: _e.mock.On("AdmissionregistrationV1alpha1")}
}

func (_c *MockClientSet_AdmissionregistrationV1alpha1_Call) Run(run func()) *MockClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1alpha1_Call) Return(admissionregistrationV1alpha1Interface v1alpha1.AdmissionregistrationV1alpha1Interface) *MockClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(admissionregistrationV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1alpha1_Call) RunAndReturn(run func() v1alpha1.AdmissionregistrationV1alpha1Interface) *MockClientSet_AdmissionregistrationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AdmissionregistrationV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AdmissionregistrationV1beta1() v1beta1.AdmissionregistrationV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AdmissionregistrationV1beta1")
	}

	var r0 v1beta1.AdmissionregistrationV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta1.AdmissionregistrationV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.AdmissionregistrationV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_AdmissionregistrationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdmissionregistrationV1beta1'
type MockClientSet_AdmissionregistrationV1beta1_Call struct {
	*mock.Call
}

// AdmissionregistrationV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AdmissionregistrationV1beta1() *MockClientSet_AdmissionregistrationV1beta1_Call {
	return &MockClientSet_AdmissionregistrationV1beta1_Call{Call: _e.mock.On("AdmissionregistrationV1beta1")}
}

func (_c *MockClientSet_AdmissionregistrationV1beta1_Call) Run(run func()) *MockClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1beta1_Call) Return(admissionregistrationV1beta1Interface v1beta1.AdmissionregistrationV1beta1Interface) *MockClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(admissionregistrationV1beta1Interface)
	return _c
}

func (_c *MockClientSet_AdmissionregistrationV1beta1_Call) RunAndReturn(run func() v1beta1.AdmissionregistrationV1beta1Interface) *MockClientSet_AdmissionregistrationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AppsV1() v10.AppsV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1")
	}

	var r0 v10.AppsV1Interface
	if returnFunc, ok := ret.Get(0).(func() v10.AppsV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v10.AppsV1Interface)
		}
	}
	return r0
}

// MockClientSet_AppsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1'
type MockClientSet_AppsV1_Call struct {
	*mock.Call
}

// AppsV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AppsV1() *MockClientSet_AppsV1_Call {
	return &MockClientSet_AppsV1_Call{Call: _e.mock.On("AppsV1")}
}

func (_c *MockClientSet_AppsV1_Call) Run(run func()) *MockClientSet_AppsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AppsV1_Call) Return(appsV1Interface v10.AppsV1Interface) *MockClientSet_AppsV1_Call {
	_c.Call.Return(appsV1Interface)
	return _c
}

func (_c *MockClientSet_AppsV1_Call) RunAndReturn(run func() v10.AppsV1Interface) *MockClientSet_AppsV1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AppsV1beta1() v1beta10.AppsV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1beta1")
	}

	var r0 v1beta10.AppsV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta10.AppsV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta10.AppsV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_AppsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta1'
type MockClientSet_AppsV1beta1_Call struct {
	*mock.Call
}

// AppsV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AppsV1beta1() *MockClientSet_AppsV1beta1_Call {
	return &MockClientSet_AppsV1beta1_Call{Call: _e.mock.On("AppsV1beta1")}
}

func (_c *MockClientSet_AppsV1beta1_Call) Run(run func()) *MockClientSet_AppsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AppsV1beta1_Call) Return(appsV1beta1Interface v1beta10.AppsV1beta1Interface) *MockClientSet_AppsV1beta1_Call {
	_c.Call.Return(appsV1beta1Interface)
	return _c
}

func (_c *MockClientSet_AppsV1beta1_Call) RunAndReturn(run func() v1beta10.AppsV1beta1Interface) *MockClientSet_AppsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AppsV1beta2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AppsV1beta2() v1beta2.AppsV1beta2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppsV1beta2")
	}

	var r0 v1beta2.AppsV1beta2Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta2.AppsV1beta2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta2.AppsV1beta2Interface)
		}
	}
	return r0
}

// MockClientSet_AppsV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppsV1beta2'
type MockClientSet_AppsV1beta2_Call struct {
	*mock.Call
}

// AppsV1beta2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AppsV1beta2() *MockClientSet_AppsV1beta2_Call {
	return &MockClientSet_AppsV1beta2_Call{Call: _e.mock.On("AppsV1beta2")}
}

func (_c *MockClientSet_AppsV1beta2_Call) Run(run func()) *MockClientSet_AppsV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AppsV1beta2_Call) Return(appsV1beta2Interface v1beta2.AppsV1beta2Interface) *MockClientSet_AppsV1beta2_Call {
	_c.Call.Return(appsV1beta2Interface)
	return _c
}

func (_c *MockClientSet_AppsV1beta2_Call) RunAndReturn(run func() v1beta2.AppsV1beta2Interface) *MockClientSet_AppsV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AuthenticationV1() v11.AuthenticationV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1")
	}

	var r0 v11.AuthenticationV1Interface
	if returnFunc, ok := ret.Get(0).(func() v11.AuthenticationV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v11.AuthenticationV1Interface)
		}
	}
	return r0
}

// MockClientSet_AuthenticationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1'
type MockClientSet_AuthenticationV1_Call struct {
	*mock.Call
}

// AuthenticationV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AuthenticationV1() *MockClientSet_AuthenticationV1_Call {
	return &MockClientSet_AuthenticationV1_Call{Call: _e.mock.On("AuthenticationV1")}
}

func (_c *MockClientSet_AuthenticationV1_Call) Run(run func()) *MockClientSet_AuthenticationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AuthenticationV1_Call) Return(authenticationV1Interface v11.AuthenticationV1Interface) *MockClientSet_AuthenticationV1_Call {
	_c.Call.Return(authenticationV1Interface)
	return _c
}

func (_c *MockClientSet_AuthenticationV1_Call) RunAndReturn(run func() v11.AuthenticationV1Interface) *MockClientSet_AuthenticationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AuthenticationV1alpha1() v1alpha10.AuthenticationV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1alpha1")
	}

	var r0 v1alpha10.AuthenticationV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha10.AuthenticationV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha10.AuthenticationV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_AuthenticationV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1alpha1'
type MockClientSet_AuthenticationV1alpha1_Call struct {
	*mock.Call
}

// AuthenticationV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AuthenticationV1alpha1() *MockClientSet_AuthenticationV1alpha1_Call {
	return &MockClientSet_AuthenticationV1alpha1_Call{Call: _e.mock.On("AuthenticationV1alpha1")}
}

func (_c *MockClientSet_AuthenticationV1alpha1_Call) Run(run func()) *MockClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AuthenticationV1alpha1_Call) Return(authenticationV1alpha1Interface v1alpha10.AuthenticationV1alpha1Interface) *MockClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Return(authenticationV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_AuthenticationV1alpha1_Call) RunAndReturn(run func() v1alpha10.AuthenticationV1alpha1Interface) *MockClientSet_AuthenticationV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticationV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AuthenticationV1beta1() v1beta11.AuthenticationV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticationV1beta1")
	}

	var r0 v1beta11.AuthenticationV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta11.AuthenticationV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta11.AuthenticationV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_AuthenticationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticationV1beta1'
type MockClientSet_AuthenticationV1beta1_Call struct {
	*mock.Call
}

// AuthenticationV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AuthenticationV1beta1() *MockClientSet_AuthenticationV1beta1_Call {
	return &MockClientSet_AuthenticationV1beta1_Call{Call: _e.mock.On("AuthenticationV1beta1")}
}

func (_c *MockClientSet_AuthenticationV1beta1_Call) Run(run func()) *MockClientSet_AuthenticationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AuthenticationV1beta1_Call) Return(authenticationV1beta1Interface v1beta11.AuthenticationV1beta1Interface) *MockClientSet_AuthenticationV1beta1_Call {
	_c.Call.Return(authenticationV1beta1Interface)
	return _c
}

func (_c *MockClientSet_AuthenticationV1beta1_Call) RunAndReturn(run func() v1beta11.AuthenticationV1beta1Interface) *MockClientSet_AuthenticationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AuthorizationV1() v12.AuthorizationV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthorizationV1")
	}

	var r0 v12.AuthorizationV1Interface
	if returnFunc, ok := ret.Get(0).(func() v12.AuthorizationV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v12.AuthorizationV1Interface)
		}
	}
	return r0
}

// MockClientSet_AuthorizationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1'
type MockClientSet_AuthorizationV1_Call struct {
	*mock.Call
}

// AuthorizationV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AuthorizationV1() *MockClientSet_AuthorizationV1_Call {
	return &MockClientSet_AuthorizationV1_Call{Call: _e.mock.On("AuthorizationV1")}
}

func (_c *MockClientSet_AuthorizationV1_Call) Run(run func()) *MockClientSet_AuthorizationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AuthorizationV1_Call) Return(authorizationV1Interface v12.AuthorizationV1Interface) *MockClientSet_AuthorizationV1_Call {
	_c.Call.Return(authorizationV1Interface)
	return _c
}

func (_c *MockClientSet_AuthorizationV1_Call) RunAndReturn(run func() v12.AuthorizationV1Interface) *MockClientSet_AuthorizationV1_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizationV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AuthorizationV1beta1() v1beta12.AuthorizationV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthorizationV1beta1")
	}

	var r0 v1beta12.AuthorizationV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta12.AuthorizationV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta12.AuthorizationV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_AuthorizationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizationV1beta1'
type MockClientSet_AuthorizationV1beta1_Call struct {
	*mock.Call
}

// AuthorizationV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AuthorizationV1beta1() *MockClientSet_AuthorizationV1beta1_Call {
	return &MockClientSet_AuthorizationV1beta1_Call{Call: _e.mock.On("AuthorizationV1beta1")}
}

func (_c *MockClientSet_AuthorizationV1beta1_Call) Run(run func()) *MockClientSet_AuthorizationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AuthorizationV1beta1_Call) Return(authorizationV1beta1Interface v1beta12.AuthorizationV1beta1Interface) *MockClientSet_AuthorizationV1beta1_Call {
	_c.Call.Return(authorizationV1beta1Interface)
	return _c
}

func (_c *MockClientSet_AuthorizationV1beta1_Call) RunAndReturn(run func() v1beta12.AuthorizationV1beta1Interface) *MockClientSet_AuthorizationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AutoscalingV1() v13.AutoscalingV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV1")
	}

	var r0 v13.AutoscalingV1Interface
	if returnFunc, ok := ret.Get(0).(func() v13.AutoscalingV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v13.AutoscalingV1Interface)
		}
	}
	return r0
}

// MockClientSet_AutoscalingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV1'
type MockClientSet_AutoscalingV1_Call struct {
	*mock.Call
}

// AutoscalingV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AutoscalingV1() *MockClientSet_AutoscalingV1_Call {
	return &MockClientSet_AutoscalingV1_Call{Call: _e.mock.On("AutoscalingV1")}
}

func (_c *MockClientSet_AutoscalingV1_Call) Run(run func()) *MockClientSet_AutoscalingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AutoscalingV1_Call) Return(autoscalingV1Interface v13.AutoscalingV1Interface) *MockClientSet_AutoscalingV1_Call {
	_c.Call.Return(autoscalingV1Interface)
	return _c
}

func (_c *MockClientSet_AutoscalingV1_Call) RunAndReturn(run func() v13.AutoscalingV1Interface) *MockClientSet_AutoscalingV1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AutoscalingV2() v2.AutoscalingV2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2")
	}

	var r0 v2.AutoscalingV2Interface
	if returnFunc, ok := ret.Get(0).(func() v2.AutoscalingV2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2.AutoscalingV2Interface)
		}
	}
	return r0
}

// MockClientSet_AutoscalingV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2'
type MockClientSet_AutoscalingV2_Call struct {
	*mock.Call
}

// AutoscalingV2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AutoscalingV2() *MockClientSet_AutoscalingV2_Call {
	return &MockClientSet_AutoscalingV2_Call{Call: _e.mock.On("AutoscalingV2")}
}

func (_c *MockClientSet_AutoscalingV2_Call) Run(run func()) *MockClientSet_AutoscalingV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AutoscalingV2_Call) Return(autoscalingV2Interface v2.AutoscalingV2Interface) *MockClientSet_AutoscalingV2_Call {
	_c.Call.Return(autoscalingV2Interface)
	return _c
}

func (_c *MockClientSet_AutoscalingV2_Call) RunAndReturn(run func() v2.AutoscalingV2Interface) *MockClientSet_AutoscalingV2_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AutoscalingV2beta1() v2beta1.AutoscalingV2beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2beta1")
	}

	var r0 v2beta1.AutoscalingV2beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v2beta1.AutoscalingV2beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta1.AutoscalingV2beta1Interface)
		}
	}
	return r0
}

// MockClientSet_AutoscalingV2beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta1'
type MockClientSet_AutoscalingV2beta1_Call struct {
	*mock.Call
}

// AutoscalingV2beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AutoscalingV2beta1() *MockClientSet_AutoscalingV2beta1_Call {
	return &MockClientSet_AutoscalingV2beta1_Call{Call: _e.mock.On("AutoscalingV2beta1")}
}

func (_c *MockClientSet_AutoscalingV2beta1_Call) Run(run func()) *MockClientSet_AutoscalingV2beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AutoscalingV2beta1_Call) Return(autoscalingV2beta1Interface v2beta1.AutoscalingV2beta1Interface) *MockClientSet_AutoscalingV2beta1_Call {
	_c.Call.Return(autoscalingV2beta1Interface)
	return _c
}

func (_c *MockClientSet_AutoscalingV2beta1_Call) RunAndReturn(run func() v2beta1.AutoscalingV2beta1Interface) *MockClientSet_AutoscalingV2beta1_Call {
	_c.Call.Return(run)
	return _c
}

// AutoscalingV2beta2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) AutoscalingV2beta2() v2beta2.AutoscalingV2beta2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoscalingV2beta2")
	}

	var r0 v2beta2.AutoscalingV2beta2Interface
	if returnFunc, ok := ret.Get(0).(func() v2beta2.AutoscalingV2beta2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v2beta2.AutoscalingV2beta2Interface)
		}
	}
	return r0
}

// MockClientSet_AutoscalingV2beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoscalingV2beta2'
type MockClientSet_AutoscalingV2beta2_Call struct {
	*mock.Call
}

// AutoscalingV2beta2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) AutoscalingV2beta2() *MockClientSet_AutoscalingV2beta2_Call {
	return &MockClientSet_AutoscalingV2beta2_Call{Call: _e.mock.On("AutoscalingV2beta2")}
}

func (_c *MockClientSet_AutoscalingV2beta2_Call) Run(run func()) *MockClientSet_AutoscalingV2beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_AutoscalingV2beta2_Call) Return(autoscalingV2beta2Interface v2beta2.AutoscalingV2beta2Interface) *MockClientSet_AutoscalingV2beta2_Call {
	_c.Call.Return(autoscalingV2beta2Interface)
	return _c
}

func (_c *MockClientSet_AutoscalingV2beta2_Call) RunAndReturn(run func() v2beta2.AutoscalingV2beta2Interface) *MockClientSet_AutoscalingV2beta2_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) BatchV1() v14.BatchV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchV1")
	}

	var r0 v14.BatchV1Interface
	if returnFunc, ok := ret.Get(0).(func() v14.BatchV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v14.BatchV1Interface)
		}
	}
	return r0
}

// MockClientSet_BatchV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1'
type MockClientSet_BatchV1_Call struct {
	*mock.Call
}

// BatchV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) BatchV1() *MockClientSet_BatchV1_Call {
	return &MockClientSet_BatchV1_Call{Call: _e.mock.On("BatchV1")}
}

func (_c *MockClientSet_BatchV1_Call) Run(run func()) *MockClientSet_BatchV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_BatchV1_Call) Return(batchV1Interface v14.BatchV1Interface) *MockClientSet_BatchV1_Call {
	_c.Call.Return(batchV1Interface)
	return _c
}

func (_c *MockClientSet_BatchV1_Call) RunAndReturn(run func() v14.BatchV1Interface) *MockClientSet_BatchV1_Call {
	_c.Call.Return(run)
	return _c
}

// BatchV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) BatchV1beta1() v1beta13.BatchV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchV1beta1")
	}

	var r0 v1beta13.BatchV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta13.BatchV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta13.BatchV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_BatchV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchV1beta1'
type MockClientSet_BatchV1beta1_Call struct {
	*mock.Call
}

// BatchV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) BatchV1beta1() *MockClientSet_BatchV1beta1_Call {
	return &MockClientSet_BatchV1beta1_Call{Call: _e.mock.On("BatchV1beta1")}
}

func (_c *MockClientSet_BatchV1beta1_Call) Run(run func()) *MockClientSet_BatchV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_BatchV1beta1_Call) Return(batchV1beta1Interface v1beta13.BatchV1beta1Interface) *MockClientSet_BatchV1beta1_Call {
	_c.Call.Return(batchV1beta1Interface)
	return _c
}

func (_c *MockClientSet_BatchV1beta1_Call) RunAndReturn(run func() v1beta13.BatchV1beta1Interface) *MockClientSet_BatchV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CertificatesV1() v15.CertificatesV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1")
	}

	var r0 v15.CertificatesV1Interface
	if returnFunc, ok := ret.Get(0).(func() v15.CertificatesV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v15.CertificatesV1Interface)
		}
	}
	return r0
}

// MockClientSet_CertificatesV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1'
type MockClientSet_CertificatesV1_Call struct {
	*mock.Call
}

// CertificatesV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CertificatesV1() *MockClientSet_CertificatesV1_Call {
	return &MockClientSet_CertificatesV1_Call{Call: _e.mock.On("CertificatesV1")}
}

func (_c *MockClientSet_CertificatesV1_Call) Run(run func()) *MockClientSet_CertificatesV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CertificatesV1_Call) Return(certificatesV1Interface v15.CertificatesV1Interface) *MockClientSet_CertificatesV1_Call {
	_c.Call.Return(certificatesV1Interface)
	return _c
}

func (_c *MockClientSet_CertificatesV1_Call) RunAndReturn(run func() v15.CertificatesV1Interface) *MockClientSet_CertificatesV1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CertificatesV1alpha1() v1alpha11.CertificatesV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1alpha1")
	}

	var r0 v1alpha11.CertificatesV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha11.CertificatesV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha11.CertificatesV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_CertificatesV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1alpha1'
type MockClientSet_CertificatesV1alpha1_Call struct {
	*mock.Call
}

// CertificatesV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CertificatesV1alpha1() *MockClientSet_CertificatesV1alpha1_Call {
	return &MockClientSet_CertificatesV1alpha1_Call{Call: _e.mock.On("CertificatesV1alpha1")}
}

func (_c *MockClientSet_CertificatesV1alpha1_Call) Run(run func()) *MockClientSet_CertificatesV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CertificatesV1alpha1_Call) Return(certificatesV1alpha1Interface v1alpha11.CertificatesV1alpha1Interface) *MockClientSet_CertificatesV1alpha1_Call {
	_c.Call.Return(certificatesV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_CertificatesV1alpha1_Call) RunAndReturn(run func() v1alpha11.CertificatesV1alpha1Interface) *MockClientSet_CertificatesV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// CertificatesV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CertificatesV1beta1() v1beta14.CertificatesV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificatesV1beta1")
	}

	var r0 v1beta14.CertificatesV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta14.CertificatesV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta14.CertificatesV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_CertificatesV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificatesV1beta1'
type MockClientSet_CertificatesV1beta1_Call struct {
	*mock.Call
}

// CertificatesV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CertificatesV1beta1() *MockClientSet_CertificatesV1beta1_Call {
	return &MockClientSet_CertificatesV1beta1_Call{Call: _e.mock.On("CertificatesV1beta1")}
}

func (_c *MockClientSet_CertificatesV1beta1_Call) Run(run func()) *MockClientSet_CertificatesV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CertificatesV1beta1_Call) Return(certificatesV1beta1Interface v1beta14.CertificatesV1beta1Interface) *MockClientSet_CertificatesV1beta1_Call {
	_c.Call.Return(certificatesV1beta1Interface)
	return _c
}

func (_c *MockClientSet_CertificatesV1beta1_Call) RunAndReturn(run func() v1beta14.CertificatesV1beta1Interface) *MockClientSet_CertificatesV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CoordinationV1() v16.CoordinationV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1")
	}

	var r0 v16.CoordinationV1Interface
	if returnFunc, ok := ret.Get(0).(func() v16.CoordinationV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v16.CoordinationV1Interface)
		}
	}
	return r0
}

// MockClientSet_CoordinationV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1'
type MockClientSet_CoordinationV1_Call struct {
	*mock.Call
}

// CoordinationV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CoordinationV1() *MockClientSet_CoordinationV1_Call {
	return &MockClientSet_CoordinationV1_Call{Call: _e.mock.On("CoordinationV1")}
}

func (_c *MockClientSet_CoordinationV1_Call) Run(run func()) *MockClientSet_CoordinationV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CoordinationV1_Call) Return(coordinationV1Interface v16.CoordinationV1Interface) *MockClientSet_CoordinationV1_Call {
	_c.Call.Return(coordinationV1Interface)
	return _c
}

func (_c *MockClientSet_CoordinationV1_Call) RunAndReturn(run func() v16.CoordinationV1Interface) *MockClientSet_CoordinationV1_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1alpha2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CoordinationV1alpha2() v1alpha2.CoordinationV1alpha2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1alpha2")
	}

	var r0 v1alpha2.CoordinationV1alpha2Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha2.CoordinationV1alpha2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha2.CoordinationV1alpha2Interface)
		}
	}
	return r0
}

// MockClientSet_CoordinationV1alpha2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1alpha2'
type MockClientSet_CoordinationV1alpha2_Call struct {
	*mock.Call
}

// CoordinationV1alpha2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CoordinationV1alpha2() *MockClientSet_CoordinationV1alpha2_Call {
	return &MockClientSet_CoordinationV1alpha2_Call{Call: _e.mock.On("CoordinationV1alpha2")}
}

func (_c *MockClientSet_CoordinationV1alpha2_Call) Run(run func()) *MockClientSet_CoordinationV1alpha2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CoordinationV1alpha2_Call) Return(coordinationV1alpha2Interface v1alpha2.CoordinationV1alpha2Interface) *MockClientSet_CoordinationV1alpha2_Call {
	_c.Call.Return(coordinationV1alpha2Interface)
	return _c
}

func (_c *MockClientSet_CoordinationV1alpha2_Call) RunAndReturn(run func() v1alpha2.CoordinationV1alpha2Interface) *MockClientSet_CoordinationV1alpha2_Call {
	_c.Call.Return(run)
	return _c
}

// CoordinationV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CoordinationV1beta1() v1beta15.CoordinationV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoordinationV1beta1")
	}

	var r0 v1beta15.CoordinationV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta15.CoordinationV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta15.CoordinationV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_CoordinationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoordinationV1beta1'
type MockClientSet_CoordinationV1beta1_Call struct {
	*mock.Call
}

// CoordinationV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CoordinationV1beta1() *MockClientSet_CoordinationV1beta1_Call {
	return &MockClientSet_CoordinationV1beta1_Call{Call: _e.mock.On("CoordinationV1beta1")}
}

func (_c *MockClientSet_CoordinationV1beta1_Call) Run(run func()) *MockClientSet_CoordinationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CoordinationV1beta1_Call) Return(coordinationV1beta1Interface v1beta15.CoordinationV1beta1Interface) *MockClientSet_CoordinationV1beta1_Call {
	_c.Call.Return(coordinationV1beta1Interface)
	return _c
}

func (_c *MockClientSet_CoordinationV1beta1_Call) RunAndReturn(run func() v1beta15.CoordinationV1beta1Interface) *MockClientSet_CoordinationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// CoreV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) CoreV1() v17.CoreV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CoreV1")
	}

	var r0 v17.CoreV1Interface
	if returnFunc, ok := ret.Get(0).(func() v17.CoreV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v17.CoreV1Interface)
		}
	}
	return r0
}

// MockClientSet_CoreV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CoreV1'
type MockClientSet_CoreV1_Call struct {
	*mock.Call
}

// CoreV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) CoreV1() *MockClientSet_CoreV1_Call {
	return &MockClientSet_CoreV1_Call{Call: _e.mock.On("CoreV1")}
}

func (_c *MockClientSet_CoreV1_Call) Run(run func()) *MockClientSet_CoreV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_CoreV1_Call) Return(coreV1Interface v17.CoreV1Interface) *MockClientSet_CoreV1_Call {
	_c.Call.Return(coreV1Interface)
	return _c
}

func (_c *MockClientSet_CoreV1_Call) RunAndReturn(run func() v17.CoreV1Interface) *MockClientSet_CoreV1_Call {
	_c.Call.Return(run)
	return _c
}

// Discovery provides a mock function for the type MockClientSet
func (_mock *MockClientSet) Discovery() discovery.DiscoveryInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Discovery")
	}

	var r0 discovery.DiscoveryInterface
	if returnFunc, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}
	return r0
}

// MockClientSet_Discovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discovery'
type MockClientSet_Discovery_Call struct {
	*mock.Call
}

// Discovery is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) Discovery() *MockClientSet_Discovery_Call {
	return &MockClientSet_Discovery_Call{Call: _e.mock.On("Discovery")}
}

func (_c *MockClientSet_Discovery_Call) Run(run func()) *MockClientSet_Discovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_Discovery_Call) Return(discoveryInterface discovery.DiscoveryInterface) *MockClientSet_Discovery_Call {
	_c.Call.Return(discoveryInterface)
	return _c
}

func (_c *MockClientSet_Discovery_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *MockClientSet_Discovery_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) DiscoveryV1() v18.DiscoveryV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveryV1")
	}

	var r0 v18.DiscoveryV1Interface
	if returnFunc, ok := ret.Get(0).(func() v18.DiscoveryV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v18.DiscoveryV1Interface)
		}
	}
	return r0
}

// MockClientSet_DiscoveryV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1'
type MockClientSet_DiscoveryV1_Call struct {
	*mock.Call
}

// DiscoveryV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) DiscoveryV1() *MockClientSet_DiscoveryV1_Call {
	return &MockClientSet_DiscoveryV1_Call{Call: _e.mock.On("DiscoveryV1")}
}

func (_c *MockClientSet_DiscoveryV1_Call) Run(run func()) *MockClientSet_DiscoveryV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_DiscoveryV1_Call) Return(discoveryV1Interface v18.DiscoveryV1Interface) *MockClientSet_DiscoveryV1_Call {
	_c.Call.Return(discoveryV1Interface)
	return _c
}

func (_c *MockClientSet_DiscoveryV1_Call) RunAndReturn(run func() v18.DiscoveryV1Interface) *MockClientSet_DiscoveryV1_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoveryV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) DiscoveryV1beta1() v1beta16.DiscoveryV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoveryV1beta1")
	}

	var r0 v1beta16.DiscoveryV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta16.DiscoveryV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta16.DiscoveryV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_DiscoveryV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoveryV1beta1'
type MockClientSet_DiscoveryV1beta1_Call struct {
	*mock.Call
}

// DiscoveryV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) DiscoveryV1beta1() *MockClientSet_DiscoveryV1beta1_Call {
	return &MockClientSet_DiscoveryV1beta1_Call{Call: _e.mock.On("DiscoveryV1beta1")}
}

func (_c *MockClientSet_DiscoveryV1beta1_Call) Run(run func()) *MockClientSet_DiscoveryV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_DiscoveryV1beta1_Call) Return(discoveryV1beta1Interface v1beta16.DiscoveryV1beta1Interface) *MockClientSet_DiscoveryV1beta1_Call {
	_c.Call.Return(discoveryV1beta1Interface)
	return _c
}

func (_c *MockClientSet_DiscoveryV1beta1_Call) RunAndReturn(run func() v1beta16.DiscoveryV1beta1Interface) *MockClientSet_DiscoveryV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) EventsV1() v19.EventsV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventsV1")
	}

	var r0 v19.EventsV1Interface
	if returnFunc, ok := ret.Get(0).(func() v19.EventsV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v19.EventsV1Interface)
		}
	}
	return r0
}

// MockClientSet_EventsV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1'
type MockClientSet_EventsV1_Call struct {
	*mock.Call
}

// EventsV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) EventsV1() *MockClientSet_EventsV1_Call {
	return &MockClientSet_EventsV1_Call{Call: _e.mock.On("EventsV1")}
}

func (_c *MockClientSet_EventsV1_Call) Run(run func()) *MockClientSet_EventsV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_EventsV1_Call) Return(eventsV1Interface v19.EventsV1Interface) *MockClientSet_EventsV1_Call {
	_c.Call.Return(eventsV1Interface)
	return _c
}

func (_c *MockClientSet_EventsV1_Call) RunAndReturn(run func() v19.EventsV1Interface) *MockClientSet_EventsV1_Call {
	_c.Call.Return(run)
	return _c
}

// EventsV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) EventsV1beta1() v1beta17.EventsV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventsV1beta1")
	}

	var r0 v1beta17.EventsV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta17.EventsV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta17.EventsV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_EventsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsV1beta1'
type MockClientSet_EventsV1beta1_Call struct {
	*mock.Call
}

// EventsV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) EventsV1beta1() *MockClientSet_EventsV1beta1_Call {
	return &MockClientSet_EventsV1beta1_Call{Call: _e.mock.On("EventsV1beta1")}
}

func (_c *MockClientSet_EventsV1beta1_Call) Run(run func()) *MockClientSet_EventsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_EventsV1beta1_Call) Return(eventsV1beta1Interface v1beta17.EventsV1beta1Interface) *MockClientSet_EventsV1beta1_Call {
	_c.Call.Return(eventsV1beta1Interface)
	return _c
}

func (_c *MockClientSet_EventsV1beta1_Call) RunAndReturn(run func() v1beta17.EventsV1beta1Interface) *MockClientSet_EventsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ExtensionsV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ExtensionsV1beta1() v1beta18.ExtensionsV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtensionsV1beta1")
	}

	var r0 v1beta18.ExtensionsV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta18.ExtensionsV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta18.ExtensionsV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_ExtensionsV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtensionsV1beta1'
type MockClientSet_ExtensionsV1beta1_Call struct {
	*mock.Call
}

// ExtensionsV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ExtensionsV1beta1() *MockClientSet_ExtensionsV1beta1_Call {
	return &MockClientSet_ExtensionsV1beta1_Call{Call: _e.mock.On("ExtensionsV1beta1")}
}

func (_c *MockClientSet_ExtensionsV1beta1_Call) Run(run func()) *MockClientSet_ExtensionsV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ExtensionsV1beta1_Call) Return(extensionsV1beta1Interface v1beta18.ExtensionsV1beta1Interface) *MockClientSet_ExtensionsV1beta1_Call {
	_c.Call.Return(extensionsV1beta1Interface)
	return _c
}

func (_c *MockClientSet_ExtensionsV1beta1_Call) RunAndReturn(run func() v1beta18.ExtensionsV1beta1Interface) *MockClientSet_ExtensionsV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) FlowcontrolV1() v110.FlowcontrolV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1")
	}

	var r0 v110.FlowcontrolV1Interface
	if returnFunc, ok := ret.Get(0).(func() v110.FlowcontrolV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v110.FlowcontrolV1Interface)
		}
	}
	return r0
}

// MockClientSet_FlowcontrolV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1'
type MockClientSet_FlowcontrolV1_Call struct {
	*mock.Call
}

// FlowcontrolV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) FlowcontrolV1() *MockClientSet_FlowcontrolV1_Call {
	return &MockClientSet_FlowcontrolV1_Call{Call: _e.mock.On("FlowcontrolV1")}
}

func (_c *MockClientSet_FlowcontrolV1_Call) Run(run func()) *MockClientSet_FlowcontrolV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_FlowcontrolV1_Call) Return(flowcontrolV1Interface v110.FlowcontrolV1Interface) *MockClientSet_FlowcontrolV1_Call {
	_c.Call.Return(flowcontrolV1Interface)
	return _c
}

func (_c *MockClientSet_FlowcontrolV1_Call) RunAndReturn(run func() v110.FlowcontrolV1Interface) *MockClientSet_FlowcontrolV1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) FlowcontrolV1beta1() v1beta19.FlowcontrolV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta1")
	}

	var r0 v1beta19.FlowcontrolV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta19.FlowcontrolV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta19.FlowcontrolV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_FlowcontrolV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta1'
type MockClientSet_FlowcontrolV1beta1_Call struct {
	*mock.Call
}

// FlowcontrolV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) FlowcontrolV1beta1() *MockClientSet_FlowcontrolV1beta1_Call {
	return &MockClientSet_FlowcontrolV1beta1_Call{Call: _e.mock.On("FlowcontrolV1beta1")}
}

func (_c *MockClientSet_FlowcontrolV1beta1_Call) Run(run func()) *MockClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta1_Call) Return(flowcontrolV1beta1Interface v1beta19.FlowcontrolV1beta1Interface) *MockClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Return(flowcontrolV1beta1Interface)
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta1_Call) RunAndReturn(run func() v1beta19.FlowcontrolV1beta1Interface) *MockClientSet_FlowcontrolV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) FlowcontrolV1beta2() v1beta20.FlowcontrolV1beta2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta2")
	}

	var r0 v1beta20.FlowcontrolV1beta2Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta20.FlowcontrolV1beta2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta20.FlowcontrolV1beta2Interface)
		}
	}
	return r0
}

// MockClientSet_FlowcontrolV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta2'
type MockClientSet_FlowcontrolV1beta2_Call struct {
	*mock.Call
}

// FlowcontrolV1beta2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) FlowcontrolV1beta2() *MockClientSet_FlowcontrolV1beta2_Call {
	return &MockClientSet_FlowcontrolV1beta2_Call{Call: _e.mock.On("FlowcontrolV1beta2")}
}

func (_c *MockClientSet_FlowcontrolV1beta2_Call) Run(run func()) *MockClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta2_Call) Return(flowcontrolV1beta2Interface v1beta20.FlowcontrolV1beta2Interface) *MockClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Return(flowcontrolV1beta2Interface)
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta2_Call) RunAndReturn(run func() v1beta20.FlowcontrolV1beta2Interface) *MockClientSet_FlowcontrolV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// FlowcontrolV1beta3 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) FlowcontrolV1beta3() v1beta3.FlowcontrolV1beta3Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlowcontrolV1beta3")
	}

	var r0 v1beta3.FlowcontrolV1beta3Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta3.FlowcontrolV1beta3Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta3.FlowcontrolV1beta3Interface)
		}
	}
	return r0
}

// MockClientSet_FlowcontrolV1beta3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlowcontrolV1beta3'
type MockClientSet_FlowcontrolV1beta3_Call struct {
	*mock.Call
}

// FlowcontrolV1beta3 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) FlowcontrolV1beta3() *MockClientSet_FlowcontrolV1beta3_Call {
	return &MockClientSet_FlowcontrolV1beta3_Call{Call: _e.mock.On("FlowcontrolV1beta3")}
}

func (_c *MockClientSet_FlowcontrolV1beta3_Call) Run(run func()) *MockClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta3_Call) Return(flowcontrolV1beta3Interface v1beta3.FlowcontrolV1beta3Interface) *MockClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Return(flowcontrolV1beta3Interface)
	return _c
}

func (_c *MockClientSet_FlowcontrolV1beta3_Call) RunAndReturn(run func() v1beta3.FlowcontrolV1beta3Interface) *MockClientSet_FlowcontrolV1beta3_Call {
	_c.Call.Return(run)
	return _c
}

// InternalV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) InternalV1alpha1() v1alpha12.InternalV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InternalV1alpha1")
	}

	var r0 v1alpha12.InternalV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha12.InternalV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha12.InternalV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_InternalV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalV1alpha1'
type MockClientSet_InternalV1alpha1_Call struct {
	*mock.Call
}

// InternalV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) InternalV1alpha1() *MockClientSet_InternalV1alpha1_Call {
	return &MockClientSet_InternalV1alpha1_Call{Call: _e.mock.On("InternalV1alpha1")}
}

func (_c *MockClientSet_InternalV1alpha1_Call) Run(run func()) *MockClientSet_InternalV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_InternalV1alpha1_Call) Return(internalV1alpha1Interface v1alpha12.InternalV1alpha1Interface) *MockClientSet_InternalV1alpha1_Call {
	_c.Call.Return(internalV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_InternalV1alpha1_Call) RunAndReturn(run func() v1alpha12.InternalV1alpha1Interface) *MockClientSet_InternalV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) NetworkingV1() v111.NetworkingV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetworkingV1")
	}

	var r0 v111.NetworkingV1Interface
	if returnFunc, ok := ret.Get(0).(func() v111.NetworkingV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v111.NetworkingV1Interface)
		}
	}
	return r0
}

// MockClientSet_NetworkingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1'
type MockClientSet_NetworkingV1_Call struct {
	*mock.Call
}

// NetworkingV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) NetworkingV1() *MockClientSet_NetworkingV1_Call {
	return &MockClientSet_NetworkingV1_Call{Call: _e.mock.On("NetworkingV1")}
}

func (_c *MockClientSet_NetworkingV1_Call) Run(run func()) *MockClientSet_NetworkingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_NetworkingV1_Call) Return(networkingV1Interface v111.NetworkingV1Interface) *MockClientSet_NetworkingV1_Call {
	_c.Call.Return(networkingV1Interface)
	return _c
}

func (_c *MockClientSet_NetworkingV1_Call) RunAndReturn(run func() v111.NetworkingV1Interface) *MockClientSet_NetworkingV1_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkingV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) NetworkingV1beta1() v1beta110.NetworkingV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NetworkingV1beta1")
	}

	var r0 v1beta110.NetworkingV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta110.NetworkingV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta110.NetworkingV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_NetworkingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkingV1beta1'
type MockClientSet_NetworkingV1beta1_Call struct {
	*mock.Call
}

// NetworkingV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) NetworkingV1beta1() *MockClientSet_NetworkingV1beta1_Call {
	return &MockClientSet_NetworkingV1beta1_Call{Call: _e.mock.On("NetworkingV1beta1")}
}

func (_c *MockClientSet_NetworkingV1beta1_Call) Run(run func()) *MockClientSet_NetworkingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_NetworkingV1beta1_Call) Return(networkingV1beta1Interface v1beta110.NetworkingV1beta1Interface) *MockClientSet_NetworkingV1beta1_Call {
	_c.Call.Return(networkingV1beta1Interface)
	return _c
}

func (_c *MockClientSet_NetworkingV1beta1_Call) RunAndReturn(run func() v1beta110.NetworkingV1beta1Interface) *MockClientSet_NetworkingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) NodeV1() v112.NodeV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1")
	}

	var r0 v112.NodeV1Interface
	if returnFunc, ok := ret.Get(0).(func() v112.NodeV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v112.NodeV1Interface)
		}
	}
	return r0
}

// MockClientSet_NodeV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1'
type MockClientSet_NodeV1_Call struct {
	*mock.Call
}

// NodeV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) NodeV1() *MockClientSet_NodeV1_Call {
	return &MockClientSet_NodeV1_Call{Call: _e.mock.On("NodeV1")}
}

func (_c *MockClientSet_NodeV1_Call) Run(run func()) *MockClientSet_NodeV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_NodeV1_Call) Return(nodeV1Interface v112.NodeV1Interface) *MockClientSet_NodeV1_Call {
	_c.Call.Return(nodeV1Interface)
	return _c
}

func (_c *MockClientSet_NodeV1_Call) RunAndReturn(run func() v112.NodeV1Interface) *MockClientSet_NodeV1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) NodeV1alpha1() v1alpha13.NodeV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1alpha1")
	}

	var r0 v1alpha13.NodeV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha13.NodeV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha13.NodeV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_NodeV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1alpha1'
type MockClientSet_NodeV1alpha1_Call struct {
	*mock.Call
}

// NodeV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) NodeV1alpha1() *MockClientSet_NodeV1alpha1_Call {
	return &MockClientSet_NodeV1alpha1_Call{Call: _e.mock.On("NodeV1alpha1")}
}

func (_c *MockClientSet_NodeV1alpha1_Call) Run(run func()) *MockClientSet_NodeV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_NodeV1alpha1_Call) Return(nodeV1alpha1Interface v1alpha13.NodeV1alpha1Interface) *MockClientSet_NodeV1alpha1_Call {
	_c.Call.Return(nodeV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_NodeV1alpha1_Call) RunAndReturn(run func() v1alpha13.NodeV1alpha1Interface) *MockClientSet_NodeV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// NodeV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) NodeV1beta1() v1beta111.NodeV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeV1beta1")
	}

	var r0 v1beta111.NodeV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta111.NodeV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta111.NodeV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_NodeV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeV1beta1'
type MockClientSet_NodeV1beta1_Call struct {
	*mock.Call
}

// NodeV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) NodeV1beta1() *MockClientSet_NodeV1beta1_Call {
	return &MockClientSet_NodeV1beta1_Call{Call: _e.mock.On("NodeV1beta1")}
}

func (_c *MockClientSet_NodeV1beta1_Call) Run(run func()) *MockClientSet_NodeV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_NodeV1beta1_Call) Return(nodeV1beta1Interface v1beta111.NodeV1beta1Interface) *MockClientSet_NodeV1beta1_Call {
	_c.Call.Return(nodeV1beta1Interface)
	return _c
}

func (_c *MockClientSet_NodeV1beta1_Call) RunAndReturn(run func() v1beta111.NodeV1beta1Interface) *MockClientSet_NodeV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) PolicyV1() v113.PolicyV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PolicyV1")
	}

	var r0 v113.PolicyV1Interface
	if returnFunc, ok := ret.Get(0).(func() v113.PolicyV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v113.PolicyV1Interface)
		}
	}
	return r0
}

// MockClientSet_PolicyV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1'
type MockClientSet_PolicyV1_Call struct {
	*mock.Call
}

// PolicyV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) PolicyV1() *MockClientSet_PolicyV1_Call {
	return &MockClientSet_PolicyV1_Call{Call: _e.mock.On("PolicyV1")}
}

func (_c *MockClientSet_PolicyV1_Call) Run(run func()) *MockClientSet_PolicyV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_PolicyV1_Call) Return(policyV1Interface v113.PolicyV1Interface) *MockClientSet_PolicyV1_Call {
	_c.Call.Return(policyV1Interface)
	return _c
}

func (_c *MockClientSet_PolicyV1_Call) RunAndReturn(run func() v113.PolicyV1Interface) *MockClientSet_PolicyV1_Call {
	_c.Call.Return(run)
	return _c
}

// PolicyV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) PolicyV1beta1() v1beta112.PolicyV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PolicyV1beta1")
	}

	var r0 v1beta112.PolicyV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta112.PolicyV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta112.PolicyV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_PolicyV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PolicyV1beta1'
type MockClientSet_PolicyV1beta1_Call struct {
	*mock.Call
}

// PolicyV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) PolicyV1beta1() *MockClientSet_PolicyV1beta1_Call {
	return &MockClientSet_PolicyV1beta1_Call{Call: _e.mock.On("PolicyV1beta1")}
}

func (_c *MockClientSet_PolicyV1beta1_Call) Run(run func()) *MockClientSet_PolicyV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_PolicyV1beta1_Call) Return(policyV1beta1Interface v1beta112.PolicyV1beta1Interface) *MockClientSet_PolicyV1beta1_Call {
	_c.Call.Return(policyV1beta1Interface)
	return _c
}

func (_c *MockClientSet_PolicyV1beta1_Call) RunAndReturn(run func() v1beta112.PolicyV1beta1Interface) *MockClientSet_PolicyV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectcalicoV3 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ProjectcalicoV3() v3.ProjectcalicoV3Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectcalicoV3")
	}

	var r0 v3.ProjectcalicoV3Interface
	if returnFunc, ok := ret.Get(0).(func() v3.ProjectcalicoV3Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v3.ProjectcalicoV3Interface)
		}
	}
	return r0
}

// MockClientSet_ProjectcalicoV3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectcalicoV3'
type MockClientSet_ProjectcalicoV3_Call struct {
	*mock.Call
}

// ProjectcalicoV3 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ProjectcalicoV3() *MockClientSet_ProjectcalicoV3_Call {
	return &MockClientSet_ProjectcalicoV3_Call{Call: _e.mock.On("ProjectcalicoV3")}
}

func (_c *MockClientSet_ProjectcalicoV3_Call) Run(run func()) *MockClientSet_ProjectcalicoV3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ProjectcalicoV3_Call) Return(projectcalicoV3Interface v3.ProjectcalicoV3Interface) *MockClientSet_ProjectcalicoV3_Call {
	_c.Call.Return(projectcalicoV3Interface)
	return _c
}

func (_c *MockClientSet_ProjectcalicoV3_Call) RunAndReturn(run func() v3.ProjectcalicoV3Interface) *MockClientSet_ProjectcalicoV3_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) RbacV1() v114.RbacV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1")
	}

	var r0 v114.RbacV1Interface
	if returnFunc, ok := ret.Get(0).(func() v114.RbacV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v114.RbacV1Interface)
		}
	}
	return r0
}

// MockClientSet_RbacV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1'
type MockClientSet_RbacV1_Call struct {
	*mock.Call
}

// RbacV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) RbacV1() *MockClientSet_RbacV1_Call {
	return &MockClientSet_RbacV1_Call{Call: _e.mock.On("RbacV1")}
}

func (_c *MockClientSet_RbacV1_Call) Run(run func()) *MockClientSet_RbacV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_RbacV1_Call) Return(rbacV1Interface v114.RbacV1Interface) *MockClientSet_RbacV1_Call {
	_c.Call.Return(rbacV1Interface)
	return _c
}

func (_c *MockClientSet_RbacV1_Call) RunAndReturn(run func() v114.RbacV1Interface) *MockClientSet_RbacV1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) RbacV1alpha1() v1alpha14.RbacV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1alpha1")
	}

	var r0 v1alpha14.RbacV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha14.RbacV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha14.RbacV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_RbacV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1alpha1'
type MockClientSet_RbacV1alpha1_Call struct {
	*mock.Call
}

// RbacV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) RbacV1alpha1() *MockClientSet_RbacV1alpha1_Call {
	return &MockClientSet_RbacV1alpha1_Call{Call: _e.mock.On("RbacV1alpha1")}
}

func (_c *MockClientSet_RbacV1alpha1_Call) Run(run func()) *MockClientSet_RbacV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_RbacV1alpha1_Call) Return(rbacV1alpha1Interface v1alpha14.RbacV1alpha1Interface) *MockClientSet_RbacV1alpha1_Call {
	_c.Call.Return(rbacV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_RbacV1alpha1_Call) RunAndReturn(run func() v1alpha14.RbacV1alpha1Interface) *MockClientSet_RbacV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// RbacV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) RbacV1beta1() v1beta113.RbacV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RbacV1beta1")
	}

	var r0 v1beta113.RbacV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta113.RbacV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta113.RbacV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_RbacV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RbacV1beta1'
type MockClientSet_RbacV1beta1_Call struct {
	*mock.Call
}

// RbacV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) RbacV1beta1() *MockClientSet_RbacV1beta1_Call {
	return &MockClientSet_RbacV1beta1_Call{Call: _e.mock.On("RbacV1beta1")}
}

func (_c *MockClientSet_RbacV1beta1_Call) Run(run func()) *MockClientSet_RbacV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_RbacV1beta1_Call) Return(rbacV1beta1Interface v1beta113.RbacV1beta1Interface) *MockClientSet_RbacV1beta1_Call {
	_c.Call.Return(rbacV1beta1Interface)
	return _c
}

func (_c *MockClientSet_RbacV1beta1_Call) RunAndReturn(run func() v1beta113.RbacV1beta1Interface) *MockClientSet_RbacV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ResourceV1() v115.ResourceV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1")
	}

	var r0 v115.ResourceV1Interface
	if returnFunc, ok := ret.Get(0).(func() v115.ResourceV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v115.ResourceV1Interface)
		}
	}
	return r0
}

// MockClientSet_ResourceV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1'
type MockClientSet_ResourceV1_Call struct {
	*mock.Call
}

// ResourceV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ResourceV1() *MockClientSet_ResourceV1_Call {
	return &MockClientSet_ResourceV1_Call{Call: _e.mock.On("ResourceV1")}
}

func (_c *MockClientSet_ResourceV1_Call) Run(run func()) *MockClientSet_ResourceV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ResourceV1_Call) Return(resourceV1Interface v115.ResourceV1Interface) *MockClientSet_ResourceV1_Call {
	_c.Call.Return(resourceV1Interface)
	return _c
}

func (_c *MockClientSet_ResourceV1_Call) RunAndReturn(run func() v115.ResourceV1Interface) *MockClientSet_ResourceV1_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1alpha3 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ResourceV1alpha3() v1alpha3.ResourceV1alpha3Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1alpha3")
	}

	var r0 v1alpha3.ResourceV1alpha3Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha3.ResourceV1alpha3Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha3.ResourceV1alpha3Interface)
		}
	}
	return r0
}

// MockClientSet_ResourceV1alpha3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1alpha3'
type MockClientSet_ResourceV1alpha3_Call struct {
	*mock.Call
}

// ResourceV1alpha3 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ResourceV1alpha3() *MockClientSet_ResourceV1alpha3_Call {
	return &MockClientSet_ResourceV1alpha3_Call{Call: _e.mock.On("ResourceV1alpha3")}
}

func (_c *MockClientSet_ResourceV1alpha3_Call) Run(run func()) *MockClientSet_ResourceV1alpha3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ResourceV1alpha3_Call) Return(resourceV1alpha3Interface v1alpha3.ResourceV1alpha3Interface) *MockClientSet_ResourceV1alpha3_Call {
	_c.Call.Return(resourceV1alpha3Interface)
	return _c
}

func (_c *MockClientSet_ResourceV1alpha3_Call) RunAndReturn(run func() v1alpha3.ResourceV1alpha3Interface) *MockClientSet_ResourceV1alpha3_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ResourceV1beta1() v1beta114.ResourceV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1beta1")
	}

	var r0 v1beta114.ResourceV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta114.ResourceV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta114.ResourceV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_ResourceV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1beta1'
type MockClientSet_ResourceV1beta1_Call struct {
	*mock.Call
}

// ResourceV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ResourceV1beta1() *MockClientSet_ResourceV1beta1_Call {
	return &MockClientSet_ResourceV1beta1_Call{Call: _e.mock.On("ResourceV1beta1")}
}

func (_c *MockClientSet_ResourceV1beta1_Call) Run(run func()) *MockClientSet_ResourceV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ResourceV1beta1_Call) Return(resourceV1beta1Interface v1beta114.ResourceV1beta1Interface) *MockClientSet_ResourceV1beta1_Call {
	_c.Call.Return(resourceV1beta1Interface)
	return _c
}

func (_c *MockClientSet_ResourceV1beta1_Call) RunAndReturn(run func() v1beta114.ResourceV1beta1Interface) *MockClientSet_ResourceV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceV1beta2 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) ResourceV1beta2() v1beta21.ResourceV1beta2Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResourceV1beta2")
	}

	var r0 v1beta21.ResourceV1beta2Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta21.ResourceV1beta2Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta21.ResourceV1beta2Interface)
		}
	}
	return r0
}

// MockClientSet_ResourceV1beta2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceV1beta2'
type MockClientSet_ResourceV1beta2_Call struct {
	*mock.Call
}

// ResourceV1beta2 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) ResourceV1beta2() *MockClientSet_ResourceV1beta2_Call {
	return &MockClientSet_ResourceV1beta2_Call{Call: _e.mock.On("ResourceV1beta2")}
}

func (_c *MockClientSet_ResourceV1beta2_Call) Run(run func()) *MockClientSet_ResourceV1beta2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_ResourceV1beta2_Call) Return(resourceV1beta2Interface v1beta21.ResourceV1beta2Interface) *MockClientSet_ResourceV1beta2_Call {
	_c.Call.Return(resourceV1beta2Interface)
	return _c
}

func (_c *MockClientSet_ResourceV1beta2_Call) RunAndReturn(run func() v1beta21.ResourceV1beta2Interface) *MockClientSet_ResourceV1beta2_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) SchedulingV1() v116.SchedulingV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1")
	}

	var r0 v116.SchedulingV1Interface
	if returnFunc, ok := ret.Get(0).(func() v116.SchedulingV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v116.SchedulingV1Interface)
		}
	}
	return r0
}

// MockClientSet_SchedulingV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1'
type MockClientSet_SchedulingV1_Call struct {
	*mock.Call
}

// SchedulingV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) SchedulingV1() *MockClientSet_SchedulingV1_Call {
	return &MockClientSet_SchedulingV1_Call{Call: _e.mock.On("SchedulingV1")}
}

func (_c *MockClientSet_SchedulingV1_Call) Run(run func()) *MockClientSet_SchedulingV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_SchedulingV1_Call) Return(schedulingV1Interface v116.SchedulingV1Interface) *MockClientSet_SchedulingV1_Call {
	_c.Call.Return(schedulingV1Interface)
	return _c
}

func (_c *MockClientSet_SchedulingV1_Call) RunAndReturn(run func() v116.SchedulingV1Interface) *MockClientSet_SchedulingV1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) SchedulingV1alpha1() v1alpha15.SchedulingV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1alpha1")
	}

	var r0 v1alpha15.SchedulingV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha15.SchedulingV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha15.SchedulingV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_SchedulingV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1alpha1'
type MockClientSet_SchedulingV1alpha1_Call struct {
	*mock.Call
}

// SchedulingV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) SchedulingV1alpha1() *MockClientSet_SchedulingV1alpha1_Call {
	return &MockClientSet_SchedulingV1alpha1_Call{Call: _e.mock.On("SchedulingV1alpha1")}
}

func (_c *MockClientSet_SchedulingV1alpha1_Call) Run(run func()) *MockClientSet_SchedulingV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_SchedulingV1alpha1_Call) Return(schedulingV1alpha1Interface v1alpha15.SchedulingV1alpha1Interface) *MockClientSet_SchedulingV1alpha1_Call {
	_c.Call.Return(schedulingV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_SchedulingV1alpha1_Call) RunAndReturn(run func() v1alpha15.SchedulingV1alpha1Interface) *MockClientSet_SchedulingV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// SchedulingV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) SchedulingV1beta1() v1beta115.SchedulingV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SchedulingV1beta1")
	}

	var r0 v1beta115.SchedulingV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta115.SchedulingV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta115.SchedulingV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_SchedulingV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchedulingV1beta1'
type MockClientSet_SchedulingV1beta1_Call struct {
	*mock.Call
}

// SchedulingV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) SchedulingV1beta1() *MockClientSet_SchedulingV1beta1_Call {
	return &MockClientSet_SchedulingV1beta1_Call{Call: _e.mock.On("SchedulingV1beta1")}
}

func (_c *MockClientSet_SchedulingV1beta1_Call) Run(run func()) *MockClientSet_SchedulingV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_SchedulingV1beta1_Call) Return(schedulingV1beta1Interface v1beta115.SchedulingV1beta1Interface) *MockClientSet_SchedulingV1beta1_Call {
	_c.Call.Return(schedulingV1beta1Interface)
	return _c
}

func (_c *MockClientSet_SchedulingV1beta1_Call) RunAndReturn(run func() v1beta115.SchedulingV1beta1Interface) *MockClientSet_SchedulingV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) StorageV1() v117.StorageV1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1")
	}

	var r0 v117.StorageV1Interface
	if returnFunc, ok := ret.Get(0).(func() v117.StorageV1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v117.StorageV1Interface)
		}
	}
	return r0
}

// MockClientSet_StorageV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1'
type MockClientSet_StorageV1_Call struct {
	*mock.Call
}

// StorageV1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) StorageV1() *MockClientSet_StorageV1_Call {
	return &MockClientSet_StorageV1_Call{Call: _e.mock.On("StorageV1")}
}

func (_c *MockClientSet_StorageV1_Call) Run(run func()) *MockClientSet_StorageV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_StorageV1_Call) Return(storageV1Interface v117.StorageV1Interface) *MockClientSet_StorageV1_Call {
	_c.Call.Return(storageV1Interface)
	return _c
}

func (_c *MockClientSet_StorageV1_Call) RunAndReturn(run func() v117.StorageV1Interface) *MockClientSet_StorageV1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1alpha1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) StorageV1alpha1() v1alpha16.StorageV1alpha1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1alpha1")
	}

	var r0 v1alpha16.StorageV1alpha1Interface
	if returnFunc, ok := ret.Get(0).(func() v1alpha16.StorageV1alpha1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha16.StorageV1alpha1Interface)
		}
	}
	return r0
}

// MockClientSet_StorageV1alpha1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1alpha1'
type MockClientSet_StorageV1alpha1_Call struct {
	*mock.Call
}

// StorageV1alpha1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) StorageV1alpha1() *MockClientSet_StorageV1alpha1_Call {
	return &MockClientSet_StorageV1alpha1_Call{Call: _e.mock.On("StorageV1alpha1")}
}

func (_c *MockClientSet_StorageV1alpha1_Call) Run(run func()) *MockClientSet_StorageV1alpha1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_StorageV1alpha1_Call) Return(storageV1alpha1Interface v1alpha16.StorageV1alpha1Interface) *MockClientSet_StorageV1alpha1_Call {
	_c.Call.Return(storageV1alpha1Interface)
	return _c
}

func (_c *MockClientSet_StorageV1alpha1_Call) RunAndReturn(run func() v1alpha16.StorageV1alpha1Interface) *MockClientSet_StorageV1alpha1_Call {
	_c.Call.Return(run)
	return _c
}

// StorageV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) StorageV1beta1() v1beta116.StorageV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StorageV1beta1")
	}

	var r0 v1beta116.StorageV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta116.StorageV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta116.StorageV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_StorageV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageV1beta1'
type MockClientSet_StorageV1beta1_Call struct {
	*mock.Call
}

// StorageV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) StorageV1beta1() *MockClientSet_StorageV1beta1_Call {
	return &MockClientSet_StorageV1beta1_Call{Call: _e.mock.On("StorageV1beta1")}
}

func (_c *MockClientSet_StorageV1beta1_Call) Run(run func()) *MockClientSet_StorageV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_StorageV1beta1_Call) Return(storageV1beta1Interface v1beta116.StorageV1beta1Interface) *MockClientSet_StorageV1beta1_Call {
	_c.Call.Return(storageV1beta1Interface)
	return _c
}

func (_c *MockClientSet_StorageV1beta1_Call) RunAndReturn(run func() v1beta116.StorageV1beta1Interface) *MockClientSet_StorageV1beta1_Call {
	_c.Call.Return(run)
	return _c
}

// StoragemigrationV1beta1 provides a mock function for the type MockClientSet
func (_mock *MockClientSet) StoragemigrationV1beta1() v1beta117.StoragemigrationV1beta1Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StoragemigrationV1beta1")
	}

	var r0 v1beta117.StoragemigrationV1beta1Interface
	if returnFunc, ok := ret.Get(0).(func() v1beta117.StoragemigrationV1beta1Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta117.StoragemigrationV1beta1Interface)
		}
	}
	return r0
}

// MockClientSet_StoragemigrationV1beta1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoragemigrationV1beta1'
type MockClientSet_StoragemigrationV1beta1_Call struct {
	*mock.Call
}

// StoragemigrationV1beta1 is a helper method to define mock.On call
func (_e *MockClientSet_Expecter) StoragemigrationV1beta1() *MockClientSet_StoragemigrationV1beta1_Call {
	return &MockClientSet_StoragemigrationV1beta1_Call{Call: _e.mock.On("StoragemigrationV1beta1")}
}

func (_c *MockClientSet_StoragemigrationV1beta1_Call) Run(run func()) *MockClientSet_StoragemigrationV1beta1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientSet_StoragemigrationV1beta1_Call) Return(storagemigrationV1beta1Interface v1beta117.StoragemigrationV1beta1Interface) *MockClientSet_StoragemigrationV1beta1_Call {
	_c.Call.Return(storagemigrationV1beta1Interface)
	return _c
}

func (_c *MockClientSet_StoragemigrationV1beta1_Call) RunAndReturn(run func() v1beta117.StoragemigrationV1beta1Interface) *MockClientSet_StoragemigrationV1beta1_Call {
	_c.Call.Return(run)
	return _c
}
