apiVersion: projectcalico.org/v3
kind: GlobalThreatFeed
metadata:
  name: vpn-feed
spec:
  pull:
    http:
      url: https://raw.githubusercontent.com/X4BNet/lists_vpn/main/ipv4.txt
  globalNetworkSet:
    labels:
      feed: vpn-feed
