// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileMaintainer creates a new instance of MockFileMaintainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileMaintainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileMaintainer {
	mock := &MockFileMaintainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileMaintainer is an autogenerated mock type for the FileMaintainer type
type MockFileMaintainer struct {
	mock.Mock
}

type MockFileMaintainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileMaintainer) EXPECT() *MockFileMaintainer_Expecter {
	return &MockFileMaintainer_Expecter{mock: &_m.Mock}
}

// Maintain provides a mock function for the type MockFileMaintainer
func (_mock *MockFileMaintainer) Maintain(path string) {
	_mock.Called(path)
	return
}

// MockFileMaintainer_Maintain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Maintain'
type MockFileMaintainer_Maintain_Call struct {
	*mock.Call
}

// Maintain is a helper method to define mock.On call
//   - path string
func (_e *MockFileMaintainer_Expecter) Maintain(path interface{}) *MockFileMaintainer_Maintain_Call {
	return &MockFileMaintainer_Maintain_Call{Call: _e.mock.On("Maintain", path)}
}

func (_c *MockFileMaintainer_Maintain_Call) Run(run func(path string)) *MockFileMaintainer_Maintain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileMaintainer_Maintain_Call) Return() *MockFileMaintainer_Maintain_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileMaintainer_Maintain_Call) RunAndReturn(run func(path string)) *MockFileMaintainer_Maintain_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockFileMaintainer
func (_mock *MockFileMaintainer) Run(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockFileMaintainer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFileMaintainer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileMaintainer_Expecter) Run(ctx interface{}) *MockFileMaintainer_Run_Call {
	return &MockFileMaintainer_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockFileMaintainer_Run_Call) Run(run func(ctx context.Context)) *MockFileMaintainer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileMaintainer_Run_Call) Return() *MockFileMaintainer_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileMaintainer_Run_Call) RunAndReturn(run func(ctx context.Context)) *MockFileMaintainer_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockFileMaintainer
func (_mock *MockFileMaintainer) Stop(path string) {
	_mock.Called(path)
	return
}

// MockFileMaintainer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockFileMaintainer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - path string
func (_e *MockFileMaintainer_Expecter) Stop(path interface{}) *MockFileMaintainer_Stop_Call {
	return &MockFileMaintainer_Stop_Call{Call: _e.mock.On("Stop", path)}
}

func (_c *MockFileMaintainer_Stop_Call) Run(run func(path string)) *MockFileMaintainer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileMaintainer_Stop_Call) Return() *MockFileMaintainer_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileMaintainer_Stop_Call) RunAndReturn(run func(path string)) *MockFileMaintainer_Stop_Call {
	_c.Run(run)
	return _c
}
