// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/authorization/v1"
	"k8s.io/apiserver/pkg/authentication/user"
)

// NewMockRBACAuthorizer creates a new instance of MockRBACAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRBACAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRBACAuthorizer {
	mock := &MockRBACAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRBACAuthorizer is an autogenerated mock type for the RBACAuthorizer type
type MockRBACAuthorizer struct {
	mock.Mock
}

type MockRBACAuthorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRBACAuthorizer) EXPECT() *MockRBACAuthorizer_Expecter {
	return &MockRBACAuthorizer_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type MockRBACAuthorizer
func (_mock *MockRBACAuthorizer) Authorize(usr user.Info, resources *v1.ResourceAttributes, nonResources *v1.NonResourceAttributes) (bool, error) {
	ret := _mock.Called(usr, resources, nonResources)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) (bool, error)); ok {
		return returnFunc(usr, resources, nonResources)
	}
	if returnFunc, ok := ret.Get(0).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) bool); ok {
		r0 = returnFunc(usr, resources, nonResources)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) error); ok {
		r1 = returnFunc(usr, resources, nonResources)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRBACAuthorizer_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockRBACAuthorizer_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - usr user.Info
//   - resources *v1.ResourceAttributes
//   - nonResources *v1.NonResourceAttributes
func (_e *MockRBACAuthorizer_Expecter) Authorize(usr interface{}, resources interface{}, nonResources interface{}) *MockRBACAuthorizer_Authorize_Call {
	return &MockRBACAuthorizer_Authorize_Call{Call: _e.mock.On("Authorize", usr, resources, nonResources)}
}

func (_c *MockRBACAuthorizer_Authorize_Call) Run(run func(usr user.Info, resources *v1.ResourceAttributes, nonResources *v1.NonResourceAttributes)) *MockRBACAuthorizer_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.Info
		if args[0] != nil {
			arg0 = args[0].(user.Info)
		}
		var arg1 *v1.ResourceAttributes
		if args[1] != nil {
			arg1 = args[1].(*v1.ResourceAttributes)
		}
		var arg2 *v1.NonResourceAttributes
		if args[2] != nil {
			arg2 = args[2].(*v1.NonResourceAttributes)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRBACAuthorizer_Authorize_Call) Return(b bool, err error) *MockRBACAuthorizer_Authorize_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRBACAuthorizer_Authorize_Call) RunAndReturn(run func(usr user.Info, resources *v1.ResourceAttributes, nonResources *v1.NonResourceAttributes) (bool, error)) *MockRBACAuthorizer_Authorize_Call {
	_c.Call.Return(run)
	return _c
}
