// Code generated by mockery v2.53.4. DO NOT EDIT.

package auth

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/authorization/v1"
	user "k8s.io/apiserver/pkg/authentication/user"
)

// MockRBACAuthorizer is an autogenerated mock type for the RBACAuthorizer type
type MockRBACAuthorizer struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: usr, resources, nonResources
func (_m *MockRBACAuthorizer) Authorize(usr user.Info, resources *v1.ResourceAttributes, nonResources *v1.NonResourceAttributes) (bool, error) {
	ret := _m.Called(usr, resources, nonResources)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) (bool, error)); ok {
		return rf(usr, resources, nonResources)
	}
	if rf, ok := ret.Get(0).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) bool); ok {
		r0 = rf(usr, resources, nonResources)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(user.Info, *v1.ResourceAttributes, *v1.NonResourceAttributes) error); ok {
		r1 = rf(usr, resources, nonResources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRBACAuthorizer creates a new instance of MockRBACAuthorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRBACAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRBACAuthorizer {
	mock := &MockRBACAuthorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
